#!/usr/bin/env tsx
import { existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

/**
 * Icon generation script for @meldui/tabler-vue
 *
 * This script:
 * 1. Imports all icons from @tabler/icons-vue
 * 2. Generates individual files for each icon in src/icons/
 * 3. Generates a barrel index.ts that re-exports all icons
 *
 * This approach enables optimal tree-shaking - consumers only bundle
 * the icons they actually import.
 *
 * Run this script whenever @tabler/icons-vue is updated to sync new icons.
 *
 * Usage: pnpm generate-icons
 */

async function generateIcons() {
  console.log('🔄 Generating icon files...')

  // Import all Tabler icons
  const tablerIcons = await import('@tabler/icons-vue')

  // Get all icon names (exports starting with 'Icon')
  const iconNames = Object.keys(tablerIcons).filter(
    (name) => name.startsWith('Icon') && name !== 'Icon',
  )

  console.log(`📦 Found ${iconNames.length} icons from @tabler/icons-vue`)

  // Create icons directory (clean it first if exists)
  const iconsDir = resolve(__dirname, '../src/icons')
  if (existsSync(iconsDir)) {
    rmSync(iconsDir, { recursive: true })
  }
  mkdirSync(iconsDir, { recursive: true })

  // Generate individual icon files
  console.log('📝 Generating individual icon files...')
  for (const name of iconNames) {
    const iconFileContent = `/**
 * Auto-generated icon: ${name}
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { ${name} as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const ${name} = createIcon(TablerIcon)
`
    writeFileSync(resolve(iconsDir, `${name}.ts`), iconFileContent, 'utf-8')
  }

  console.log(`✅ Generated ${iconNames.length} individual icon files`)

  // Generate barrel index.ts with re-exports
  const indexContent = `/**
 * Auto-generated icon exports for @meldui/tabler-vue
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 * Generated by: pnpm generate-icons
 * Generated on: ${new Date().toISOString()}
 *
 * This file re-exports all Tabler icons with MeldUI defaults applied.
 * Each icon is in its own module for optimal tree-shaking.
 *
 * Usage:
 *   import { IconUser, IconSettings } from '@meldui/tabler-vue'
 *
 * Only the icons you import will be included in your bundle.
 */

// Re-export all icons from individual files
${iconNames.map((name) => `export { ${name} } from './icons/${name}'`).join('\n')}

// Re-export utilities
export { createIcon } from './wrapper'
export { ICON_DEFAULTS } from './defaults'
export type { IconDefaults } from './defaults'
`

  // Write to src/index.ts
  const indexPath = resolve(__dirname, '../src/index.ts')
  writeFileSync(indexPath, indexContent, 'utf-8')

  console.log(`📝 Generated barrel index.ts with ${iconNames.length} re-exports`)
  console.log('✅ Icon generation complete!')
  console.log('')
  console.log('Tree-shaking is now enabled:')
  console.log('  - Each icon is in its own module (src/icons/*.ts)')
  console.log('  - Consumers only bundle icons they import')
  console.log('  - Expected: ~2-5KB per icon vs 3.5MB for all icons')
}

// Run the generator
generateIcons().catch(console.error)
