/**
 * Auto-generated icon: IconRss
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRss as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRss = createIcon(TablerIcon)
