/**
 * Auto-generated icon: IconFlag3Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFlag3Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFlag3Filled = createIcon(TablerIcon)
