/**
 * Auto-generated icon: IconBarbellFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBarbellFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBarbellFilled = createIcon(TablerIcon)
