/**
 * Auto-generated icon: IconAdjustmentsPlus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAdjustmentsPlus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAdjustmentsPlus = createIcon(TablerIcon)
