/**
 * Auto-generated icon: IconHandLittleFinger
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHandLittleFinger as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHandLittleFinger = createIcon(TablerIcon)
