/**
 * Auto-generated icon: IconCornerLeftDown
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCornerLeftDown as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCornerLeftDown = createIcon(TablerIcon)
