/**
 * Auto-generated icon: IconRouteScan
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRouteScan as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRouteScan = createIcon(TablerIcon)
