/**
 * Auto-generated icon: IconTent
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTent as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTent = createIcon(TablerIcon)
