/**
 * Auto-generated icon: IconParenthesesOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconParenthesesOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconParenthesesOff = createIcon(TablerIcon)
