/**
 * Auto-generated icon: IconWashDrycleanOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconWashDrycleanOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconWashDrycleanOff = createIcon(TablerIcon)
