/**
 * Auto-generated icon: IconAdjustmentsPause
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAdjustmentsPause as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAdjustmentsPause = createIcon(TablerIcon)
