/**
 * Auto-generated icon: IconBrandLeetcode
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandLeetcode as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandLeetcode = createIcon(TablerIcon)
