/**
 * Auto-generated icon: IconCross
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCross as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCross = createIcon(TablerIcon)
