/**
 * Auto-generated icon: IconDeviceDesktopUp
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceDesktopUp as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceDesktopUp = createIcon(TablerIcon)
