/**
 * Auto-generated icon: IconCurrencyEuro
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCurrencyEuro as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCurrencyEuro = createIcon(TablerIcon)
