/**
 * Auto-generated icon: IconDna2
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDna2 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDna2 = createIcon(TablerIcon)
