/**
 * Auto-generated icon: IconMessageCircleMinus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMessageCircleMinus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMessageCircleMinus = createIcon(TablerIcon)
