/**
 * Auto-generated icon: IconCodeVariablePlus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCodeVariablePlus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCodeVariablePlus = createIcon(TablerIcon)
