/**
 * Auto-generated icon: IconSwipeLeft
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSwipeLeft as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSwipeLeft = createIcon(TablerIcon)
