/**
 * Auto-generated icon: IconTheater
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTheater as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTheater = createIcon(TablerIcon)
