/**
 * Auto-generated icon: IconBrandMeetup
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandMeetup as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandMeetup = createIcon(TablerIcon)
