/**
 * Auto-generated icon: IconShieldCog
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconShieldCog as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconShieldCog = createIcon(TablerIcon)
