/**
 * Auto-generated icon: IconBrandMixpanel
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandMixpanel as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandMixpanel = createIcon(TablerIcon)
