/**
 * Auto-generated icon: IconLockPin
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLockPin as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLockPin = createIcon(TablerIcon)
