/**
 * Auto-generated icon: IconSquareNumber6Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareNumber6Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareNumber6Filled = createIcon(TablerIcon)
