/**
 * Auto-generated icon: IconAlarmSnooze
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAlarmSnooze as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAlarmSnooze = createIcon(TablerIcon)
