/**
 * Auto-generated icon: IconCalendarTime
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCalendarTime as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCalendarTime = createIcon(TablerIcon)
