/**
 * Auto-generated icon: IconAnalyzeOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAnalyzeOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAnalyzeOff = createIcon(TablerIcon)
