/**
 * Auto-generated icon: IconSunFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSunFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSunFilled = createIcon(TablerIcon)
