/**
 * Auto-generated icon: IconLetterL
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLetterL as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLetterL = createIcon(TablerIcon)
