/**
 * Auto-generated icon: IconBrandYoutube
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandYoutube as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandYoutube = createIcon(TablerIcon)
