/**
 * Auto-generated icon: IconLogicAnd
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLogicAnd as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLogicAnd = createIcon(TablerIcon)
