/**
 * Auto-generated icon: IconHttpOptionsOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHttpOptionsOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHttpOptionsOff = createIcon(TablerIcon)
