/**
 * Auto-generated icon: IconGpsFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconGpsFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconGpsFilled = createIcon(TablerIcon)
