/**
 * Auto-generated icon: IconMenu3
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMenu3 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMenu3 = createIcon(TablerIcon)
