/**
 * Auto-generated icon: IconSquare6
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquare6 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquare6 = createIcon(TablerIcon)
