/**
 * Auto-generated icon: IconNumber24Small
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNumber24Small as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNumber24Small = createIcon(TablerIcon)
