/**
 * Auto-generated icon: IconBrandCypress
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandCypress as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandCypress = createIcon(TablerIcon)
