/**
 * Auto-generated icon: IconHexagon9
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHexagon9 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHexagon9 = createIcon(TablerIcon)
