/**
 * Auto-generated icon: IconCloudX
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCloudX as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCloudX = createIcon(TablerIcon)
