/**
 * Auto-generated icon: IconTopologyStarRing3
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTopologyStarRing3 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTopologyStarRing3 = createIcon(TablerIcon)
