/**
 * Auto-generated icon: IconShirtSport
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconShirtSport as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconShirtSport = createIcon(TablerIcon)
