/**
 * Auto-generated icon: IconMessageFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMessageFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMessageFilled = createIcon(TablerIcon)
