/**
 * Auto-generated icon: IconSignalH
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSignalH as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSignalH = createIcon(TablerIcon)
