/**
 * Auto-generated icon: IconSpeedboatFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSpeedboatFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSpeedboatFilled = createIcon(TablerIcon)
