/**
 * Auto-generated icon: IconCircleDashedLetterQ
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleDashedLetterQ as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleDashedLetterQ = createIcon(TablerIcon)
