/**
 * Auto-generated icon: IconReplaceUser
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconReplaceUser as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconReplaceUser = createIcon(TablerIcon)
