/**
 * Auto-generated icon: IconAppsOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAppsOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAppsOff = createIcon(TablerIcon)
