/**
 * Auto-generated icon: IconSquareNumber5Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareNumber5Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareNumber5Filled = createIcon(TablerIcon)
