/**
 * Auto-generated icon: IconArrowRightRhombusFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowRightRhombusFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowRightRhombusFilled = createIcon(TablerIcon)
