/**
 * Auto-generated icon: IconBoxMultiple6
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBoxMultiple6 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBoxMultiple6 = createIcon(TablerIcon)
