/**
 * Auto-generated icon: IconEggOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconEggOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconEggOff = createIcon(TablerIcon)
