/**
 * Auto-generated icon: IconKerning
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconKerning as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconKerning = createIcon(TablerIcon)
