/**
 * Auto-generated icon: IconCurrencyBahraini
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCurrencyBahraini as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCurrencyBahraini = createIcon(TablerIcon)
