/**
 * Auto-generated icon: IconRulerMeasure
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRulerMeasure as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRulerMeasure = createIcon(TablerIcon)
