/**
 * Auto-generated icon: IconArrowsRight
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowsRight as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowsRight = createIcon(TablerIcon)
