/**
 * Auto-generated icon: IconRoute
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRoute as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRoute = createIcon(TablerIcon)
