/**
 * Auto-generated icon: IconMoneybagHeart
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMoneybagHeart as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMoneybagHeart = createIcon(TablerIcon)
