/**
 * Auto-generated icon: IconAxe
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAxe as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAxe = createIcon(TablerIcon)
