/**
 * Auto-generated icon: IconCopyleftOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCopyleftOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCopyleftOff = createIcon(TablerIcon)
