/**
 * Auto-generated icon: IconGitCommit
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconGitCommit as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconGitCommit = createIcon(TablerIcon)
