/**
 * Auto-generated icon: IconLayoutAlignBottom
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLayoutAlignBottom as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLayoutAlignBottom = createIcon(TablerIcon)
