/**
 * Auto-generated icon: IconZoomReset
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconZoomReset as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconZoomReset = createIcon(TablerIcon)
