/**
 * Auto-generated icon: IconArrowNarrowLeftDashed
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowNarrowLeftDashed as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowNarrowLeftDashed = createIcon(TablerIcon)
