/**
 * Auto-generated icon: IconPinnedOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPinnedOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPinnedOff = createIcon(TablerIcon)
