/**
 * Auto-generated icon: IconMountain
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMountain as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMountain = createIcon(TablerIcon)
