/**
 * Auto-generated icon: IconAlt
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAlt as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAlt = createIcon(TablerIcon)
