/**
 * Auto-generated icon: IconUserBolt
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconUserBolt as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconUserBolt = createIcon(TablerIcon)
