/**
 * Auto-generated icon: IconCarouselVertical
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCarouselVertical as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCarouselVertical = createIcon(TablerIcon)
