/**
 * Auto-generated icon: IconKeyframeAlignHorizontal
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconKeyframeAlignHorizontal as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconKeyframeAlignHorizontal = createIcon(TablerIcon)
