/**
 * Auto-generated icon: IconSquareToggleHorizontal
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareToggleHorizontal as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareToggleHorizontal = createIcon(TablerIcon)
