/**
 * Auto-generated icon: IconHomeOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHomeOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHomeOff = createIcon(TablerIcon)
