/**
 * Auto-generated icon: IconMoodSmileDizzy
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMoodSmileDizzy as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMoodSmileDizzy = createIcon(TablerIcon)
