/**
 * Auto-generated icon: IconChartBarPopular
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconChartBarPopular as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconChartBarPopular = createIcon(TablerIcon)
