/**
 * Auto-generated icon: IconZeppelinFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconZeppelinFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconZeppelinFilled = createIcon(TablerIcon)
