/**
 * Auto-generated icon: IconMusicDown
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMusicDown as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMusicDown = createIcon(TablerIcon)
