/**
 * Auto-generated icon: IconNumber88Small
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNumber88Small as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNumber88Small = createIcon(TablerIcon)
