/**
 * Auto-generated icon: IconHttpConnect
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHttpConnect as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHttpConnect = createIcon(TablerIcon)
