/**
 * Auto-generated icon: IconComet
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconComet as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconComet = createIcon(TablerIcon)
