/**
 * Auto-generated icon: IconLollipopOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLollipopOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLollipopOff = createIcon(TablerIcon)
