/**
 * Auto-generated icon: IconSunElectricity
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSunElectricity as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSunElectricity = createIcon(TablerIcon)
