/**
 * Auto-generated icon: IconClockHeart
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconClockHeart as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconClockHeart = createIcon(TablerIcon)
