/**
 * Auto-generated icon: IconRegexOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRegexOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRegexOff = createIcon(TablerIcon)
