/**
 * Auto-generated icon: IconMicrophone2Off
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMicrophone2Off as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMicrophone2Off = createIcon(TablerIcon)
