/**
 * Auto-generated icon: IconTriangleSquareCircle
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTriangleSquareCircle as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTriangleSquareCircle = createIcon(TablerIcon)
