/**
 * Auto-generated icon: IconRestore
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRestore as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRestore = createIcon(TablerIcon)
