/**
 * Auto-generated icon: IconHomeStats
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHomeStats as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHomeStats = createIcon(TablerIcon)
