/**
 * Auto-generated icon: IconBrandSpacehey
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandSpacehey as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandSpacehey = createIcon(TablerIcon)
