/**
 * Auto-generated icon: IconChartDonutFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconChartDonutFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconChartDonutFilled = createIcon(TablerIcon)
