/**
 * Auto-generated icon: IconBuildingStadium
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBuildingStadium as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBuildingStadium = createIcon(TablerIcon)
