/**
 * Auto-generated icon: IconFileUpload
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileUpload as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileUpload = createIcon(TablerIcon)
