/**
 * Auto-generated icon: IconPaperclip
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPaperclip as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPaperclip = createIcon(TablerIcon)
