/**
 * Auto-generated icon: IconTimeDuration10
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTimeDuration10 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTimeDuration10 = createIcon(TablerIcon)
