/**
 * Auto-generated icon: IconPlayCardAFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPlayCardAFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPlayCardAFilled = createIcon(TablerIcon)
