/**
 * Auto-generated icon: IconLetterFSmall
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLetterFSmall as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLetterFSmall = createIcon(TablerIcon)
