/**
 * Auto-generated icon: IconPercentage66
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPercentage66 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPercentage66 = createIcon(TablerIcon)
