/**
 * Auto-generated icon: IconCircleChevronsDownFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleChevronsDownFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleChevronsDownFilled = createIcon(TablerIcon)
