/**
 * Auto-generated icon: IconClockStar
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconClockStar as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconClockStar = createIcon(TablerIcon)
