/**
 * Auto-generated icon: IconBroadcastOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBroadcastOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBroadcastOff = createIcon(TablerIcon)
