/**
 * Auto-generated icon: IconPercentage20
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPercentage20 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPercentage20 = createIcon(TablerIcon)
