/**
 * Auto-generated icon: IconLockAccess
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLockAccess as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLockAccess = createIcon(TablerIcon)
