/**
 * Auto-generated icon: IconChevronsRight
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconChevronsRight as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconChevronsRight = createIcon(TablerIcon)
