/**
 * Auto-generated icon: IconTerminal2
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTerminal2 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTerminal2 = createIcon(TablerIcon)
