/**
 * Auto-generated icon: IconDeviceIpadStar
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceIpadStar as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceIpadStar = createIcon(TablerIcon)
