/**
 * Auto-generated icon: IconFileShredder
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileShredder as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileShredder = createIcon(TablerIcon)
