/**
 * Auto-generated icon: IconGitMerge
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconGitMerge as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconGitMerge = createIcon(TablerIcon)
