/**
 * Auto-generated icon: IconCameraUp
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCameraUp as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCameraUp = createIcon(TablerIcon)
