/**
 * Auto-generated icon: IconDeviceWatchCog
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceWatchCog as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceWatchCog = createIcon(TablerIcon)
