/**
 * Auto-generated icon: IconLayoutBottombarExpandFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLayoutBottombarExpandFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLayoutBottombarExpandFilled = createIcon(TablerIcon)
