/**
 * Auto-generated icon: IconCone
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCone as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCone = createIcon(TablerIcon)
