/**
 * Auto-generated icon: IconPercentage90
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPercentage90 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPercentage90 = createIcon(TablerIcon)
