/**
 * Auto-generated icon: IconSquareLetterGFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareLetterGFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareLetterGFilled = createIcon(TablerIcon)
