/**
 * Auto-generated icon: IconZodiacGemini
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconZodiacGemini as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconZodiacGemini = createIcon(TablerIcon)
