/**
 * Auto-generated icon: IconUsers
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconUsers as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconUsers = createIcon(TablerIcon)
