/**
 * Auto-generated icon: IconBackslash
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBackslash as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBackslash = createIcon(TablerIcon)
