/**
 * Auto-generated icon: IconPictureInPicture
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPictureInPicture as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPictureInPicture = createIcon(TablerIcon)
