/**
 * Auto-generated icon: IconCrutchesOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCrutchesOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCrutchesOff = createIcon(TablerIcon)
