/**
 * Auto-generated icon: IconHeading
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHeading as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHeading = createIcon(TablerIcon)
