/**
 * Auto-generated icon: IconMathXy
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMathXy as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMathXy = createIcon(TablerIcon)
