/**
 * Auto-generated icon: IconMailUp
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMailUp as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMailUp = createIcon(TablerIcon)
