/**
 * Auto-generated icon: IconCircleDashedPercentage
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleDashedPercentage as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleDashedPercentage = createIcon(TablerIcon)
