/**
 * Auto-generated icon: IconZoomIn
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconZoomIn as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconZoomIn = createIcon(TablerIcon)
