/**
 * Auto-generated icon: IconHierarchy3
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHierarchy3 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHierarchy3 = createIcon(TablerIcon)
