/**
 * Auto-generated icon: IconFolderPin
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFolderPin as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFolderPin = createIcon(TablerIcon)
