/**
 * Auto-generated icon: IconLayersLinked
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLayersLinked as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLayersLinked = createIcon(TablerIcon)
