/**
 * Auto-generated icon: IconAlignBoxRightMiddle
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAlignBoxRightMiddle as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAlignBoxRightMiddle = createIcon(TablerIcon)
