/**
 * Auto-generated icon: IconCarouselHorizontalFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCarouselHorizontalFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCarouselHorizontalFilled = createIcon(TablerIcon)
