/**
 * Auto-generated icon: IconRepeatOnce
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRepeatOnce as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRepeatOnce = createIcon(TablerIcon)
