/**
 * Auto-generated icon: IconCursorText
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCursorText as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCursorText = createIcon(TablerIcon)
