/**
 * Auto-generated icon: IconSort90
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSort90 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSort90 = createIcon(TablerIcon)
