/**
 * Auto-generated icon: IconHighlightOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHighlightOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHighlightOff = createIcon(TablerIcon)
