/**
 * Auto-generated icon: IconOlympicsOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconOlympicsOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconOlympicsOff = createIcon(TablerIcon)
