/**
 * Auto-generated icon: IconSignal5g
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSignal5g as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSignal5g = createIcon(TablerIcon)
