/**
 * Auto-generated icon: IconCircleLetterR
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleLetterR as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleLetterR = createIcon(TablerIcon)
