/**
 * Auto-generated icon: IconHeartsOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHeartsOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHeartsOff = createIcon(TablerIcon)
