/**
 * Auto-generated icon: IconHexagonFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHexagonFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHexagonFilled = createIcon(TablerIcon)
