/**
 * Auto-generated icon: IconPlayCardJFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPlayCardJFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPlayCardJFilled = createIcon(TablerIcon)
