/**
 * Auto-generated icon: IconCameraStar
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCameraStar as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCameraStar = createIcon(TablerIcon)
