/**
 * Auto-generated icon: IconRowRemove
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRowRemove as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRowRemove = createIcon(TablerIcon)
