/**
 * Auto-generated icon: IconBellCode
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBellCode as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBellCode = createIcon(TablerIcon)
