/**
 * Auto-generated icon: IconChevronsUpLeft
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconChevronsUpLeft as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconChevronsUpLeft = createIcon(TablerIcon)
