/**
 * Auto-generated icon: IconNavigationHeart
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNavigationHeart as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNavigationHeart = createIcon(TablerIcon)
