/**
 * Auto-generated icon: IconFileBarcode
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileBarcode as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileBarcode = createIcon(TablerIcon)
