/**
 * Auto-generated icon: IconCircleLetterWFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleLetterWFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleLetterWFilled = createIcon(TablerIcon)
