/**
 * Auto-generated icon: IconMailQuestion
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMailQuestion as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMailQuestion = createIcon(TablerIcon)
