/**
 * Auto-generated icon: IconMask
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMask as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMask = createIcon(TablerIcon)
