/**
 * Auto-generated icon: IconBorderNone
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBorderNone as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBorderNone = createIcon(TablerIcon)
