/**
 * Auto-generated icon: IconTimelineEvent
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTimelineEvent as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTimelineEvent = createIcon(TablerIcon)
