/**
 * Auto-generated icon: IconBasketCancel
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBasketCancel as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBasketCancel = createIcon(TablerIcon)
