/**
 * Auto-generated icon: IconClipboardHeart
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconClipboardHeart as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconClipboardHeart = createIcon(TablerIcon)
