/**
 * Auto-generated icon: IconShieldMinus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconShieldMinus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconShieldMinus = createIcon(TablerIcon)
