/**
 * Auto-generated icon: IconCheckupList
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCheckupList as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCheckupList = createIcon(TablerIcon)
