/**
 * Auto-generated icon: IconSquareForbid2
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareForbid2 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareForbid2 = createIcon(TablerIcon)
