/**
 * Auto-generated icon: IconBrandTeams
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandTeams as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandTeams = createIcon(TablerIcon)
