/**
 * Auto-generated icon: IconHospitalCircleFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHospitalCircleFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHospitalCircleFilled = createIcon(TablerIcon)
