/**
 * Auto-generated icon: IconBrandMastercard
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandMastercard as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandMastercard = createIcon(TablerIcon)
