/**
 * Auto-generated icon: IconFileTextAi
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileTextAi as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileTextAi = createIcon(TablerIcon)
