/**
 * Auto-generated icon: IconCircleNumber3Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleNumber3Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleNumber3Filled = createIcon(TablerIcon)
