/**
 * Auto-generated icon: IconDeviceImacPin
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceImacPin as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceImacPin = createIcon(TablerIcon)
