/**
 * Auto-generated icon: IconFileSpark
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileSpark as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileSpark = createIcon(TablerIcon)
