/**
 * Auto-generated icon: IconAdOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAdOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAdOff = createIcon(TablerIcon)
