/**
 * Auto-generated icon: IconEscalatorFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconEscalatorFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconEscalatorFilled = createIcon(TablerIcon)
