/**
 * Auto-generated icon: IconPlayerSkipForward
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPlayerSkipForward as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPlayerSkipForward = createIcon(TablerIcon)
