/**
 * Auto-generated icon: IconAlertOctagonFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAlertOctagonFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAlertOctagonFilled = createIcon(TablerIcon)
