/**
 * Auto-generated icon: IconPhoneRinging
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPhoneRinging as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPhoneRinging = createIcon(TablerIcon)
