/**
 * Auto-generated icon: IconMapBolt
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMapBolt as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMapBolt = createIcon(TablerIcon)
