/**
 * Auto-generated icon: IconSquareRoundedLetterIFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareRoundedLetterIFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareRoundedLetterIFilled = createIcon(TablerIcon)
