/**
 * Auto-generated icon: IconBandageOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBandageOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBandageOff = createIcon(TablerIcon)
