/**
 * Auto-generated icon: IconNumber27Small
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNumber27Small as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNumber27Small = createIcon(TablerIcon)
