/**
 * Auto-generated icon: IconPilcrowLeft
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPilcrowLeft as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPilcrowLeft = createIcon(TablerIcon)
