/**
 * Auto-generated icon: IconShape3
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconShape3 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconShape3 = createIcon(TablerIcon)
