/**
 * Auto-generated icon: IconDashboardOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDashboardOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDashboardOff = createIcon(TablerIcon)
