/**
 * Auto-generated icon: IconMoodSuprised
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMoodSuprised as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMoodSuprised = createIcon(TablerIcon)
