/**
 * Auto-generated icon: IconSquareLetterQ
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareLetterQ as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareLetterQ = createIcon(TablerIcon)
