/**
 * Auto-generated icon: IconHours12
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHours12 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHours12 = createIcon(TablerIcon)
