/**
 * Auto-generated icon: IconForbid2
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconForbid2 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconForbid2 = createIcon(TablerIcon)
