/**
 * Auto-generated icon: IconNumber69Small
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNumber69Small as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNumber69Small = createIcon(TablerIcon)
