/**
 * Auto-generated icon: IconMushroomOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMushroomOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMushroomOff = createIcon(TablerIcon)
