/**
 * Auto-generated icon: IconArrowsMoveHorizontal
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowsMoveHorizontal as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowsMoveHorizontal = createIcon(TablerIcon)
