/**
 * Auto-generated icon: IconGenderHermaphrodite
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconGenderHermaphrodite as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconGenderHermaphrodite = createIcon(TablerIcon)
