/**
 * Auto-generated icon: IconMacroFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMacroFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMacroFilled = createIcon(TablerIcon)
