/**
 * Auto-generated icon: IconChartArrows
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconChartArrows as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconChartArrows = createIcon(TablerIcon)
