/**
 * Auto-generated icon: IconMath
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMath as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMath = createIcon(TablerIcon)
