/**
 * Auto-generated icon: IconDeviceImacCode
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceImacCode as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceImacCode = createIcon(TablerIcon)
