/**
 * Auto-generated icon: IconDevicesSearch
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDevicesSearch as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDevicesSearch = createIcon(TablerIcon)
