/**
 * Auto-generated icon: IconCylinderPlus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCylinderPlus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCylinderPlus = createIcon(TablerIcon)
