/**
 * Auto-generated icon: IconGlassGin
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconGlassGin as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconGlassGin = createIcon(TablerIcon)
