/**
 * Auto-generated icon: IconVariableMinus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconVariableMinus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconVariableMinus = createIcon(TablerIcon)
