/**
 * Auto-generated icon: IconCloudCheck
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCloudCheck as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCloudCheck = createIcon(TablerIcon)
