/**
 * Auto-generated icon: IconGhost2Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconGhost2Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconGhost2Filled = createIcon(TablerIcon)
