/**
 * Auto-generated icon: IconCircleLetterM
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleLetterM as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleLetterM = createIcon(TablerIcon)
