/**
 * Auto-generated icon: IconBrandMastodon
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandMastodon as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandMastodon = createIcon(TablerIcon)
