/**
 * Auto-generated icon: IconMoodPlus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMoodPlus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMoodPlus = createIcon(TablerIcon)
