/**
 * Auto-generated icon: IconApiOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconApiOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconApiOff = createIcon(TablerIcon)
