/**
 * Auto-generated icon: IconMoodX
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMoodX as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMoodX = createIcon(TablerIcon)
