/**
 * Auto-generated icon: IconBrandOpera
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandOpera as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandOpera = createIcon(TablerIcon)
