/**
 * Auto-generated icon: IconScooterElectric
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconScooterElectric as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconScooterElectric = createIcon(TablerIcon)
