/**
 * Auto-generated icon: IconEyeEdit
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconEyeEdit as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconEyeEdit = createIcon(TablerIcon)
