/**
 * Auto-generated icon: IconCrop32Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCrop32Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCrop32Filled = createIcon(TablerIcon)
