/**
 * Auto-generated icon: IconCaretUpFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCaretUpFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCaretUpFilled = createIcon(TablerIcon)
