/**
 * Auto-generated icon: IconPlaystationSquare
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPlaystationSquare as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPlaystationSquare = createIcon(TablerIcon)
