/**
 * Auto-generated icon: IconMapPinCancel
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMapPinCancel as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMapPinCancel = createIcon(TablerIcon)
