/**
 * Auto-generated icon: IconReceiptPound
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconReceiptPound as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconReceiptPound = createIcon(TablerIcon)
