/**
 * Auto-generated icon: IconBrandIntercom
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandIntercom as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandIntercom = createIcon(TablerIcon)
