/**
 * Auto-generated icon: IconRotateRectangle
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRotateRectangle as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRotateRectangle = createIcon(TablerIcon)
