/**
 * Auto-generated icon: IconBorderCornerRounded
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBorderCornerRounded as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBorderCornerRounded = createIcon(TablerIcon)
