/**
 * Auto-generated icon: IconMapPinX
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMapPinX as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMapPinX = createIcon(TablerIcon)
