/**
 * Auto-generated icon: IconMapMinus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMapMinus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMapMinus = createIcon(TablerIcon)
