/**
 * Auto-generated icon: IconBrandCashapp
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandCashapp as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandCashapp = createIcon(TablerIcon)
