/**
 * Auto-generated icon: IconLockSquareRounded
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLockSquareRounded as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLockSquareRounded = createIcon(TablerIcon)
