/**
 * Auto-generated icon: IconBrandYandex
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandYandex as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandYandex = createIcon(TablerIcon)
