/**
 * Auto-generated icon: IconTextSpellcheck
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTextSpellcheck as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTextSpellcheck = createIcon(TablerIcon)
