/**
 * Auto-generated icon: IconBasketOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBasketOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBasketOff = createIcon(TablerIcon)
