/**
 * Auto-generated icon: IconDevicesCheck
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDevicesCheck as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDevicesCheck = createIcon(TablerIcon)
