/**
 * Auto-generated icon: IconClothesRack
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconClothesRack as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconClothesRack = createIcon(TablerIcon)
