/**
 * Auto-generated icon: IconCaretUpDown
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCaretUpDown as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCaretUpDown = createIcon(TablerIcon)
