/**
 * Auto-generated icon: IconBleachNoChlorine
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBleachNoChlorine as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBleachNoChlorine = createIcon(TablerIcon)
