/**
 * Auto-generated icon: IconCopyrightFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCopyrightFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCopyrightFilled = createIcon(TablerIcon)
