/**
 * Auto-generated icon: IconNotesOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNotesOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNotesOff = createIcon(TablerIcon)
