/**
 * Auto-generated icon: IconCheckbox
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCheckbox as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCheckbox = createIcon(TablerIcon)
