/**
 * Auto-generated icon: IconPictureInPictureOn
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPictureInPictureOn as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPictureInPictureOn = createIcon(TablerIcon)
