/**
 * Auto-generated icon: IconAssemblyFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAssemblyFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAssemblyFilled = createIcon(TablerIcon)
