/**
 * Auto-generated icon: IconScreenShareOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconScreenShareOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconScreenShareOff = createIcon(TablerIcon)
