/**
 * Auto-generated icon: IconWritingSign
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconWritingSign as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconWritingSign = createIcon(TablerIcon)
