/**
 * Auto-generated icon: IconEyeCog
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconEyeCog as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconEyeCog = createIcon(TablerIcon)
