/**
 * Auto-generated icon: IconInputAi
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconInputAi as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconInputAi = createIcon(TablerIcon)
