/**
 * Auto-generated icon: IconCalendarRepeat
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCalendarRepeat as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCalendarRepeat = createIcon(TablerIcon)
