/**
 * Auto-generated icon: IconArrowBarDown
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowBarDown as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowBarDown = createIcon(TablerIcon)
