/**
 * Auto-generated icon: IconLayoutBottombarFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLayoutBottombarFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLayoutBottombarFilled = createIcon(TablerIcon)
