/**
 * Auto-generated icon: IconTemperatureOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTemperatureOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTemperatureOff = createIcon(TablerIcon)
