/**
 * Auto-generated icon: IconPentagon
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPentagon as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPentagon = createIcon(TablerIcon)
