/**
 * Auto-generated icon: IconHeadsetOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHeadsetOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHeadsetOff = createIcon(TablerIcon)
