/**
 * Auto-generated icon: IconPointerCode
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPointerCode as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPointerCode = createIcon(TablerIcon)
