/**
 * Auto-generated icon: IconTableRow
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTableRow as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTableRow = createIcon(TablerIcon)
