/**
 * Auto-generated icon: IconArrowRotaryRight
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowRotaryRight as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowRotaryRight = createIcon(TablerIcon)
