/**
 * Auto-generated icon: IconBrandPnpm
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandPnpm as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandPnpm = createIcon(TablerIcon)
