/**
 * Auto-generated icon: IconDeviceIpadHorizontalDown
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceIpadHorizontalDown as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceIpadHorizontalDown = createIcon(TablerIcon)
