/**
 * Auto-generated icon: IconDeviceIpadUp
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceIpadUp as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceIpadUp = createIcon(TablerIcon)
