/**
 * Auto-generated icon: IconVideoPlus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconVideoPlus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconVideoPlus = createIcon(TablerIcon)
