/**
 * Auto-generated icon: IconHandRock
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHandRock as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHandRock = createIcon(TablerIcon)
