/**
 * Auto-generated icon: IconBadgeWcFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBadgeWcFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBadgeWcFilled = createIcon(TablerIcon)
