/**
 * Auto-generated icon: IconHeadphones
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHeadphones as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHeadphones = createIcon(TablerIcon)
