/**
 * Auto-generated icon: IconLayoutSidebarRightInactive
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLayoutSidebarRightInactive as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLayoutSidebarRightInactive = createIcon(TablerIcon)
