/**
 * Auto-generated icon: IconGavel
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconGavel as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconGavel = createIcon(TablerIcon)
