/**
 * Auto-generated icon: IconClockHour11Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconClockHour11Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconClockHour11Filled = createIcon(TablerIcon)
