/**
 * Auto-generated icon: IconHomeCancel
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHomeCancel as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHomeCancel = createIcon(TablerIcon)
