/**
 * Auto-generated icon: IconCalendarQuestion
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCalendarQuestion as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCalendarQuestion = createIcon(TablerIcon)
