/**
 * Auto-generated icon: IconShare
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconShare as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconShare = createIcon(TablerIcon)
