/**
 * Auto-generated icon: IconMessageSearch
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMessageSearch as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMessageSearch = createIcon(TablerIcon)
