/**
 * Auto-generated icon: IconSortDescendingSmallBig
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSortDescendingSmallBig as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSortDescendingSmallBig = createIcon(TablerIcon)
