/**
 * Auto-generated icon: IconBoxAlignBottomFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBoxAlignBottomFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBoxAlignBottomFilled = createIcon(TablerIcon)
