/**
 * Auto-generated icon: IconDialpadFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDialpadFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDialpadFilled = createIcon(TablerIcon)
