/**
 * Auto-generated icon: IconChartBubble
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconChartBubble as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconChartBubble = createIcon(TablerIcon)
