/**
 * Auto-generated icon: IconBrandElectronicArts
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandElectronicArts as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandElectronicArts = createIcon(TablerIcon)
