/**
 * Auto-generated icon: IconTemplateFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTemplateFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTemplateFilled = createIcon(TablerIcon)
