/**
 * Auto-generated icon: IconSquareChevronsDown
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareChevronsDown as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareChevronsDown = createIcon(TablerIcon)
