/**
 * Auto-generated icon: IconMoodSearch
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMoodSearch as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMoodSearch = createIcon(TablerIcon)
