/**
 * Auto-generated icon: IconPhotoSensor3
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPhotoSensor3 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPhotoSensor3 = createIcon(TablerIcon)
