/**
 * Auto-generated icon: IconTriangle
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTriangle as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTriangle = createIcon(TablerIcon)
