/**
 * Auto-generated icon: IconRouteSquare
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRouteSquare as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRouteSquare = createIcon(TablerIcon)
