/**
 * Auto-generated icon: IconBrandGoogleHome
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandGoogleHome as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandGoogleHome = createIcon(TablerIcon)
