/**
 * Auto-generated icon: IconPhoneCheck
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPhoneCheck as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPhoneCheck = createIcon(TablerIcon)
