/**
 * Auto-generated icon: IconAlertCircle
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAlertCircle as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAlertCircle = createIcon(TablerIcon)
