/**
 * Auto-generated icon: IconSwipeRightFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSwipeRightFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSwipeRightFilled = createIcon(TablerIcon)
