/**
 * Auto-generated icon: IconSquareCheck
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareCheck as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareCheck = createIcon(TablerIcon)
