/**
 * Auto-generated icon: IconBellXFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBellXFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBellXFilled = createIcon(TablerIcon)
