/**
 * Auto-generated icon: IconBellStar
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBellStar as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBellStar = createIcon(TablerIcon)
