/**
 * Auto-generated icon: IconDevicesX
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDevicesX as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDevicesX = createIcon(TablerIcon)
