/**
 * Auto-generated icon: IconMoodUp
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMoodUp as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMoodUp = createIcon(TablerIcon)
