/**
 * Auto-generated icon: IconHexagonNumber1Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHexagonNumber1Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHexagonNumber1Filled = createIcon(TablerIcon)
