/**
 * Auto-generated icon: IconGridScan
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconGridScan as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconGridScan = createIcon(TablerIcon)
