/**
 * Auto-generated icon: IconDatabaseExport
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDatabaseExport as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDatabaseExport = createIcon(TablerIcon)
