/**
 * Auto-generated icon: IconRegistered
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRegistered as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRegistered = createIcon(TablerIcon)
