/**
 * Auto-generated icon: IconToolsKitchen2
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconToolsKitchen2 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconToolsKitchen2 = createIcon(TablerIcon)
