/**
 * Auto-generated icon: IconLabelOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLabelOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLabelOff = createIcon(TablerIcon)
