/**
 * Auto-generated icon: IconArmchair2Off
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArmchair2Off as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArmchair2Off = createIcon(TablerIcon)
