/**
 * Auto-generated icon: IconBellFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBellFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBellFilled = createIcon(TablerIcon)
