/**
 * Auto-generated icon: IconLetterF
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLetterF as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLetterF = createIcon(TablerIcon)
