/**
 * Auto-generated icon: IconBrandGatsby
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandGatsby as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandGatsby = createIcon(TablerIcon)
