/**
 * Auto-generated icon: IconDisabled2
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDisabled2 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDisabled2 = createIcon(TablerIcon)
