/**
 * Auto-generated icon: IconDeviceMobilePause
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceMobilePause as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceMobilePause = createIcon(TablerIcon)
