/**
 * Auto-generated icon: IconOval
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconOval as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconOval = createIcon(TablerIcon)
