/**
 * Auto-generated icon: IconPhotoSpark
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPhotoSpark as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPhotoSpark = createIcon(TablerIcon)
