/**
 * Auto-generated icon: IconSalt
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSalt as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSalt = createIcon(TablerIcon)
