/**
 * Auto-generated icon: IconRollerSkating
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRollerSkating as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRollerSkating = createIcon(TablerIcon)
