/**
 * Auto-generated icon: IconMapSearch
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMapSearch as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMapSearch = createIcon(TablerIcon)
