/**
 * Auto-generated icon: IconClock
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconClock as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconClock = createIcon(TablerIcon)
