/**
 * Auto-generated icon: IconArrowBigLeftLine
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowBigLeftLine as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowBigLeftLine = createIcon(TablerIcon)
