/**
 * Auto-generated icon: IconFocus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFocus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFocus = createIcon(TablerIcon)
