/**
 * Auto-generated icon: IconFileExport
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileExport as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileExport = createIcon(TablerIcon)
