/**
 * Auto-generated icon: IconBasketBolt
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBasketBolt as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBasketBolt = createIcon(TablerIcon)
