/**
 * Auto-generated icon: IconArrowsSort
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowsSort as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowsSort = createIcon(TablerIcon)
