/**
 * Auto-generated icon: IconBrandNodejs
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandNodejs as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandNodejs = createIcon(TablerIcon)
