/**
 * Auto-generated icon: IconLocationCog
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLocationCog as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLocationCog = createIcon(TablerIcon)
