/**
 * Auto-generated icon: IconPhoto
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPhoto as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPhoto = createIcon(TablerIcon)
