/**
 * Auto-generated icon: IconRosetteFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRosetteFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRosetteFilled = createIcon(TablerIcon)
