/**
 * Auto-generated icon: IconArrowRotaryLastLeft
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowRotaryLastLeft as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowRotaryLastLeft = createIcon(TablerIcon)
