/**
 * Auto-generated icon: IconHexagonPlusFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHexagonPlusFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHexagonPlusFilled = createIcon(TablerIcon)
