/**
 * Auto-generated icon: IconCircle2
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircle2 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircle2 = createIcon(TablerIcon)
