/**
 * Auto-generated icon: IconSeparatorVertical
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSeparatorVertical as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSeparatorVertical = createIcon(TablerIcon)
