/**
 * Auto-generated icon: IconLockCheck
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLockCheck as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLockCheck = createIcon(TablerIcon)
