/**
 * Auto-generated icon: IconLassoPolygonFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLassoPolygonFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLassoPolygonFilled = createIcon(TablerIcon)
