/**
 * Auto-generated icon: IconPlayCardQ
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPlayCardQ as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPlayCardQ = createIcon(TablerIcon)
