/**
 * Auto-generated icon: IconWorldCheck
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconWorldCheck as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconWorldCheck = createIcon(TablerIcon)
