/**
 * Auto-generated icon: IconStepInto
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconStepInto as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconStepInto = createIcon(TablerIcon)
