/**
 * Auto-generated icon: IconMoodBitcoin
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMoodBitcoin as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMoodBitcoin = createIcon(TablerIcon)
