/**
 * Auto-generated icon: IconLayersSelectedBottom
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLayersSelectedBottom as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLayersSelectedBottom = createIcon(TablerIcon)
