/**
 * Auto-generated icon: IconBoxModel2
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBoxModel2 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBoxModel2 = createIcon(TablerIcon)
