/**
 * Auto-generated icon: IconPhotoVideo
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPhotoVideo as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPhotoVideo = createIcon(TablerIcon)
