/**
 * Auto-generated icon: IconCircleCaretDownFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleCaretDownFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleCaretDownFilled = createIcon(TablerIcon)
