/**
 * Auto-generated icon: IconCurrencyDollarAustralian
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCurrencyDollarAustralian as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCurrencyDollarAustralian = createIcon(TablerIcon)
