/**
 * Auto-generated icon: IconScanEye
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconScanEye as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconScanEye = createIcon(TablerIcon)
