/**
 * Auto-generated icon: IconArrowWaveRightDown
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowWaveRightDown as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowWaveRightDown = createIcon(TablerIcon)
