/**
 * Auto-generated icon: IconTaxEuro
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTaxEuro as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTaxEuro = createIcon(TablerIcon)
