/**
 * Auto-generated icon: IconWorldStar
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconWorldStar as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconWorldStar = createIcon(TablerIcon)
