/**
 * Auto-generated icon: IconLegoOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLegoOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLegoOff = createIcon(TablerIcon)
