/**
 * Auto-generated icon: IconCubeSend
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCubeSend as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCubeSend = createIcon(TablerIcon)
