/**
 * Auto-generated icon: IconRocketOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRocketOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRocketOff = createIcon(TablerIcon)
