/**
 * Auto-generated icon: IconArrowLeftRhombusFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowLeftRhombusFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowLeftRhombusFilled = createIcon(TablerIcon)
