/**
 * Auto-generated icon: IconFileTypeBmp
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileTypeBmp as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileTypeBmp = createIcon(TablerIcon)
