/**
 * Auto-generated icon: IconSunrise
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSunrise as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSunrise = createIcon(TablerIcon)
