/**
 * Auto-generated icon: IconCircleLetterF
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleLetterF as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleLetterF = createIcon(TablerIcon)
