/**
 * Auto-generated icon: IconToiletPaper
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconToiletPaper as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconToiletPaper = createIcon(TablerIcon)
