/**
 * Auto-generated icon: IconStackFront
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconStackFront as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconStackFront = createIcon(TablerIcon)
