/**
 * Auto-generated icon: IconMinimize
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMinimize as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMinimize = createIcon(TablerIcon)
