/**
 * Auto-generated icon: IconOctagonMinusFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconOctagonMinusFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconOctagonMinusFilled = createIcon(TablerIcon)
