/**
 * Auto-generated icon: IconFlagStar
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFlagStar as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFlagStar = createIcon(TablerIcon)
