/**
 * Auto-generated icon: IconCoins
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCoins as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCoins = createIcon(TablerIcon)
