/**
 * Auto-generated icon: IconDeviceWatchOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceWatchOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceWatchOff = createIcon(TablerIcon)
