/**
 * Auto-generated icon: IconSquareChevronsRightFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareChevronsRightFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareChevronsRightFilled = createIcon(TablerIcon)
