/**
 * Auto-generated icon: IconSquareRoundedNumber3Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareRoundedNumber3Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareRoundedNumber3Filled = createIcon(TablerIcon)
