/**
 * Auto-generated icon: IconChartPie4
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconChartPie4 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconChartPie4 = createIcon(TablerIcon)
