/**
 * Auto-generated icon: IconCurrencyRipple
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCurrencyRipple as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCurrencyRipple = createIcon(TablerIcon)
