/**
 * Auto-generated icon: IconMessageDown
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMessageDown as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMessageDown = createIcon(TablerIcon)
