/**
 * Auto-generated icon: IconFilter2Bolt
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFilter2Bolt as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFilter2Bolt = createIcon(TablerIcon)
