/**
 * Auto-generated icon: IconEyePin
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconEyePin as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconEyePin = createIcon(TablerIcon)
