/**
 * Auto-generated icon: IconDeviceTabletBolt
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceTabletBolt as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceTabletBolt = createIcon(TablerIcon)
