/**
 * Auto-generated icon: IconCube
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCube as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCube = createIcon(TablerIcon)
