/**
 * Auto-generated icon: IconDeviceGamepad3Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceGamepad3Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceGamepad3Filled = createIcon(TablerIcon)
