/**
 * Auto-generated icon: IconCloud
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCloud as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCloud = createIcon(TablerIcon)
