/**
 * Auto-generated icon: IconCircleNumber5Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleNumber5Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleNumber5Filled = createIcon(TablerIcon)
