/**
 * Auto-generated icon: IconDatabaseLeak
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDatabaseLeak as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDatabaseLeak = createIcon(TablerIcon)
