/**
 * Auto-generated icon: IconTimeDuration60
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTimeDuration60 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTimeDuration60 = createIcon(TablerIcon)
