/**
 * Auto-generated icon: IconArrowBadgeUp
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowBadgeUp as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowBadgeUp = createIcon(TablerIcon)
