/**
 * Auto-generated icon: IconMilitaryRank
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMilitaryRank as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMilitaryRank = createIcon(TablerIcon)
