/**
 * Auto-generated icon: IconUserX
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconUserX as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconUserX = createIcon(TablerIcon)
