/**
 * Auto-generated icon: IconBrandSnapchatFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandSnapchatFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandSnapchatFilled = createIcon(TablerIcon)
