/**
 * Auto-generated icon: IconSquareCheckFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareCheckFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareCheckFilled = createIcon(TablerIcon)
