/**
 * Auto-generated icon: IconMathXFloorDivideY
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMathXFloorDivideY as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMathXFloorDivideY = createIcon(TablerIcon)
