/**
 * Auto-generated icon: IconPhotoFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPhotoFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPhotoFilled = createIcon(TablerIcon)
