/**
 * Auto-generated icon: IconSettingsPin
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSettingsPin as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSettingsPin = createIcon(TablerIcon)
