/**
 * Auto-generated icon: IconRectangularPrismOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRectangularPrismOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRectangularPrismOff = createIcon(TablerIcon)
