/**
 * Auto-generated icon: IconFreezeRowColumn
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFreezeRowColumn as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFreezeRowColumn = createIcon(TablerIcon)
