/**
 * Auto-generated icon: IconCapsule
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCapsule as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCapsule = createIcon(TablerIcon)
