/**
 * Auto-generated icon: IconBatterySpark
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBatterySpark as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBatterySpark = createIcon(TablerIcon)
