/**
 * Auto-generated icon: IconTimeDuration45
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTimeDuration45 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTimeDuration45 = createIcon(TablerIcon)
