/**
 * Auto-generated icon: IconTrendingDown3
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTrendingDown3 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTrendingDown3 = createIcon(TablerIcon)
