/**
 * Auto-generated icon: IconBadgeCcFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBadgeCcFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBadgeCcFilled = createIcon(TablerIcon)
