/**
 * Auto-generated icon: IconNumber98Small
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNumber98Small as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNumber98Small = createIcon(TablerIcon)
