/**
 * Auto-generated icon: IconMoodWrrrFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMoodWrrrFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMoodWrrrFilled = createIcon(TablerIcon)
