/**
 * Auto-generated icon: IconChessRook
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconChessRook as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconChessRook = createIcon(TablerIcon)
