/**
 * Auto-generated icon: IconClockHour6
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconClockHour6 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconClockHour6 = createIcon(TablerIcon)
