/**
 * Auto-generated icon: IconBrandFramerMotion
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandFramerMotion as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandFramerMotion = createIcon(TablerIcon)
