/**
 * Auto-generated icon: IconMailOpened
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMailOpened as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMailOpened = createIcon(TablerIcon)
