/**
 * Auto-generated icon: IconCircleLetterC
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleLetterC as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleLetterC = createIcon(TablerIcon)
