/**
 * Auto-generated icon: IconArrowRotaryStraight
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowRotaryStraight as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowRotaryStraight = createIcon(TablerIcon)
