/**
 * Auto-generated icon: IconCircleDottedLetterN
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleDottedLetterN as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleDottedLetterN = createIcon(TablerIcon)
