/**
 * Auto-generated icon: IconBrandHexo
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandHexo as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandHexo = createIcon(TablerIcon)
