/**
 * Auto-generated icon: IconMatchstick
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMatchstick as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMatchstick = createIcon(TablerIcon)
