/**
 * Auto-generated icon: IconMeepleFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMeepleFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMeepleFilled = createIcon(TablerIcon)
