/**
 * Auto-generated icon: IconBatteryEco
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBatteryEco as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBatteryEco = createIcon(TablerIcon)
