/**
 * Auto-generated icon: IconPointerSearch
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPointerSearch as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPointerSearch = createIcon(TablerIcon)
