/**
 * Auto-generated icon: IconWiperWash
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconWiperWash as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconWiperWash = createIcon(TablerIcon)
