/**
 * Auto-generated icon: IconPanoramaVertical
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPanoramaVertical as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPanoramaVertical = createIcon(TablerIcon)
