/**
 * Auto-generated icon: IconBadge2k
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBadge2k as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBadge2k = createIcon(TablerIcon)
