/**
 * Auto-generated icon: IconPresentationOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPresentationOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPresentationOff = createIcon(TablerIcon)
