/**
 * Auto-generated icon: IconSquareRoundedNumber8Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareRoundedNumber8Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareRoundedNumber8Filled = createIcon(TablerIcon)
