/**
 * Auto-generated icon: IconGasStationFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconGasStationFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconGasStationFilled = createIcon(TablerIcon)
