/**
 * Auto-generated icon: IconThumbDownFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconThumbDownFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconThumbDownFilled = createIcon(TablerIcon)
