/**
 * Auto-generated icon: IconSquareRoundedArrowRightFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareRoundedArrowRightFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareRoundedArrowRightFilled = createIcon(TablerIcon)
