/**
 * Auto-generated icon: IconClockHour5
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconClockHour5 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconClockHour5 = createIcon(TablerIcon)
