/**
 * Auto-generated icon: IconFileTypePpt
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileTypePpt as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileTypePpt = createIcon(TablerIcon)
