/**
 * Auto-generated icon: IconShieldUp
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconShieldUp as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconShieldUp = createIcon(TablerIcon)
