/**
 * Auto-generated icon: IconDeviceMobileDollar
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceMobileDollar as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceMobileDollar = createIcon(TablerIcon)
