/**
 * Auto-generated icon: IconSquareRoundedLetterZ
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareRoundedLetterZ as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareRoundedLetterZ = createIcon(TablerIcon)
