/**
 * Auto-generated icon: IconParachuteOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconParachuteOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconParachuteOff = createIcon(TablerIcon)
