/**
 * Auto-generated icon: IconPills
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPills as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPills = createIcon(TablerIcon)
