/**
 * Auto-generated icon: IconSquareRoundedPlus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareRoundedPlus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareRoundedPlus = createIcon(TablerIcon)
