/**
 * Auto-generated icon: IconBoxMultipleFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBoxMultipleFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBoxMultipleFilled = createIcon(TablerIcon)
