/**
 * Auto-generated icon: IconMultiplier05x
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMultiplier05x as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMultiplier05x = createIcon(TablerIcon)
