/**
 * Auto-generated icon: IconBrandNeteaseMusic
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandNeteaseMusic as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandNeteaseMusic = createIcon(TablerIcon)
