/**
 * Auto-generated icon: IconViewportWide
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconViewportWide as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconViewportWide = createIcon(TablerIcon)
