/**
 * Auto-generated icon: IconDeviceImacCancel
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceImacCancel as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceImacCancel = createIcon(TablerIcon)
