/**
 * Auto-generated icon: IconSpiralOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSpiralOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSpiralOff = createIcon(TablerIcon)
