/**
 * Auto-generated icon: IconSortAZ
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSortAZ as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSortAZ = createIcon(TablerIcon)
