/**
 * Auto-generated icon: IconLockDollar
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLockDollar as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLockDollar = createIcon(TablerIcon)
