/**
 * Auto-generated icon: IconShoppingCartHeart
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconShoppingCartHeart as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconShoppingCartHeart = createIcon(TablerIcon)
