/**
 * Auto-generated icon: IconWorldHeart
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconWorldHeart as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconWorldHeart = createIcon(TablerIcon)
