/**
 * Auto-generated icon: IconBrandWaze
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandWaze as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandWaze = createIcon(TablerIcon)
