/**
 * Auto-generated icon: IconFileArrowRight
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileArrowRight as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileArrowRight = createIcon(TablerIcon)
