/**
 * Auto-generated icon: IconHomeMove
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHomeMove as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHomeMove = createIcon(TablerIcon)
