/**
 * Auto-generated icon: IconGitPullRequestClosed
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconGitPullRequestClosed as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconGitPullRequestClosed = createIcon(TablerIcon)
