/**
 * Auto-generated icon: IconDeviceImacFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceImacFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceImacFilled = createIcon(TablerIcon)
