/**
 * Auto-generated icon: IconSwipeRight
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSwipeRight as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSwipeRight = createIcon(TablerIcon)
