/**
 * Auto-generated icon: IconLayoutDistributeHorizontalFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLayoutDistributeHorizontalFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLayoutDistributeHorizontalFilled = createIcon(TablerIcon)
