/**
 * Auto-generated icon: IconDice3
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDice3 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDice3 = createIcon(TablerIcon)
