/**
 * Auto-generated icon: IconWalletOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconWalletOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconWalletOff = createIcon(TablerIcon)
