/**
 * Auto-generated icon: IconChartFunnelFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconChartFunnelFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconChartFunnelFilled = createIcon(TablerIcon)
