/**
 * Auto-generated icon: IconFlagSearch
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFlagSearch as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFlagSearch = createIcon(TablerIcon)
