/**
 * Auto-generated icon: IconEraser
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconEraser as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconEraser = createIcon(TablerIcon)
