/**
 * Auto-generated icon: IconCandy
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCandy as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCandy = createIcon(TablerIcon)
