/**
 * Auto-generated icon: IconPlayCard9Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPlayCard9Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPlayCard9Filled = createIcon(TablerIcon)
