/**
 * Auto-generated icon: IconPentagonNumber7
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPentagonNumber7 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPentagonNumber7 = createIcon(TablerIcon)
