/**
 * Auto-generated icon: IconCaravanFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCaravanFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCaravanFilled = createIcon(TablerIcon)
