/**
 * Auto-generated icon: IconTransitionBottomFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTransitionBottomFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTransitionBottomFilled = createIcon(TablerIcon)
