/**
 * Auto-generated icon: IconGridPattern
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconGridPattern as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconGridPattern = createIcon(TablerIcon)
