/**
 * Auto-generated icon: IconTransferIn
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTransferIn as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTransferIn = createIcon(TablerIcon)
