/**
 * Auto-generated icon: IconHomeDollar
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHomeDollar as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHomeDollar = createIcon(TablerIcon)
