/**
 * Auto-generated icon: IconAlertCircleFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAlertCircleFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAlertCircleFilled = createIcon(TablerIcon)
