/**
 * Auto-generated icon: IconBallpen
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBallpen as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBallpen = createIcon(TablerIcon)
