/**
 * Auto-generated icon: IconHourglassFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHourglassFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHourglassFilled = createIcon(TablerIcon)
