/**
 * Auto-generated icon: IconArrowDownLeft
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowDownLeft as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowDownLeft = createIcon(TablerIcon)
