/**
 * Auto-generated icon: IconHeartbeat
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHeartbeat as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHeartbeat = createIcon(TablerIcon)
