/**
 * Auto-generated icon: IconStethoscopeOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconStethoscopeOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconStethoscopeOff = createIcon(TablerIcon)
