/**
 * Auto-generated icon: IconFileSignal
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileSignal as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileSignal = createIcon(TablerIcon)
