/**
 * Auto-generated icon: IconDeviceMobileQuestion
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceMobileQuestion as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceMobileQuestion = createIcon(TablerIcon)
