/**
 * Auto-generated icon: IconUhd
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconUhd as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconUhd = createIcon(TablerIcon)
