/**
 * Auto-generated icon: IconSitemapOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSitemapOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSitemapOff = createIcon(TablerIcon)
