/**
 * Auto-generated icon: IconBowlSpoonFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBowlSpoonFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBowlSpoonFilled = createIcon(TablerIcon)
