/**
 * Auto-generated icon: IconSquareNumber0Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareNumber0Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareNumber0Filled = createIcon(TablerIcon)
