/**
 * Auto-generated icon: IconArrowUpSquareFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowUpSquareFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowUpSquareFilled = createIcon(TablerIcon)
