/**
 * Auto-generated icon: IconMoodSmileFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMoodSmileFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMoodSmileFilled = createIcon(TablerIcon)
