/**
 * Auto-generated icon: IconPencil
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPencil as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPencil = createIcon(TablerIcon)
