/**
 * Auto-generated icon: IconKering
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconKering as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconKering = createIcon(TablerIcon)
