/**
 * Auto-generated icon: IconNavigationSearch
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNavigationSearch as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNavigationSearch = createIcon(TablerIcon)
