/**
 * Auto-generated icon: IconFreeRights
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFreeRights as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFreeRights = createIcon(TablerIcon)
