/**
 * Auto-generated icon: IconGardenCartFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconGardenCartFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconGardenCartFilled = createIcon(TablerIcon)
