/**
 * Auto-generated icon: IconCreativeCommonsNd
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCreativeCommonsNd as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCreativeCommonsNd = createIcon(TablerIcon)
