/**
 * Auto-generated icon: IconStack2
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconStack2 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconStack2 = createIcon(TablerIcon)
