/**
 * Auto-generated icon: IconDeviceWatchDollar
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceWatchDollar as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceWatchDollar = createIcon(TablerIcon)
