/**
 * Auto-generated icon: IconToggleRight
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconToggleRight as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconToggleRight = createIcon(TablerIcon)
