/**
 * Auto-generated icon: IconFileInvoice
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileInvoice as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileInvoice = createIcon(TablerIcon)
