/**
 * Auto-generated icon: IconOverline
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconOverline as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconOverline = createIcon(TablerIcon)
