/**
 * Auto-generated icon: IconHexagonMinusFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHexagonMinusFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHexagonMinusFilled = createIcon(TablerIcon)
