/**
 * Auto-generated icon: IconRating18Plus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRating18Plus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRating18Plus = createIcon(TablerIcon)
