/**
 * Auto-generated icon: IconCircleChevronsLeftFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleChevronsLeftFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleChevronsLeftFilled = createIcon(TablerIcon)
