/**
 * Auto-generated icon: IconLetterASmall
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLetterASmall as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLetterASmall = createIcon(TablerIcon)
