/**
 * Auto-generated icon: IconLocationCancel
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLocationCancel as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLocationCancel = createIcon(TablerIcon)
