/**
 * Auto-generated icon: IconArrowsDoubleNeSw
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowsDoubleNeSw as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowsDoubleNeSw = createIcon(TablerIcon)
