/**
 * Auto-generated icon: IconGrill
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconGrill as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconGrill = createIcon(TablerIcon)
