/**
 * Auto-generated icon: IconGenderFemale
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconGenderFemale as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconGenderFemale = createIcon(TablerIcon)
