/**
 * Auto-generated icon: IconArrowRightFromArc
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowRightFromArc as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowRightFromArc = createIcon(TablerIcon)
