/**
 * Auto-generated icon: IconStack3
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconStack3 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconStack3 = createIcon(TablerIcon)
