/**
 * Auto-generated icon: IconBrandEnvato
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandEnvato as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandEnvato = createIcon(TablerIcon)
