/**
 * Auto-generated icon: IconNumber21Small
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNumber21Small as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNumber21Small = createIcon(TablerIcon)
