/**
 * Auto-generated icon: IconRelationOneToMany
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRelationOneToMany as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRelationOneToMany = createIcon(TablerIcon)
