/**
 * Auto-generated icon: IconCoinOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCoinOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCoinOff = createIcon(TablerIcon)
