/**
 * Auto-generated icon: IconBrandDaysCounter
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandDaysCounter as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandDaysCounter = createIcon(TablerIcon)
