/**
 * Auto-generated icon: IconBellRinging2
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBellRinging2 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBellRinging2 = createIcon(TablerIcon)
