/**
 * Auto-generated icon: IconMapDown
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMapDown as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMapDown = createIcon(TablerIcon)
