/**
 * Auto-generated icon: IconProgress
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconProgress as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconProgress = createIcon(TablerIcon)
