/**
 * Auto-generated icon: IconPlayCard7Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPlayCard7Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPlayCard7Filled = createIcon(TablerIcon)
