/**
 * Auto-generated icon: IconRecycleOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRecycleOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRecycleOff = createIcon(TablerIcon)
