/**
 * Auto-generated icon: IconBatteryExclamation
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBatteryExclamation as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBatteryExclamation = createIcon(TablerIcon)
