/**
 * Auto-generated icon: IconCubeSpark
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCubeSpark as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCubeSpark = createIcon(TablerIcon)
