/**
 * Auto-generated icon: IconCurrencyPound
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCurrencyPound as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCurrencyPound = createIcon(TablerIcon)
