/**
 * Auto-generated icon: IconPencilDown
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPencilDown as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPencilDown = createIcon(TablerIcon)
