/**
 * Auto-generated icon: IconBookmarksFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBookmarksFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBookmarksFilled = createIcon(TablerIcon)
