/**
 * Auto-generated icon: IconCameraCancel
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCameraCancel as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCameraCancel = createIcon(TablerIcon)
