/**
 * Auto-generated icon: IconStack2Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconStack2Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconStack2Filled = createIcon(TablerIcon)
