/**
 * Auto-generated icon: IconHexagonNumber0
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHexagonNumber0 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHexagonNumber0 = createIcon(TablerIcon)
