/**
 * Auto-generated icon: IconChevronDownRight
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconChevronDownRight as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconChevronDownRight = createIcon(TablerIcon)
