/**
 * Auto-generated icon: IconRewindBackward40
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRewindBackward40 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRewindBackward40 = createIcon(TablerIcon)
