/**
 * Auto-generated icon: IconAlignBoxCenterMiddle
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAlignBoxCenterMiddle as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAlignBoxCenterMiddle = createIcon(TablerIcon)
