/**
 * Auto-generated icon: IconWritingOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconWritingOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconWritingOff = createIcon(TablerIcon)
