/**
 * Auto-generated icon: IconWorldDollar
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconWorldDollar as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconWorldDollar = createIcon(TablerIcon)
