/**
 * Auto-generated icon: IconZodiacTaurus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconZodiacTaurus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconZodiacTaurus = createIcon(TablerIcon)
