/**
 * Auto-generated icon: IconLockPlus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLockPlus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLockPlus = createIcon(TablerIcon)
