/**
 * Auto-generated icon: IconHorse
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHorse as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHorse = createIcon(TablerIcon)
