/**
 * Auto-generated icon: IconPlantOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPlantOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPlantOff = createIcon(TablerIcon)
