/**
 * Auto-generated icon: IconDatabaseDollar
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDatabaseDollar as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDatabaseDollar = createIcon(TablerIcon)
