/**
 * Auto-generated icon: IconArrowBigUpLinesFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowBigUpLinesFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowBigUpLinesFilled = createIcon(TablerIcon)
