/**
 * Auto-generated icon: IconExplicit
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconExplicit as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconExplicit = createIcon(TablerIcon)
