/**
 * Auto-generated icon: IconInfoSmall
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconInfoSmall as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconInfoSmall = createIcon(TablerIcon)
