/**
 * Auto-generated icon: IconMicrowaveFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMicrowaveFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMicrowaveFilled = createIcon(TablerIcon)
