/**
 * Auto-generated icon: IconSolarElectricity
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSolarElectricity as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSolarElectricity = createIcon(TablerIcon)
