/**
 * Auto-generated icon: IconHelpSquareFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHelpSquareFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHelpSquareFilled = createIcon(TablerIcon)
