/**
 * Auto-generated icon: IconSortDescendingLetters
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSortDescendingLetters as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSortDescendingLetters = createIcon(TablerIcon)
