/**
 * Auto-generated icon: IconSquareRoundedNumber5
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareRoundedNumber5 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareRoundedNumber5 = createIcon(TablerIcon)
