/**
 * Auto-generated icon: IconWhirl
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconWhirl as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconWhirl = createIcon(TablerIcon)
