/**
 * Auto-generated icon: IconArrowDownRightCircle
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowDownRightCircle as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowDownRightCircle = createIcon(TablerIcon)
