/**
 * Auto-generated icon: IconPray
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPray as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPray = createIcon(TablerIcon)
