/**
 * Auto-generated icon: IconVectorTriangle
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconVectorTriangle as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconVectorTriangle = createIcon(TablerIcon)
