/**
 * Auto-generated icon: IconHeartStar
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHeartStar as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHeartStar = createIcon(TablerIcon)
