/**
 * Auto-generated icon: IconSettingsCog
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSettingsCog as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSettingsCog = createIcon(TablerIcon)
