/**
 * Auto-generated icon: IconHorseToy
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHorseToy as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHorseToy = createIcon(TablerIcon)
