/**
 * Auto-generated icon: IconCurrencyPaanga
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCurrencyPaanga as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCurrencyPaanga = createIcon(TablerIcon)
