/**
 * Auto-generated icon: IconTruckOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTruckOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTruckOff = createIcon(TablerIcon)
