/**
 * Auto-generated icon: IconRouteAltLeft
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRouteAltLeft as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRouteAltLeft = createIcon(TablerIcon)
