/**
 * Auto-generated icon: IconTriangleOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTriangleOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTriangleOff = createIcon(TablerIcon)
