/**
 * Auto-generated icon: IconCurrencyZloty
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCurrencyZloty as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCurrencyZloty = createIcon(TablerIcon)
