/**
 * Auto-generated icon: IconSunLow
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSunLow as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSunLow = createIcon(TablerIcon)
