/**
 * Auto-generated icon: IconColumns1Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconColumns1Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconColumns1Filled = createIcon(TablerIcon)
