/**
 * Auto-generated icon: IconTrianglePlus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTrianglePlus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTrianglePlus = createIcon(TablerIcon)
