/**
 * Auto-generated icon: IconSettingsSearch
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSettingsSearch as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSettingsSearch = createIcon(TablerIcon)
