/**
 * Auto-generated icon: IconMilk
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMilk as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMilk = createIcon(TablerIcon)
