/**
 * Auto-generated icon: IconBounceLeftFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBounceLeftFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBounceLeftFilled = createIcon(TablerIcon)
