/**
 * Auto-generated icon: IconSquareRoundedLetterP
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareRoundedLetterP as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareRoundedLetterP = createIcon(TablerIcon)
