/**
 * Auto-generated icon: IconInnerShadowTop
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconInnerShadowTop as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconInnerShadowTop = createIcon(TablerIcon)
