/**
 * Auto-generated icon: IconFilter2Plus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFilter2Plus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFilter2Plus = createIcon(TablerIcon)
