/**
 * Auto-generated icon: IconCurrencyDollarGuyanese
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCurrencyDollarGuyanese as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCurrencyDollarGuyanese = createIcon(TablerIcon)
