/**
 * Auto-generated icon: IconHourglassLow
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHourglassLow as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHourglassLow = createIcon(TablerIcon)
