/**
 * Auto-generated icon: IconLane
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLane as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLane = createIcon(TablerIcon)
