/**
 * Auto-generated icon: IconFilter2Cancel
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFilter2Cancel as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFilter2Cancel = createIcon(TablerIcon)
