/**
 * Auto-generated icon: IconMapPlus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMapPlus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMapPlus = createIcon(TablerIcon)
