/**
 * Auto-generated icon: IconSquareLetterK
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareLetterK as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareLetterK = createIcon(TablerIcon)
