/**
 * Auto-generated icon: IconCircleCaretDown
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleCaretDown as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleCaretDown = createIcon(TablerIcon)
