/**
 * Auto-generated icon: IconPhoneDone
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPhoneDone as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPhoneDone = createIcon(TablerIcon)
