/**
 * Auto-generated icon: IconAspectRatio
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAspectRatio as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAspectRatio = createIcon(TablerIcon)
