/**
 * Auto-generated icon: IconDeviceDesktopX
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceDesktopX as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceDesktopX = createIcon(TablerIcon)
