/**
 * Auto-generated icon: IconLayoutAlignRightFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLayoutAlignRightFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLayoutAlignRightFilled = createIcon(TablerIcon)
