/**
 * Auto-generated icon: IconNoDerivatives
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNoDerivatives as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNoDerivatives = createIcon(TablerIcon)
