/**
 * Auto-generated icon: IconPrism
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPrism as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPrism = createIcon(TablerIcon)
