/**
 * Auto-generated icon: IconPlayFootball
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPlayFootball as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPlayFootball = createIcon(TablerIcon)
