/**
 * Auto-generated icon: IconHelpCircle
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHelpCircle as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHelpCircle = createIcon(TablerIcon)
