/**
 * Auto-generated icon: IconArrowsExchange2
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowsExchange2 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowsExchange2 = createIcon(TablerIcon)
