/**
 * Auto-generated icon: IconFileTypeXls
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileTypeXls as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileTypeXls = createIcon(TablerIcon)
