/**
 * Auto-generated icon: IconBombFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBombFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBombFilled = createIcon(TablerIcon)
