/**
 * Auto-generated icon: IconDesk
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDesk as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDesk = createIcon(TablerIcon)
