/**
 * Auto-generated icon: IconDeviceSim2
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceSim2 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceSim2 = createIcon(TablerIcon)
