/**
 * Auto-generated icon: IconFeatherOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFeatherOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFeatherOff = createIcon(TablerIcon)
