/**
 * Auto-generated icon: IconMoodConfuzedFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMoodConfuzedFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMoodConfuzedFilled = createIcon(TablerIcon)
