/**
 * Auto-generated icon: IconActivity
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconActivity as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconActivity = createIcon(TablerIcon)
