/**
 * Auto-generated icon: IconHexagonLetterS
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHexagonLetterS as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHexagonLetterS = createIcon(TablerIcon)
