/**
 * Auto-generated icon: IconFocusAuto
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFocusAuto as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFocusAuto = createIcon(TablerIcon)
