/**
 * Auto-generated icon: IconLoader2
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLoader2 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLoader2 = createIcon(TablerIcon)
