/**
 * Auto-generated icon: IconHazeMoon
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHazeMoon as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHazeMoon = createIcon(TablerIcon)
