/**
 * Auto-generated icon: IconUmbrella
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconUmbrella as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconUmbrella = createIcon(TablerIcon)
