/**
 * Auto-generated icon: IconTallymark4
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTallymark4 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTallymark4 = createIcon(TablerIcon)
