/**
 * Auto-generated icon: IconNumbers
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNumbers as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNumbers = createIcon(TablerIcon)
