/**
 * Auto-generated icon: IconUsersGroup
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconUsersGroup as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconUsersGroup = createIcon(TablerIcon)
