/**
 * Auto-generated icon: IconFileInfoFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileInfoFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileInfoFilled = createIcon(TablerIcon)
