/**
 * Auto-generated icon: IconCircleNumber5
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleNumber5 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleNumber5 = createIcon(TablerIcon)
