/**
 * Auto-generated icon: IconPercentage0
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPercentage0 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPercentage0 = createIcon(TablerIcon)
