/**
 * Auto-generated icon: IconLockShare
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLockShare as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLockShare = createIcon(TablerIcon)
