/**
 * Auto-generated icon: IconArrowMoveRightFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowMoveRightFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowMoveRightFilled = createIcon(TablerIcon)
