/**
 * Auto-generated icon: IconAlignRight
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAlignRight as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAlignRight = createIcon(TablerIcon)
