/**
 * Auto-generated icon: IconCoinTakaFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCoinTakaFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCoinTakaFilled = createIcon(TablerIcon)
