/**
 * Auto-generated icon: IconClock24
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconClock24 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconClock24 = createIcon(TablerIcon)
