/**
 * Auto-generated icon: IconBoxMultiple7
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBoxMultiple7 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBoxMultiple7 = createIcon(TablerIcon)
