/**
 * Auto-generated icon: IconBeer
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBeer as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBeer = createIcon(TablerIcon)
