/**
 * Auto-generated icon: IconAlignLeft2
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAlignLeft2 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAlignLeft2 = createIcon(TablerIcon)
