/**
 * Auto-generated icon: IconSteeringWheelOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSteeringWheelOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSteeringWheelOff = createIcon(TablerIcon)
