/**
 * Auto-generated icon: IconBrandCitymapper
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandCitymapper as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandCitymapper = createIcon(TablerIcon)
