/**
 * Auto-generated icon: IconBinocularsFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBinocularsFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBinocularsFilled = createIcon(TablerIcon)
