/**
 * Auto-generated icon: IconCurrencyDollarBrunei
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCurrencyDollarBrunei as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCurrencyDollarBrunei = createIcon(TablerIcon)
