/**
 * Auto-generated icon: IconDroneOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDroneOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDroneOff = createIcon(TablerIcon)
