/**
 * Auto-generated icon: IconFileStack
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileStack as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileStack = createIcon(TablerIcon)
