/**
 * Auto-generated icon: IconPencilPin
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPencilPin as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPencilPin = createIcon(TablerIcon)
