/**
 * Auto-generated icon: IconChevronCompactRight
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconChevronCompactRight as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconChevronCompactRight = createIcon(TablerIcon)
