/**
 * Auto-generated icon: IconLifebuoyFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLifebuoyFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLifebuoyFilled = createIcon(TablerIcon)
