/**
 * Auto-generated icon: IconXboxBFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconXboxBFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconXboxBFilled = createIcon(TablerIcon)
