/**
 * Auto-generated icon: IconSquareRoundedLetterAFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareRoundedLetterAFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareRoundedLetterAFilled = createIcon(TablerIcon)
