/**
 * Auto-generated icon: IconBrandSlack
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandSlack as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandSlack = createIcon(TablerIcon)
