/**
 * Auto-generated icon: IconDeviceTvOldFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceTvOldFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceTvOldFilled = createIcon(TablerIcon)
