/**
 * Auto-generated icon: IconFolderFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFolderFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFolderFilled = createIcon(TablerIcon)
