/**
 * Auto-generated icon: IconGitBranch
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconGitBranch as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconGitBranch = createIcon(TablerIcon)
