/**
 * Auto-generated icon: IconArrowsUpLeft
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowsUpLeft as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowsUpLeft = createIcon(TablerIcon)
