/**
 * Auto-generated icon: IconPlayerTrackPrevFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPlayerTrackPrevFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPlayerTrackPrevFilled = createIcon(TablerIcon)
