/**
 * Auto-generated icon: IconListDetails
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconListDetails as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconListDetails = createIcon(TablerIcon)
