/**
 * Auto-generated icon: IconCopyleftFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCopyleftFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCopyleftFilled = createIcon(TablerIcon)
