/**
 * Auto-generated icon: IconPropeller
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPropeller as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPropeller = createIcon(TablerIcon)
