/**
 * Auto-generated icon: IconNumber29Small
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNumber29Small as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNumber29Small = createIcon(TablerIcon)
