/**
 * Auto-generated icon: IconGraphFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconGraphFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconGraphFilled = createIcon(TablerIcon)
