/**
 * Auto-generated icon: IconMessageMinus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMessageMinus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMessageMinus = createIcon(TablerIcon)
