/**
 * Auto-generated icon: IconBrandPrisma
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandPrisma as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandPrisma = createIcon(TablerIcon)
