/**
 * Auto-generated icon: IconCircuitChangeover
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircuitChangeover as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircuitChangeover = createIcon(TablerIcon)
