/**
 * Auto-generated icon: IconGymnastics
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconGymnastics as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconGymnastics = createIcon(TablerIcon)
