/**
 * Auto-generated icon: IconSignRightFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSignRightFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSignRightFilled = createIcon(TablerIcon)
