/**
 * Auto-generated icon: IconCircle7
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircle7 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircle7 = createIcon(TablerIcon)
