/**
 * Auto-generated icon: IconLetterESmall
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLetterESmall as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLetterESmall = createIcon(TablerIcon)
