/**
 * Auto-generated icon: IconBriefcase2Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBriefcase2Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBriefcase2Filled = createIcon(TablerIcon)
