/**
 * Auto-generated icon: IconBrandUber
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandUber as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandUber = createIcon(TablerIcon)
