/**
 * Auto-generated icon: IconNumber90Small
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNumber90Small as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNumber90Small = createIcon(TablerIcon)
