/**
 * Auto-generated icon: IconHelpOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHelpOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHelpOff = createIcon(TablerIcon)
