/**
 * Auto-generated icon: IconBarbell
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBarbell as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBarbell = createIcon(TablerIcon)
