/**
 * Auto-generated icon: IconFileNeutralFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileNeutralFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileNeutralFilled = createIcon(TablerIcon)
