/**
 * Auto-generated icon: IconSpray
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSpray as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSpray = createIcon(TablerIcon)
