/**
 * Auto-generated icon: IconBadgeOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBadgeOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBadgeOff = createIcon(TablerIcon)
