/**
 * Auto-generated icon: IconMapExclamation
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMapExclamation as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMapExclamation = createIcon(TablerIcon)
