/**
 * Auto-generated icon: IconCircleDashedLetterLetterV
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleDashedLetterLetterV as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleDashedLetterLetterV = createIcon(TablerIcon)
