/**
 * Auto-generated icon: IconNorthStar
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNorthStar as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNorthStar = createIcon(TablerIcon)
