/**
 * Auto-generated icon: IconArrowsRightLeft
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowsRightLeft as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowsRightLeft = createIcon(TablerIcon)
