/**
 * Auto-generated icon: IconBallAmericanFootballOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBallAmericanFootballOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBallAmericanFootballOff = createIcon(TablerIcon)
