/**
 * Auto-generated icon: IconSquareLetterDFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareLetterDFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareLetterDFilled = createIcon(TablerIcon)
