/**
 * Auto-generated icon: IconBattery3Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBattery3Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBattery3Filled = createIcon(TablerIcon)
