/**
 * Auto-generated icon: IconBrandVisa
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandVisa as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandVisa = createIcon(TablerIcon)
