/**
 * Auto-generated icon: IconCircleDashedLetterG
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleDashedLetterG as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleDashedLetterG = createIcon(TablerIcon)
