/**
 * Auto-generated icon: IconMusic
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMusic as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMusic = createIcon(TablerIcon)
