/**
 * Auto-generated icon: IconFileTypeJs
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileTypeJs as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileTypeJs = createIcon(TablerIcon)
