/**
 * Auto-generated icon: IconKeyboard
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconKeyboard as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconKeyboard = createIcon(TablerIcon)
