/**
 * Auto-generated icon: IconBrandInstagramFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandInstagramFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandInstagramFilled = createIcon(TablerIcon)
