/**
 * Auto-generated icon: IconFilters
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFilters as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFilters = createIcon(TablerIcon)
