/**
 * Auto-generated icon: IconButterflyFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconButterflyFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconButterflyFilled = createIcon(TablerIcon)
