/**
 * Auto-generated icon: IconArmchair
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArmchair as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArmchair = createIcon(TablerIcon)
