/**
 * Auto-generated icon: IconIrregularPolyhedronPlus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconIrregularPolyhedronPlus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconIrregularPolyhedronPlus = createIcon(TablerIcon)
