/**
 * Auto-generated icon: IconMoodHeart
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMoodHeart as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMoodHeart = createIcon(TablerIcon)
