/**
 * Auto-generated icon: IconPentagonX
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPentagonX as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPentagonX = createIcon(TablerIcon)
