/**
 * Auto-generated icon: IconSquareRoundedLetterPFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareRoundedLetterPFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareRoundedLetterPFilled = createIcon(TablerIcon)
