/**
 * Auto-generated icon: IconDevicesPause
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDevicesPause as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDevicesPause = createIcon(TablerIcon)
