/**
 * Auto-generated icon: IconFileScissors
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileScissors as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileScissors = createIcon(TablerIcon)
