/**
 * Auto-generated icon: IconEyeSearch
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconEyeSearch as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconEyeSearch = createIcon(TablerIcon)
