/**
 * Auto-generated icon: IconPanoramaHorizontalFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPanoramaHorizontalFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPanoramaHorizontalFilled = createIcon(TablerIcon)
