/**
 * Auto-generated icon: IconMapPinStar
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMapPinStar as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMapPinStar = createIcon(TablerIcon)
