/**
 * Auto-generated icon: IconBrandTwitterFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandTwitterFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandTwitterFilled = createIcon(TablerIcon)
