/**
 * Auto-generated icon: IconBrandThreejs
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandThreejs as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandThreejs = createIcon(TablerIcon)
