/**
 * Auto-generated icon: IconFolder
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFolder as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFolder = createIcon(TablerIcon)
