/**
 * Auto-generated icon: IconBrandBinance
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandBinance as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandBinance = createIcon(TablerIcon)
