/**
 * Auto-generated icon: IconClipboardTypography
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconClipboardTypography as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconClipboardTypography = createIcon(TablerIcon)
