/**
 * Auto-generated icon: IconSkull
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSkull as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSkull = createIcon(TablerIcon)
