/**
 * Auto-generated icon: IconFidgetSpinnerFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFidgetSpinnerFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFidgetSpinnerFilled = createIcon(TablerIcon)
