/**
 * Auto-generated icon: IconMoodCog
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMoodCog as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMoodCog = createIcon(TablerIcon)
