/**
 * Auto-generated icon: IconLaurelWreath
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLaurelWreath as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLaurelWreath = createIcon(TablerIcon)
