/**
 * Auto-generated icon: IconSquareLetterR
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareLetterR as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareLetterR = createIcon(TablerIcon)
