/**
 * Auto-generated icon: IconCodeMinus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCodeMinus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCodeMinus = createIcon(TablerIcon)
