/**
 * Auto-generated icon: IconShoppingBagExclamation
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconShoppingBagExclamation as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconShoppingBagExclamation = createIcon(TablerIcon)
