/**
 * Auto-generated icon: IconBottle
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBottle as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBottle = createIcon(TablerIcon)
