/**
 * Auto-generated icon: IconBreadFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBreadFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBreadFilled = createIcon(TablerIcon)
