/**
 * Auto-generated icon: IconClipboardPlus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconClipboardPlus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconClipboardPlus = createIcon(TablerIcon)
