/**
 * Auto-generated icon: IconNavigationWest
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNavigationWest as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNavigationWest = createIcon(TablerIcon)
