/**
 * Auto-generated icon: IconLanguageKatakana
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLanguageKatakana as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLanguageKatakana = createIcon(TablerIcon)
