/**
 * Auto-generated icon: IconFileDownload
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileDownload as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileDownload = createIcon(TablerIcon)
