/**
 * Auto-generated icon: IconSquare4
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquare4 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquare4 = createIcon(TablerIcon)
