/**
 * Auto-generated icon: IconBellQuestion
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBellQuestion as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBellQuestion = createIcon(TablerIcon)
