/**
 * Auto-generated icon: IconStackBack
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconStackBack as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconStackBack = createIcon(TablerIcon)
