/**
 * Auto-generated icon: IconBallpenOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBallpenOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBallpenOff = createIcon(TablerIcon)
