/**
 * Auto-generated icon: IconDeviceMobileCharging
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceMobileCharging as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceMobileCharging = createIcon(TablerIcon)
