/**
 * Auto-generated icon: IconBeta
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBeta as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBeta = createIcon(TablerIcon)
