/**
 * Auto-generated icon: IconMoodXd
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMoodXd as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMoodXd = createIcon(TablerIcon)
