/**
 * Auto-generated icon: IconChartDotsFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconChartDotsFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconChartDotsFilled = createIcon(TablerIcon)
