/**
 * Auto-generated icon: IconCalendarCheck
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCalendarCheck as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCalendarCheck = createIcon(TablerIcon)
