/**
 * Auto-generated icon: IconSquareXFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareXFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareXFilled = createIcon(TablerIcon)
