/**
 * Auto-generated icon: IconTextColor
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTextColor as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTextColor = createIcon(TablerIcon)
