/**
 * Auto-generated icon: IconChartDonut4
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconChartDonut4 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconChartDonut4 = createIcon(TablerIcon)
