/**
 * Auto-generated icon: IconCookieOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCookieOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCookieOff = createIcon(TablerIcon)
