/**
 * Auto-generated icon: IconH6
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconH6 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconH6 = createIcon(TablerIcon)
