/**
 * Auto-generated icon: IconSquaresSelected
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquaresSelected as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquaresSelected = createIcon(TablerIcon)
