/**
 * Auto-generated icon: IconGenderThird
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconGenderThird as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconGenderThird = createIcon(TablerIcon)
