/**
 * Auto-generated icon: IconTransformPoint
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTransformPoint as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTransformPoint = createIcon(TablerIcon)
