/**
 * Auto-generated icon: IconAlignBoxRightStretch
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAlignBoxRightStretch as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAlignBoxRightStretch = createIcon(TablerIcon)
