/**
 * Auto-generated icon: IconDropletOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDropletOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDropletOff = createIcon(TablerIcon)
