/**
 * Auto-generated icon: IconBlur
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBlur as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBlur = createIcon(TablerIcon)
