/**
 * Auto-generated icon: IconDiaboloPlus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDiaboloPlus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDiaboloPlus = createIcon(TablerIcon)
