/**
 * Auto-generated icon: IconCoinMonero
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCoinMonero as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCoinMonero = createIcon(TablerIcon)
