/**
 * Auto-generated icon: IconBrandAlgolia
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandAlgolia as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandAlgolia = createIcon(TablerIcon)
