/**
 * Auto-generated icon: IconLetterQSmall
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLetterQSmall as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLetterQSmall = createIcon(TablerIcon)
