/**
 * Auto-generated icon: IconBattery
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBattery as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBattery = createIcon(TablerIcon)
