/**
 * Auto-generated icon: IconArrowsDoubleNwSe
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowsDoubleNwSe as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowsDoubleNwSe = createIcon(TablerIcon)
