/**
 * Auto-generated icon: IconGenderDemigirl
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconGenderDemigirl as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconGenderDemigirl = createIcon(TablerIcon)
