/**
 * Auto-generated icon: IconKeyframeAlignVerticalFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconKeyframeAlignVerticalFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconKeyframeAlignVerticalFilled = createIcon(TablerIcon)
