/**
 * Auto-generated icon: IconAlphabetBangla
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAlphabetBangla as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAlphabetBangla = createIcon(TablerIcon)
