/**
 * Auto-generated icon: IconTag
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTag as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTag = createIcon(TablerIcon)
