/**
 * Auto-generated icon: IconBusFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBusFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBusFilled = createIcon(TablerIcon)
