/**
 * Auto-generated icon: IconLine
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLine as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLine = createIcon(TablerIcon)
