/**
 * Auto-generated icon: IconMathIntegralX
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMathIntegralX as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMathIntegralX = createIcon(TablerIcon)
