/**
 * Auto-generated icon: IconBrowserCheck
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrowserCheck as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrowserCheck = createIcon(TablerIcon)
