/**
 * Auto-generated icon: IconDeviceIpadPin
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceIpadPin as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceIpadPin = createIcon(TablerIcon)
