/**
 * Auto-generated icon: IconWorldCode
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconWorldCode as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconWorldCode = createIcon(TablerIcon)
