/**
 * Auto-generated icon: IconHexagonLetterOFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHexagonLetterOFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHexagonLetterOFilled = createIcon(TablerIcon)
