/**
 * Auto-generated icon: IconLayoutAlignCenterFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLayoutAlignCenterFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLayoutAlignCenterFilled = createIcon(TablerIcon)
