/**
 * Auto-generated icon: IconH4
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconH4 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconH4 = createIcon(TablerIcon)
