/**
 * Auto-generated icon: IconPhotoCircle
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPhotoCircle as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPhotoCircle = createIcon(TablerIcon)
