/**
 * Auto-generated icon: IconDevices
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDevices as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDevices = createIcon(TablerIcon)
