/**
 * Auto-generated icon: IconArrowElbowRight
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowElbowRight as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowElbowRight = createIcon(TablerIcon)
