/**
 * Auto-generated icon: IconMelon
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMelon as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMelon = createIcon(TablerIcon)
