/**
 * Auto-generated icon: IconSquareLetterVFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareLetterVFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareLetterVFilled = createIcon(TablerIcon)
