/**
 * Auto-generated icon: IconViewportNarrow
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconViewportNarrow as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconViewportNarrow = createIcon(TablerIcon)
