/**
 * Auto-generated icon: IconBrandOffice
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandOffice as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandOffice = createIcon(TablerIcon)
