/**
 * Auto-generated icon: IconMessagePlus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMessagePlus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMessagePlus = createIcon(TablerIcon)
