/**
 * Auto-generated icon: IconFlowerFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFlowerFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFlowerFilled = createIcon(TablerIcon)
