/**
 * Auto-generated icon: IconDatabaseShare
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDatabaseShare as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDatabaseShare = createIcon(TablerIcon)
