/**
 * Auto-generated icon: IconCurrencyNano
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCurrencyNano as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCurrencyNano = createIcon(TablerIcon)
