/**
 * Auto-generated icon: IconCurrencyDram
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCurrencyDram as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCurrencyDram = createIcon(TablerIcon)
