/**
 * Auto-generated icon: IconCalendarUser
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCalendarUser as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCalendarUser = createIcon(TablerIcon)
