/**
 * Auto-generated icon: IconDeviceWatchCheck
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceWatchCheck as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceWatchCheck = createIcon(TablerIcon)
