/**
 * Auto-generated icon: IconColorSwatchOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconColorSwatchOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconColorSwatchOff = createIcon(TablerIcon)
