/**
 * Auto-generated icon: IconBomb
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBomb as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBomb = createIcon(TablerIcon)
