/**
 * Auto-generated icon: IconShoppingCartDiscount
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconShoppingCartDiscount as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconShoppingCartDiscount = createIcon(TablerIcon)
