/**
 * Auto-generated icon: IconDeviceIpadHorizontalX
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceIpadHorizontalX as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceIpadHorizontalX = createIcon(TablerIcon)
