/**
 * Auto-generated icon: IconBrandDiscord
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandDiscord as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandDiscord = createIcon(TablerIcon)
