/**
 * Auto-generated icon: IconHexagonLetterVFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHexagonLetterVFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHexagonLetterVFilled = createIcon(TablerIcon)
