/**
 * Auto-generated icon: IconFileTypeZip
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileTypeZip as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileTypeZip = createIcon(TablerIcon)
