/**
 * Auto-generated icon: IconCircleDashedLetterO
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleDashedLetterO as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleDashedLetterO = createIcon(TablerIcon)
