/**
 * Auto-generated icon: IconSquareRoundedNumber0Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareRoundedNumber0Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareRoundedNumber0Filled = createIcon(TablerIcon)
