/**
 * Auto-generated icon: IconCurrentLocationFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCurrentLocationFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCurrentLocationFilled = createIcon(TablerIcon)
