/**
 * Auto-generated icon: IconSquareRoundedChevronsDown
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareRoundedChevronsDown as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareRoundedChevronsDown = createIcon(TablerIcon)
