/**
 * Auto-generated icon: IconRadiusBottomRight
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRadiusBottomRight as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRadiusBottomRight = createIcon(TablerIcon)
