/**
 * Auto-generated icon: IconMessageStar
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMessageStar as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMessageStar = createIcon(TablerIcon)
