/**
 * Auto-generated icon: IconSectionSign
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSectionSign as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSectionSign = createIcon(TablerIcon)
