/**
 * Auto-generated icon: IconChartPie4Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconChartPie4Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconChartPie4Filled = createIcon(TablerIcon)
