/**
 * Auto-generated icon: IconTemperatureFahrenheit
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTemperatureFahrenheit as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTemperatureFahrenheit = createIcon(TablerIcon)
