/**
 * Auto-generated icon: IconTrafficLightsOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTrafficLightsOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTrafficLightsOff = createIcon(TablerIcon)
