/**
 * Auto-generated icon: IconLocationCheck
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLocationCheck as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLocationCheck = createIcon(TablerIcon)
