/**
 * Auto-generated icon: IconPlayCardKFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPlayCardKFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPlayCardKFilled = createIcon(TablerIcon)
