/**
 * Auto-generated icon: IconContainerOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconContainerOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconContainerOff = createIcon(TablerIcon)
