/**
 * Auto-generated icon: IconSquareChevronUpFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareChevronUpFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareChevronUpFilled = createIcon(TablerIcon)
