/**
 * Auto-generated icon: IconPlant
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPlant as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPlant = createIcon(TablerIcon)
