/**
 * Auto-generated icon: IconPhysotherapist
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPhysotherapist as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPhysotherapist = createIcon(TablerIcon)
