/**
 * Auto-generated icon: IconParkingCircleFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconParkingCircleFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconParkingCircleFilled = createIcon(TablerIcon)
