/**
 * Auto-generated icon: IconInfoOctagonFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconInfoOctagonFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconInfoOctagonFilled = createIcon(TablerIcon)
