/**
 * Auto-generated icon: IconBeerOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBeerOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBeerOff = createIcon(TablerIcon)
