/**
 * Auto-generated icon: IconBriefcaseOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBriefcaseOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBriefcaseOff = createIcon(TablerIcon)
