/**
 * Auto-generated icon: IconSphereOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSphereOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSphereOff = createIcon(TablerIcon)
