/**
 * Auto-generated icon: IconArrowUp
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowUp as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowUp = createIcon(TablerIcon)
