/**
 * Auto-generated icon: IconHexagonLetterUFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHexagonLetterUFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHexagonLetterUFilled = createIcon(TablerIcon)
