/**
 * Auto-generated icon: IconAlertSquareFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAlertSquareFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAlertSquareFilled = createIcon(TablerIcon)
