/**
 * Auto-generated icon: IconHeartSearch
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHeartSearch as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHeartSearch = createIcon(TablerIcon)
