/**
 * Auto-generated icon: IconMathIntegrals
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMathIntegrals as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMathIntegrals = createIcon(TablerIcon)
