/**
 * Auto-generated icon: IconVectorSpline
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconVectorSpline as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconVectorSpline = createIcon(TablerIcon)
