/**
 * Auto-generated icon: IconDeviceTabletShare
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceTabletShare as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceTabletShare = createIcon(TablerIcon)
