/**
 * Auto-generated icon: IconHexagonLetterZFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHexagonLetterZFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHexagonLetterZFilled = createIcon(TablerIcon)
