/**
 * Auto-generated icon: IconCaretLeft
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCaretLeft as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCaretLeft = createIcon(TablerIcon)
