/**
 * Auto-generated icon: IconBrandVsco
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandVsco as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandVsco = createIcon(TablerIcon)
