/**
 * Auto-generated icon: IconFall
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFall as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFall = createIcon(TablerIcon)
