/**
 * Auto-generated icon: IconBubbleTea
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBubbleTea as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBubbleTea = createIcon(TablerIcon)
