/**
 * Auto-generated icon: IconCloverFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCloverFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCloverFilled = createIcon(TablerIcon)
