/**
 * Auto-generated icon: IconGrillFork
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconGrillFork as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconGrillFork = createIcon(TablerIcon)
