/**
 * Auto-generated icon: IconBorderRightPlus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBorderRightPlus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBorderRightPlus = createIcon(TablerIcon)
