/**
 * Auto-generated icon: IconDeviceIpadBolt
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceIpadBolt as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceIpadBolt = createIcon(TablerIcon)
