/**
 * Auto-generated icon: IconBrandFinder
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandFinder as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandFinder = createIcon(TablerIcon)
