/**
 * Auto-generated icon: IconDeviceIpad
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceIpad as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceIpad = createIcon(TablerIcon)
