/**
 * Auto-generated icon: IconCheck
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCheck as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCheck = createIcon(TablerIcon)
