/**
 * Auto-generated icon: IconNumber76Small
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNumber76Small as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNumber76Small = createIcon(TablerIcon)
