/**
 * Auto-generated icon: IconUnlink
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconUnlink as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconUnlink = createIcon(TablerIcon)
