/**
 * Auto-generated icon: IconShoppingCart
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconShoppingCart as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconShoppingCart = createIcon(TablerIcon)
