/**
 * Auto-generated icon: IconZoomPan
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconZoomPan as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconZoomPan = createIcon(TablerIcon)
