/**
 * Auto-generated icon: IconFilter2Discount
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFilter2Discount as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFilter2Discount = createIcon(TablerIcon)
