/**
 * Auto-generated icon: IconHourglass
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHourglass as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHourglass = createIcon(TablerIcon)
