/**
 * Auto-generated icon: IconMoodAngryFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMoodAngryFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMoodAngryFilled = createIcon(TablerIcon)
