/**
 * Auto-generated icon: IconFileOrientation
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileOrientation as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileOrientation = createIcon(TablerIcon)
