/**
 * Auto-generated icon: IconTarget
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTarget as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTarget = createIcon(TablerIcon)
