/**
 * Auto-generated icon: IconContrast
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconContrast as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconContrast = createIcon(TablerIcon)
