/**
 * Auto-generated icon: IconRouteAltRight
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRouteAltRight as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRouteAltRight = createIcon(TablerIcon)
