/**
 * Auto-generated icon: IconDeviceGamepad3
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceGamepad3 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceGamepad3 = createIcon(TablerIcon)
