/**
 * Auto-generated icon: IconBorderTopPlus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBorderTopPlus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBorderTopPlus = createIcon(TablerIcon)
