/**
 * Auto-generated icon: IconGiftOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconGiftOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconGiftOff = createIcon(TablerIcon)
