/**
 * Auto-generated icon: IconCarGarage
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCarGarage as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCarGarage = createIcon(TablerIcon)
