/**
 * Auto-generated icon: IconManualGearboxFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconManualGearboxFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconManualGearboxFilled = createIcon(TablerIcon)
