/**
 * Auto-generated icon: IconBrandTabler
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandTabler as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandTabler = createIcon(TablerIcon)
