/**
 * Auto-generated icon: IconDeviceTablet
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceTablet as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceTablet = createIcon(TablerIcon)
