/**
 * Auto-generated icon: IconBeach
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBeach as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBeach = createIcon(TablerIcon)
