/**
 * Auto-generated icon: IconConeOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconConeOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconConeOff = createIcon(TablerIcon)
