/**
 * Auto-generated icon: IconSunset2Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSunset2Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSunset2Filled = createIcon(TablerIcon)
