/**
 * Auto-generated icon: IconCarSuv
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCarSuv as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCarSuv = createIcon(TablerIcon)
