/**
 * Auto-generated icon: IconMapPinUp
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMapPinUp as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMapPinUp = createIcon(TablerIcon)
