/**
 * Auto-generated icon: IconBasketCheck
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBasketCheck as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBasketCheck = createIcon(TablerIcon)
