/**
 * Auto-generated icon: IconBrandGraphql
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandGraphql as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandGraphql = createIcon(TablerIcon)
