/**
 * Auto-generated icon: IconChartInfographic
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconChartInfographic as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconChartInfographic = createIcon(TablerIcon)
