/**
 * Auto-generated icon: IconBrandGit
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandGit as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandGit = createIcon(TablerIcon)
