/**
 * Auto-generated icon: IconDeviceWatch
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceWatch as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceWatch = createIcon(TablerIcon)
