/**
 * Auto-generated icon: IconReorder
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconReorder as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconReorder = createIcon(TablerIcon)
