/**
 * Auto-generated icon: IconBrandTed
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandTed as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandTed = createIcon(TablerIcon)
