/**
 * Auto-generated icon: IconChartCohort
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconChartCohort as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconChartCohort = createIcon(TablerIcon)
