/**
 * Auto-generated icon: IconHexagonNumber6
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHexagonNumber6 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHexagonNumber6 = createIcon(TablerIcon)
