/**
 * Auto-generated icon: IconHexagonLetterFFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHexagonLetterFFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHexagonLetterFFilled = createIcon(TablerIcon)
