/**
 * Auto-generated icon: IconSquareRoundedArrowLeftFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareRoundedArrowLeftFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareRoundedArrowLeftFilled = createIcon(TablerIcon)
