/**
 * Auto-generated icon: IconSquareArrowUpFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareArrowUpFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareArrowUpFilled = createIcon(TablerIcon)
