/**
 * Auto-generated icon: IconMusicShare
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMusicShare as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMusicShare = createIcon(TablerIcon)
