/**
 * Auto-generated icon: IconNumber62Small
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNumber62Small as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNumber62Small = createIcon(TablerIcon)
