/**
 * Auto-generated icon: IconTriangleFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTriangleFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTriangleFilled = createIcon(TablerIcon)
