/**
 * Auto-generated icon: IconArrowNarrowUp
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowNarrowUp as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowNarrowUp = createIcon(TablerIcon)
