/**
 * Auto-generated icon: IconMessageOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMessageOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMessageOff = createIcon(TablerIcon)
