/**
 * Auto-generated icon: IconSunset
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSunset as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSunset = createIcon(TablerIcon)
