/**
 * Auto-generated icon: IconBucket
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBucket as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBucket = createIcon(TablerIcon)
