/**
 * Auto-generated icon: IconSchema
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSchema as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSchema = createIcon(TablerIcon)
