/**
 * Auto-generated icon: IconMatrix
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMatrix as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMatrix = createIcon(TablerIcon)
