/**
 * Auto-generated icon: IconShield
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconShield as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconShield = createIcon(TablerIcon)
