/**
 * Auto-generated icon: IconArrowAutofitHeight
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowAutofitHeight as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowAutofitHeight = createIcon(TablerIcon)
