/**
 * Auto-generated icon: IconMailShare
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMailShare as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMailShare = createIcon(TablerIcon)
