/**
 * Auto-generated icon: IconChartHistogram
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconChartHistogram as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconChartHistogram = createIcon(TablerIcon)
