/**
 * Auto-generated icon: IconPencilSearch
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPencilSearch as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPencilSearch = createIcon(TablerIcon)
