/**
 * Auto-generated icon: IconWifi1
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconWifi1 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconWifi1 = createIcon(TablerIcon)
