/**
 * Auto-generated icon: IconCrossFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCrossFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCrossFilled = createIcon(TablerIcon)
