/**
 * Auto-generated icon: IconAccessibleOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAccessibleOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAccessibleOff = createIcon(TablerIcon)
