/**
 * Auto-generated icon: IconMoneybagMinus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMoneybagMinus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMoneybagMinus = createIcon(TablerIcon)
