/**
 * Auto-generated icon: IconCreativeCommonsSa
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCreativeCommonsSa as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCreativeCommonsSa = createIcon(TablerIcon)
