/**
 * Auto-generated icon: IconFolderOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFolderOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFolderOff = createIcon(TablerIcon)
