/**
 * Auto-generated icon: IconBrandAo3
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandAo3 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandAo3 = createIcon(TablerIcon)
