/**
 * Auto-generated icon: IconLadder
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLadder as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLadder = createIcon(TablerIcon)
