/**
 * Auto-generated icon: IconNumber63Small
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNumber63Small as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNumber63Small = createIcon(TablerIcon)
