/**
 * Auto-generated icon: IconChefHat
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconChefHat as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconChefHat = createIcon(TablerIcon)
