/**
 * Auto-generated icon: IconSwipeDown
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSwipeDown as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSwipeDown = createIcon(TablerIcon)
