/**
 * Auto-generated icon: IconShieldCancel
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconShieldCancel as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconShieldCancel = createIcon(TablerIcon)
