/**
 * Auto-generated icon: IconPencilExclamation
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPencilExclamation as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPencilExclamation = createIcon(TablerIcon)
