/**
 * Auto-generated icon: IconBong
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBong as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBong = createIcon(TablerIcon)
