/**
 * Auto-generated icon: IconClockCheck
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconClockCheck as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconClockCheck = createIcon(TablerIcon)
