/**
 * Auto-generated icon: IconList
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconList as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconList = createIcon(TablerIcon)
