/**
 * Auto-generated icon: IconSeedlingFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSeedlingFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSeedlingFilled = createIcon(TablerIcon)
