/**
 * Auto-generated icon: IconCellSignal3
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCellSignal3 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCellSignal3 = createIcon(TablerIcon)
