/**
 * Auto-generated icon: IconInfoSquareFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconInfoSquareFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconInfoSquareFilled = createIcon(TablerIcon)
