/**
 * Auto-generated icon: IconCircleDashedNumber2
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleDashedNumber2 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleDashedNumber2 = createIcon(TablerIcon)
