/**
 * Auto-generated icon: IconDeviceIpadHorizontalCog
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceIpadHorizontalCog as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceIpadHorizontalCog = createIcon(TablerIcon)
