/**
 * Auto-generated icon: IconSquareRoundedLetterNFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareRoundedLetterNFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareRoundedLetterNFilled = createIcon(TablerIcon)
