/**
 * Auto-generated icon: IconMoodEmptyFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMoodEmptyFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMoodEmptyFilled = createIcon(TablerIcon)
