/**
 * Auto-generated icon: IconNumber52Small
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNumber52Small as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNumber52Small = createIcon(TablerIcon)
