/**
 * Auto-generated icon: IconMapX
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMapX as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMapX = createIcon(TablerIcon)
