/**
 * Auto-generated icon: IconSteeringWheel
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSteeringWheel as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSteeringWheel = createIcon(TablerIcon)
