/**
 * Auto-generated icon: IconTransactionYuan
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTransactionYuan as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTransactionYuan = createIcon(TablerIcon)
