/**
 * Auto-generated icon: IconCircleNumber0Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleNumber0Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleNumber0Filled = createIcon(TablerIcon)
