/**
 * Auto-generated icon: IconReceiptYenFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconReceiptYenFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconReceiptYenFilled = createIcon(TablerIcon)
