/**
 * Auto-generated icon: IconPower
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPower as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPower = createIcon(TablerIcon)
