/**
 * Auto-generated icon: IconHelpSmall
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHelpSmall as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHelpSmall = createIcon(TablerIcon)
