/**
 * Auto-generated icon: IconArrowDownRhombus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowDownRhombus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowDownRhombus = createIcon(TablerIcon)
