/**
 * Auto-generated icon: IconBuildingCarousel
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBuildingCarousel as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBuildingCarousel = createIcon(TablerIcon)
