/**
 * Auto-generated icon: IconAssemblyOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAssemblyOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAssemblyOff = createIcon(TablerIcon)
