/**
 * Auto-generated icon: IconPencilCancel
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPencilCancel as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPencilCancel = createIcon(TablerIcon)
