/**
 * Auto-generated icon: IconSquareLetterZFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareLetterZFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareLetterZFilled = createIcon(TablerIcon)
