/**
 * Auto-generated icon: IconArrowDownBar
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowDownBar as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowDownBar = createIcon(TablerIcon)
