/**
 * Auto-generated icon: IconDotsCircleHorizontal
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDotsCircleHorizontal as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDotsCircleHorizontal = createIcon(TablerIcon)
