/**
 * Auto-generated icon: IconNumber54Small
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNumber54Small as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNumber54Small = createIcon(TablerIcon)
