/**
 * Auto-generated icon: IconMoodSad2
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMoodSad2 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMoodSad2 = createIcon(TablerIcon)
