/**
 * Auto-generated icon: IconStormOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconStormOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconStormOff = createIcon(TablerIcon)
