/**
 * Auto-generated icon: IconCircleDashedLetterW
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleDashedLetterW as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleDashedLetterW = createIcon(TablerIcon)
