/**
 * Auto-generated icon: IconBrandGithub
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandGithub as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandGithub = createIcon(TablerIcon)
