/**
 * Auto-generated icon: IconReceiptOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconReceiptOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconReceiptOff = createIcon(TablerIcon)
