/**
 * Auto-generated icon: IconPhotoExclamation
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPhotoExclamation as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPhotoExclamation = createIcon(TablerIcon)
