/**
 * Auto-generated icon: IconHeartDown
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHeartDown as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHeartDown = createIcon(TablerIcon)
