/**
 * Auto-generated icon: IconHeadphonesOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHeadphonesOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHeadphonesOff = createIcon(TablerIcon)
