/**
 * Auto-generated icon: IconFilter2Cog
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFilter2Cog as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFilter2Cog = createIcon(TablerIcon)
