/**
 * Auto-generated icon: IconFloatLeft
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFloatLeft as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFloatLeft = createIcon(TablerIcon)
