/**
 * Auto-generated icon: IconJoinStraight
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconJoinStraight as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconJoinStraight = createIcon(TablerIcon)
