/**
 * Auto-generated icon: IconIroningSteamOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconIroningSteamOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconIroningSteamOff = createIcon(TablerIcon)
