/**
 * Auto-generated icon: IconForbid2Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconForbid2Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconForbid2Filled = createIcon(TablerIcon)
