/**
 * Auto-generated icon: IconAdjustmentsHorizontal
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAdjustmentsHorizontal as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAdjustmentsHorizontal = createIcon(TablerIcon)
