/**
 * Auto-generated icon: IconPhotoMinus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPhotoMinus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPhotoMinus = createIcon(TablerIcon)
