/**
 * Auto-generated icon: IconSquareF9Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareF9Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareF9Filled = createIcon(TablerIcon)
