/**
 * Auto-generated icon: IconRosetteNumber2
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRosetteNumber2 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRosetteNumber2 = createIcon(TablerIcon)
