/**
 * Auto-generated icon: IconNumber10Small
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNumber10Small as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNumber10Small = createIcon(TablerIcon)
