/**
 * Auto-generated icon: IconMagnet
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMagnet as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMagnet = createIcon(TablerIcon)
