/**
 * Auto-generated icon: IconTransformPointTopRight
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTransformPointTopRight as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTransformPointTopRight = createIcon(TablerIcon)
