/**
 * Auto-generated icon: IconLetterY
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLetterY as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLetterY = createIcon(TablerIcon)
