/**
 * Auto-generated icon: IconZzz
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconZzz as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconZzz = createIcon(TablerIcon)
