/**
 * Auto-generated icon: IconBrandXFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandXFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandXFilled = createIcon(TablerIcon)
