/**
 * Auto-generated icon: IconMoodUnamused
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMoodUnamused as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMoodUnamused = createIcon(TablerIcon)
