/**
 * Auto-generated icon: IconDatabaseImport
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDatabaseImport as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDatabaseImport = createIcon(TablerIcon)
