/**
 * Auto-generated icon: IconSquareLetterNFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareLetterNFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareLetterNFilled = createIcon(TablerIcon)
