/**
 * Auto-generated icon: IconNumber61Small
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNumber61Small as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNumber61Small = createIcon(TablerIcon)
