/**
 * Auto-generated icon: IconSquareRoundedLetterBFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareRoundedLetterBFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareRoundedLetterBFilled = createIcon(TablerIcon)
