/**
 * Auto-generated icon: IconMailFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMailFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMailFilled = createIcon(TablerIcon)
