/**
 * Auto-generated icon: IconBrandZhihu
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandZhihu as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandZhihu = createIcon(TablerIcon)
