/**
 * Auto-generated icon: IconGolfOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconGolfOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconGolfOff = createIcon(TablerIcon)
