/**
 * Auto-generated icon: IconKeyframesFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconKeyframesFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconKeyframesFilled = createIcon(TablerIcon)
