/**
 * Auto-generated icon: IconLetterN
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLetterN as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLetterN = createIcon(TablerIcon)
