/**
 * Auto-generated icon: IconCornerDownRight
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCornerDownRight as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCornerDownRight = createIcon(TablerIcon)
