/**
 * Auto-generated icon: IconMushroom
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMushroom as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMushroom = createIcon(TablerIcon)
