/**
 * Auto-generated icon: IconIndentDecrease
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconIndentDecrease as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconIndentDecrease = createIcon(TablerIcon)
