/**
 * Auto-generated icon: IconDeviceIpadHorizontalUp
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceIpadHorizontalUp as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceIpadHorizontalUp = createIcon(TablerIcon)
