/**
 * Auto-generated icon: IconSnowman
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSnowman as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSnowman = createIcon(TablerIcon)
