/**
 * Auto-generated icon: IconCloudDollar
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCloudDollar as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCloudDollar = createIcon(TablerIcon)
