/**
 * Auto-generated icon: IconSortZA
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSortZA as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSortZA = createIcon(TablerIcon)
