/**
 * Auto-generated icon: IconNote
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNote as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNote = createIcon(TablerIcon)
