/**
 * Auto-generated icon: IconCoinPound
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCoinPound as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCoinPound = createIcon(TablerIcon)
