/**
 * Auto-generated icon: IconClubs
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconClubs as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconClubs = createIcon(TablerIcon)
