/**
 * Auto-generated icon: IconCapRounded
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCapRounded as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCapRounded = createIcon(TablerIcon)
