/**
 * Auto-generated icon: IconLogicNot
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLogicNot as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLogicNot = createIcon(TablerIcon)
