/**
 * Auto-generated icon: IconDeviceDesktopExclamation
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceDesktopExclamation as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceDesktopExclamation = createIcon(TablerIcon)
