/**
 * Auto-generated icon: IconStethoscope
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconStethoscope as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconStethoscope = createIcon(TablerIcon)
