/**
 * Auto-generated icon: IconPencilHeart
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPencilHeart as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPencilHeart = createIcon(TablerIcon)
