/**
 * Auto-generated icon: IconLayoutAlignLeftFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLayoutAlignLeftFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLayoutAlignLeftFilled = createIcon(TablerIcon)
