/**
 * Auto-generated icon: IconLogout
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLogout as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLogout = createIcon(TablerIcon)
