/**
 * Auto-generated icon: IconWaveSawTool
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconWaveSawTool as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconWaveSawTool = createIcon(TablerIcon)
