/**
 * Auto-generated icon: IconMailBolt
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMailBolt as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMailBolt = createIcon(TablerIcon)
