/**
 * Auto-generated icon: IconShieldLockFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconShieldLockFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconShieldLockFilled = createIcon(TablerIcon)
