/**
 * Auto-generated icon: IconFlagOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFlagOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFlagOff = createIcon(TablerIcon)
