/**
 * Auto-generated icon: IconHelpHexagon
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHelpHexagon as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHelpHexagon = createIcon(TablerIcon)
