/**
 * Auto-generated icon: IconViewfinderOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconViewfinderOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconViewfinderOff = createIcon(TablerIcon)
