/**
 * Auto-generated icon: IconBleachChlorine
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBleachChlorine as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBleachChlorine = createIcon(TablerIcon)
