/**
 * Auto-generated icon: IconCoffin
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCoffin as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCoffin = createIcon(TablerIcon)
