/**
 * Auto-generated icon: IconRating12Plus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRating12Plus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRating12Plus = createIcon(TablerIcon)
