/**
 * Auto-generated icon: IconArrowRightTail
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowRightTail as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowRightTail = createIcon(TablerIcon)
