/**
 * Auto-generated icon: IconClipboardData
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconClipboardData as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconClipboardData = createIcon(TablerIcon)
