/**
 * Auto-generated icon: IconArrowAutofitRightFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowAutofitRightFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowAutofitRightFilled = createIcon(TablerIcon)
