/**
 * Auto-generated icon: IconTallymark1
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTallymark1 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTallymark1 = createIcon(TablerIcon)
