/**
 * Auto-generated icon: IconCapture
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCapture as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCapture = createIcon(TablerIcon)
