/**
 * Auto-generated icon: IconWashDryW
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconWashDryW as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconWashDryW = createIcon(TablerIcon)
