/**
 * Auto-generated icon: IconFingerprintScan
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFingerprintScan as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFingerprintScan = createIcon(TablerIcon)
