/**
 * Auto-generated icon: IconNumber1
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNumber1 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNumber1 = createIcon(TablerIcon)
