/**
 * Auto-generated icon: IconCameraX
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCameraX as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCameraX = createIcon(TablerIcon)
