/**
 * Auto-generated icon: IconChevronLeft
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconChevronLeft as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconChevronLeft = createIcon(TablerIcon)
