/**
 * Auto-generated icon: IconBrandSoundcloud
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandSoundcloud as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandSoundcloud = createIcon(TablerIcon)
