/**
 * Auto-generated icon: IconSquareRoundedChevronUp
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareRoundedChevronUp as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareRoundedChevronUp = createIcon(TablerIcon)
