/**
 * Auto-generated icon: IconBrandUnity
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandUnity as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandUnity = createIcon(TablerIcon)
