/**
 * Auto-generated icon: IconBuildingLighthouse
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBuildingLighthouse as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBuildingLighthouse = createIcon(TablerIcon)
