/**
 * Auto-generated icon: IconBadgeTmFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBadgeTmFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBadgeTmFilled = createIcon(TablerIcon)
