/**
 * Auto-generated icon: IconCircleNumber8Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleNumber8Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleNumber8Filled = createIcon(TablerIcon)
