/**
 * Auto-generated icon: IconArrowElbowLeft
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowElbowLeft as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowElbowLeft = createIcon(TablerIcon)
