/**
 * Auto-generated icon: IconBrandEdge
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandEdge as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandEdge = createIcon(TablerIcon)
