/**
 * Auto-generated icon: IconMouseOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMouseOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMouseOff = createIcon(TablerIcon)
