/**
 * Auto-generated icon: IconSquareF3Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareF3Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareF3Filled = createIcon(TablerIcon)
