/**
 * Auto-generated icon: IconTrashFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTrashFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTrashFilled = createIcon(TablerIcon)
