/**
 * Auto-generated icon: IconLineHeight
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLineHeight as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLineHeight = createIcon(TablerIcon)
