/**
 * Auto-generated icon: IconServerSpark
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconServerSpark as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconServerSpark = createIcon(TablerIcon)
