/**
 * Auto-generated icon: IconBatteryVerticalExclamation
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBatteryVerticalExclamation as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBatteryVerticalExclamation = createIcon(TablerIcon)
