/**
 * Auto-generated icon: IconReceipt
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconReceipt as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconReceipt = createIcon(TablerIcon)
