/**
 * Auto-generated icon: IconSquareRoundedNumber2
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareRoundedNumber2 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareRoundedNumber2 = createIcon(TablerIcon)
