/**
 * Auto-generated icon: IconSelector
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSelector as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSelector = createIcon(TablerIcon)
