/**
 * Auto-generated icon: IconBrandKakoTalk
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandKakoTalk as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandKakoTalk = createIcon(TablerIcon)
