/**
 * Auto-generated icon: IconSTurnDown
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSTurnDown as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSTurnDown = createIcon(TablerIcon)
