/**
 * Auto-generated icon: IconMoodCheck
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMoodCheck as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMoodCheck = createIcon(TablerIcon)
