/**
 * Auto-generated icon: IconMusicStar
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMusicStar as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMusicStar = createIcon(TablerIcon)
