/**
 * Auto-generated icon: IconArrowsJoin
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowsJoin as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowsJoin = createIcon(TablerIcon)
