/**
 * Auto-generated icon: IconAmpersand
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAmpersand as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAmpersand = createIcon(TablerIcon)
