/**
 * Auto-generated icon: IconBrandWindows
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandWindows as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandWindows = createIcon(TablerIcon)
