/**
 * Auto-generated icon: IconSquareRoundedLetterQFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareRoundedLetterQFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareRoundedLetterQFilled = createIcon(TablerIcon)
