/**
 * Auto-generated icon: IconBorderHorizontal
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBorderHorizontal as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBorderHorizontal = createIcon(TablerIcon)
