/**
 * Auto-generated icon: IconCurrencyKip
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCurrencyKip as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCurrencyKip = createIcon(TablerIcon)
