/**
 * Auto-generated icon: IconPhotoStar
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPhotoStar as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPhotoStar = createIcon(TablerIcon)
