/**
 * Auto-generated icon: IconBeerFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBeerFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBeerFilled = createIcon(TablerIcon)
