/**
 * Auto-generated icon: IconFileLike
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileLike as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileLike = createIcon(TablerIcon)
