/**
 * Auto-generated icon: IconTelescope
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTelescope as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTelescope = createIcon(TablerIcon)
