/**
 * Auto-generated icon: IconDeviceIpadCancel
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceIpadCancel as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceIpadCancel = createIcon(TablerIcon)
