/**
 * Auto-generated icon: IconGenderTrasvesti
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconGenderTrasvesti as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconGenderTrasvesti = createIcon(TablerIcon)
