/**
 * Auto-generated icon: IconFileX
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileX as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileX = createIcon(TablerIcon)
