/**
 * Auto-generated icon: IconHeadphonesFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHeadphonesFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHeadphonesFilled = createIcon(TablerIcon)
