/**
 * Auto-generated icon: IconPlaystationTriangle
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPlaystationTriangle as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPlaystationTriangle = createIcon(TablerIcon)
