/**
 * Auto-generated icon: IconMapPinShare
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMapPinShare as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMapPinShare = createIcon(TablerIcon)
