/**
 * Auto-generated icon: IconStretching
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconStretching as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconStretching = createIcon(TablerIcon)
