/**
 * Auto-generated icon: IconMessageCircle
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMessageCircle as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMessageCircle = createIcon(TablerIcon)
