/**
 * Auto-generated icon: IconChess
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconChess as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconChess = createIcon(TablerIcon)
