/**
 * Auto-generated icon: IconPigFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPigFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPigFilled = createIcon(TablerIcon)
