/**
 * Auto-generated icon: IconTrees
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTrees as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTrees = createIcon(TablerIcon)
