/**
 * Auto-generated icon: IconPhotoPlus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPhotoPlus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPhotoPlus = createIcon(TablerIcon)
