/**
 * Auto-generated icon: IconMoodWink
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMoodWink as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMoodWink = createIcon(TablerIcon)
