/**
 * Auto-generated icon: IconMessageCircleCode
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMessageCircleCode as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMessageCircleCode = createIcon(TablerIcon)
