/**
 * Auto-generated icon: IconInfoSquareRoundedFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconInfoSquareRoundedFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconInfoSquareRoundedFilled = createIcon(TablerIcon)
