/**
 * Auto-generated icon: IconFlagHeart
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFlagHeart as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFlagHeart = createIcon(TablerIcon)
