/**
 * Auto-generated icon: IconSquareMinus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareMinus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareMinus = createIcon(TablerIcon)
