/**
 * Auto-generated icon: IconCurrencyForint
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCurrencyForint as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCurrencyForint = createIcon(TablerIcon)
