/**
 * Auto-generated icon: IconCashMoveBack
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCashMoveBack as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCashMoveBack = createIcon(TablerIcon)
