/**
 * Auto-generated icon: IconBuildingBroadcastTowerFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBuildingBroadcastTowerFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBuildingBroadcastTowerFilled = createIcon(TablerIcon)
