/**
 * Auto-generated icon: IconLetterP
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLetterP as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLetterP = createIcon(TablerIcon)
