/**
 * Auto-generated icon: IconAlignBoxLeftMiddleFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAlignBoxLeftMiddleFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAlignBoxLeftMiddleFilled = createIcon(TablerIcon)
