/**
 * Auto-generated icon: IconCompass
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCompass as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCompass = createIcon(TablerIcon)
