/**
 * Auto-generated icon: IconDeviceTabletX
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceTabletX as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceTabletX = createIcon(TablerIcon)
