/**
 * Auto-generated icon: IconGolfFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconGolfFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconGolfFilled = createIcon(TablerIcon)
