/**
 * Auto-generated icon: IconSquareChevronsRight
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareChevronsRight as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareChevronsRight = createIcon(TablerIcon)
