/**
 * Auto-generated icon: IconH1
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconH1 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconH1 = createIcon(TablerIcon)
