/**
 * Auto-generated icon: IconFileSettings
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileSettings as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileSettings = createIcon(TablerIcon)
