/**
 * Auto-generated icon: IconFileLambda
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileLambda as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileLambda = createIcon(TablerIcon)
