/**
 * Auto-generated icon: IconAdjustmentsQuestion
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAdjustmentsQuestion as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAdjustmentsQuestion = createIcon(TablerIcon)
