/**
 * Auto-generated icon: IconPackageImport
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPackageImport as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPackageImport = createIcon(TablerIcon)
