/**
 * Auto-generated icon: IconMessageCircleDown
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMessageCircleDown as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMessageCircleDown = createIcon(TablerIcon)
