/**
 * Auto-generated icon: IconTags
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTags as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTags = createIcon(TablerIcon)
