/**
 * Auto-generated icon: IconApple
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconApple as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconApple = createIcon(TablerIcon)
