/**
 * Auto-generated icon: IconCloudComputingFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCloudComputingFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCloudComputingFilled = createIcon(TablerIcon)
