/**
 * Auto-generated icon: IconSquareNumber7
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareNumber7 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareNumber7 = createIcon(TablerIcon)
