/**
 * Auto-generated icon: IconBracketsContainStart
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBracketsContainStart as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBracketsContainStart = createIcon(TablerIcon)
