/**
 * Auto-generated icon: IconPlayCard9
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPlayCard9 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPlayCard9 = createIcon(TablerIcon)
