/**
 * Auto-generated icon: IconCircleDashedLetterF
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleDashedLetterF as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleDashedLetterF = createIcon(TablerIcon)
