/**
 * Auto-generated icon: IconLivePhotoOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLivePhotoOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLivePhotoOff = createIcon(TablerIcon)
