/**
 * Auto-generated icon: IconDeviceTabletUp
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceTabletUp as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceTabletUp = createIcon(TablerIcon)
