/**
 * Auto-generated icon: IconDice2
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDice2 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDice2 = createIcon(TablerIcon)
