/**
 * Auto-generated icon: IconLetterI
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLetterI as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLetterI = createIcon(TablerIcon)
