/**
 * Auto-generated icon: IconTallymark3
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTallymark3 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTallymark3 = createIcon(TablerIcon)
