/**
 * Auto-generated icon: IconChevronCompactUp
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconChevronCompactUp as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconChevronCompactUp = createIcon(TablerIcon)
