/**
 * Auto-generated icon: IconShare3
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconShare3 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconShare3 = createIcon(TablerIcon)
