/**
 * Auto-generated icon: IconShieldExclamation
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconShieldExclamation as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconShieldExclamation = createIcon(TablerIcon)
