/**
 * Auto-generated icon: Icon3dCubeSphereOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { Icon3dCubeSphereOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const Icon3dCubeSphereOff = createIcon(TablerIcon)
