/**
 * Auto-generated icon: IconLetterG
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLetterG as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLetterG = createIcon(TablerIcon)
