/**
 * Auto-generated icon: IconMoodOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMoodOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMoodOff = createIcon(TablerIcon)
