/**
 * Auto-generated icon: IconShieldCheck
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconShieldCheck as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconShieldCheck = createIcon(TablerIcon)
