/**
 * Auto-generated icon: IconUserOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconUserOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconUserOff = createIcon(TablerIcon)
