/**
 * Auto-generated icon: IconManFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconManFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconManFilled = createIcon(TablerIcon)
