/**
 * Auto-generated icon: IconBusOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBusOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBusOff = createIcon(TablerIcon)
