/**
 * Auto-generated icon: IconShieldBolt
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconShieldBolt as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconShieldBolt = createIcon(TablerIcon)
