/**
 * Auto-generated icon: IconBat
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBat as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBat = createIcon(TablerIcon)
