/**
 * Auto-generated icon: IconLayoutDashboardFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLayoutDashboardFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLayoutDashboardFilled = createIcon(TablerIcon)
