/**
 * Auto-generated icon: IconDeviceImacX
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceImacX as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceImacX = createIcon(TablerIcon)
