/**
 * Auto-generated icon: IconSquareRoundedLetterJFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareRoundedLetterJFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareRoundedLetterJFilled = createIcon(TablerIcon)
