/**
 * Auto-generated icon: IconCurrencyDirham
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCurrencyDirham as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCurrencyDirham = createIcon(TablerIcon)
