/**
 * Auto-generated icon: IconBrandGoogleFit
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandGoogleFit as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandGoogleFit = createIcon(TablerIcon)
