/**
 * Auto-generated icon: IconXboxXFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconXboxXFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconXboxXFilled = createIcon(TablerIcon)
