/**
 * Auto-generated icon: IconCopyMinus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCopyMinus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCopyMinus = createIcon(TablerIcon)
