/**
 * Auto-generated icon: IconChartRadar
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconChartRadar as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconChartRadar = createIcon(TablerIcon)
