/**
 * Auto-generated icon: IconNavigationPlus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNavigationPlus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNavigationPlus = createIcon(TablerIcon)
