/**
 * Auto-generated icon: IconCalendarWeek
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCalendarWeek as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCalendarWeek = createIcon(TablerIcon)
