/**
 * Auto-generated icon: IconFiretruck
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFiretruck as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFiretruck = createIcon(TablerIcon)
