/**
 * Auto-generated icon: IconIconsFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconIconsFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconIconsFilled = createIcon(TablerIcon)
