/**
 * Auto-generated icon: IconBoxAlignBottomLeftFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBoxAlignBottomLeftFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBoxAlignBottomLeftFilled = createIcon(TablerIcon)
