/**
 * Auto-generated icon: IconToolsKitchen3
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconToolsKitchen3 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconToolsKitchen3 = createIcon(TablerIcon)
