/**
 * Auto-generated icon: IconSoupOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSoupOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSoupOff = createIcon(TablerIcon)
