/**
 * Auto-generated icon: IconHexagonLetterMFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHexagonLetterMFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHexagonLetterMFilled = createIcon(TablerIcon)
