/**
 * Auto-generated icon: IconRosetteNumber1
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRosetteNumber1 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRosetteNumber1 = createIcon(TablerIcon)
