/**
 * Auto-generated icon: IconPercentage30
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPercentage30 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPercentage30 = createIcon(TablerIcon)
