/**
 * Auto-generated icon: IconMailCheck
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMailCheck as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMailCheck = createIcon(TablerIcon)
