/**
 * Auto-generated icon: IconLockCancel
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLockCancel as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLockCancel = createIcon(TablerIcon)
