/**
 * Auto-generated icon: IconMoodEmpty
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMoodEmpty as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMoodEmpty = createIcon(TablerIcon)
