/**
 * Auto-generated icon: IconBrandChrome
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandChrome as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandChrome = createIcon(TablerIcon)
