/**
 * Auto-generated icon: IconBrandMercedes
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandMercedes as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandMercedes = createIcon(TablerIcon)
