/**
 * Auto-generated icon: IconFileTime
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileTime as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileTime = createIcon(TablerIcon)
