/**
 * Auto-generated icon: IconBrandDisney
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandDisney as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandDisney = createIcon(TablerIcon)
