/**
 * Auto-generated icon: IconFolderSearch
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFolderSearch as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFolderSearch = createIcon(TablerIcon)
