/**
 * Auto-generated icon: IconHandGrab
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHandGrab as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHandGrab = createIcon(TablerIcon)
