/**
 * Auto-generated icon: IconBatteryVertical3
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBatteryVertical3 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBatteryVertical3 = createIcon(TablerIcon)
