/**
 * Auto-generated icon: IconEditOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconEditOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconEditOff = createIcon(TablerIcon)
