/**
 * Auto-generated icon: IconTextRecognition
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTextRecognition as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTextRecognition = createIcon(TablerIcon)
