/**
 * Auto-generated icon: IconBrandGmail
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandGmail as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandGmail = createIcon(TablerIcon)
