/**
 * Auto-generated icon: IconCircleArrowUpRightFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleArrowUpRightFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleArrowUpRightFilled = createIcon(TablerIcon)
