/**
 * Auto-generated icon: IconNotebookOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNotebookOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNotebookOff = createIcon(TablerIcon)
