/**
 * Auto-generated icon: IconTopologyStar
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTopologyStar as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTopologyStar = createIcon(TablerIcon)
