/**
 * Auto-generated icon: IconArrowBarRight
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowBarRight as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowBarRight = createIcon(TablerIcon)
