/**
 * Auto-generated icon: IconMusicCode
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMusicCode as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMusicCode = createIcon(TablerIcon)
