/**
 * Auto-generated icon: IconArrowUpDashed
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowUpDashed as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowUpDashed = createIcon(TablerIcon)
