/**
 * Auto-generated icon: IconBatteryOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBatteryOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBatteryOff = createIcon(TablerIcon)
