/**
 * Auto-generated icon: IconCampfireFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCampfireFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCampfireFilled = createIcon(TablerIcon)
