/**
 * Auto-generated icon: IconBadgeCc
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBadgeCc as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBadgeCc = createIcon(TablerIcon)
