/**
 * Auto-generated icon: IconArticleFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArticleFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArticleFilled = createIcon(TablerIcon)
