/**
 * Auto-generated icon: IconBmp
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBmp as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBmp = createIcon(TablerIcon)
