/**
 * Auto-generated icon: IconBrandX
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandX as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandX = createIcon(TablerIcon)
