/**
 * Auto-generated icon: IconBrandReactNative
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandReactNative as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandReactNative = createIcon(TablerIcon)
