/**
 * Auto-generated icon: IconBook
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBook as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBook = createIcon(TablerIcon)
