/**
 * Auto-generated icon: IconDeviceMobileVibration
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceMobileVibration as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceMobileVibration = createIcon(TablerIcon)
