/**
 * Auto-generated icon: IconClipboardOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconClipboardOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconClipboardOff = createIcon(TablerIcon)
