/**
 * Auto-generated icon: IconCherryFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCherryFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCherryFilled = createIcon(TablerIcon)
