/**
 * Auto-generated icon: IconFingerprintOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFingerprintOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFingerprintOff = createIcon(TablerIcon)
