/**
 * Auto-generated icon: IconSquareAsterisk
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareAsterisk as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareAsterisk = createIcon(TablerIcon)
