/**
 * Auto-generated icon: IconSortAscendingSmallBig
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSortAscendingSmallBig as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSortAscendingSmallBig = createIcon(TablerIcon)
