/**
 * Auto-generated icon: IconTimeDurationOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTimeDurationOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTimeDurationOff = createIcon(TablerIcon)
