/**
 * Auto-generated icon: IconWashGentle
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconWashGentle as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconWashGentle = createIcon(TablerIcon)
