/**
 * Auto-generated icon: IconHeartPin
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHeartPin as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHeartPin = createIcon(TablerIcon)
