/**
 * Auto-generated icon: IconArrowMergeRight
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowMergeRight as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowMergeRight = createIcon(TablerIcon)
