/**
 * Auto-generated icon: IconHandRingFinger
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHandRingFinger as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHandRingFinger = createIcon(TablerIcon)
