/**
 * Auto-generated icon: IconBrandVercel
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandVercel as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandVercel = createIcon(TablerIcon)
