/**
 * Auto-generated icon: IconSquareNumber1Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareNumber1Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareNumber1Filled = createIcon(TablerIcon)
