/**
 * Auto-generated icon: IconWashEco
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconWashEco as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconWashEco = createIcon(TablerIcon)
