/**
 * Auto-generated icon: IconSitemapFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSitemapFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSitemapFilled = createIcon(TablerIcon)
