/**
 * Auto-generated icon: IconHandFingerRight
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHandFingerRight as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHandFingerRight = createIcon(TablerIcon)
