/**
 * Auto-generated icon: IconSignalE
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSignalE as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSignalE = createIcon(TablerIcon)
