/**
 * Auto-generated icon: IconHexagonLetterO
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHexagonLetterO as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHexagonLetterO = createIcon(TablerIcon)
