/**
 * Auto-generated icon: IconIroning3Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconIroning3Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconIroning3Filled = createIcon(TablerIcon)
