/**
 * Auto-generated icon: IconBed
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBed as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBed = createIcon(TablerIcon)
