/**
 * Auto-generated icon: IconHomeSpark
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHomeSpark as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHomeSpark = createIcon(TablerIcon)
