/**
 * Auto-generated icon: IconPlane
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPlane as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPlane = createIcon(TablerIcon)
