/**
 * Auto-generated icon: IconDeviceIpadHorizontalPause
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceIpadHorizontalPause as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceIpadHorizontalPause = createIcon(TablerIcon)
