/**
 * Auto-generated icon: IconBrandUbuntu
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandUbuntu as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandUbuntu = createIcon(TablerIcon)
