/**
 * Auto-generated icon: IconHexagonLetterX
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHexagonLetterX as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHexagonLetterX = createIcon(TablerIcon)
