/**
 * Auto-generated icon: IconArrowLeftCircleFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowLeftCircleFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowLeftCircleFilled = createIcon(TablerIcon)
