/**
 * Auto-generated icon: IconThumbUp
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconThumbUp as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconThumbUp = createIcon(TablerIcon)
