/**
 * Auto-generated icon: IconArrowBigDownLines
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowBigDownLines as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowBigDownLines = createIcon(TablerIcon)
