/**
 * Auto-generated icon: IconDetails
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDetails as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDetails = createIcon(TablerIcon)
