/**
 * Auto-generated icon: IconHeartUp
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHeartUp as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHeartUp = createIcon(TablerIcon)
