/**
 * Auto-generated icon: IconBrandSketchFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandSketchFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandSketchFilled = createIcon(TablerIcon)
