/**
 * Auto-generated icon: IconBrandHeadlessui
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandHeadlessui as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandHeadlessui = createIcon(TablerIcon)
