/**
 * Auto-generated icon: IconArmchair2
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArmchair2 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArmchair2 = createIcon(TablerIcon)
