/**
 * Auto-generated icon: IconTopologyBus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTopologyBus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTopologyBus = createIcon(TablerIcon)
