/**
 * Auto-generated icon: IconBluetoothX
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBluetoothX as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBluetoothX = createIcon(TablerIcon)
