/**
 * Auto-generated icon: IconProng
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconProng as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconProng = createIcon(TablerIcon)
