/**
 * Auto-generated icon: IconCsv
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCsv as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCsv = createIcon(TablerIcon)
