/**
 * Auto-generated icon: IconCircleLetterN
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleLetterN as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleLetterN = createIcon(TablerIcon)
