/**
 * Auto-generated icon: IconBrandPocket
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandPocket as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandPocket = createIcon(TablerIcon)
