/**
 * Auto-generated icon: IconNumber17Small
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNumber17Small as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNumber17Small = createIcon(TablerIcon)
