/**
 * Auto-generated icon: IconCurrencyLari
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCurrencyLari as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCurrencyLari = createIcon(TablerIcon)
