/**
 * Auto-generated icon: IconCornerRightUp
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCornerRightUp as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCornerRightUp = createIcon(TablerIcon)
