/**
 * Auto-generated icon: IconBabyCarriageFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBabyCarriageFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBabyCarriageFilled = createIcon(TablerIcon)
