/**
 * Auto-generated icon: IconMathEqualGreater
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMathEqualGreater as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMathEqualGreater = createIcon(TablerIcon)
