/**
 * Auto-generated icon: IconShieldCheckFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconShieldCheckFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconShieldCheckFilled = createIcon(TablerIcon)
