/**
 * Auto-generated icon: IconSlash
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSlash as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSlash = createIcon(TablerIcon)
