/**
 * Auto-generated icon: IconBrowserShare
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrowserShare as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrowserShare = createIcon(TablerIcon)
