/**
 * Auto-generated icon: IconClockMinus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconClockMinus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconClockMinus = createIcon(TablerIcon)
