/**
 * Auto-generated icon: IconArrowAutofitLeftFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowAutofitLeftFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowAutofitLeftFilled = createIcon(TablerIcon)
