/**
 * Auto-generated icon: IconScaleOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconScaleOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconScaleOff = createIcon(TablerIcon)
