/**
 * Auto-generated icon: IconConfettiFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconConfettiFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconConfettiFilled = createIcon(TablerIcon)
