/**
 * Auto-generated icon: IconCircleArrowDown
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleArrowDown as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleArrowDown = createIcon(TablerIcon)
