/**
 * Auto-generated icon: IconDoorOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDoorOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDoorOff = createIcon(TablerIcon)
