/**
 * Auto-generated icon: IconHanger
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHanger as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHanger = createIcon(TablerIcon)
