/**
 * Auto-generated icon: IconLayoutBoard
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLayoutBoard as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLayoutBoard = createIcon(TablerIcon)
