/**
 * Auto-generated icon: IconZodiacLeo
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconZodiacLeo as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconZodiacLeo = createIcon(TablerIcon)
