/**
 * Auto-generated icon: IconBrandGooglePodcasts
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandGooglePodcasts as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandGooglePodcasts = createIcon(TablerIcon)
