/**
 * Auto-generated icon: IconCloudCode
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCloudCode as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCloudCode = createIcon(TablerIcon)
