/**
 * Auto-generated icon: IconChartFunnel
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconChartFunnel as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconChartFunnel = createIcon(TablerIcon)
