/**
 * Auto-generated icon: IconFireHydrantOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFireHydrantOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFireHydrantOff = createIcon(TablerIcon)
