/**
 * Auto-generated icon: IconBrandPatreon
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandPatreon as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandPatreon = createIcon(TablerIcon)
