/**
 * Auto-generated icon: IconCookieMan
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCookieMan as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCookieMan = createIcon(TablerIcon)
