/**
 * Auto-generated icon: IconMichelinStar
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMichelinStar as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMichelinStar = createIcon(TablerIcon)
