/**
 * Auto-generated icon: IconChevronUpRight
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconChevronUpRight as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconChevronUpRight = createIcon(TablerIcon)
