/**
 * Auto-generated icon: IconCurrencyBitcoin
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCurrencyBitcoin as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCurrencyBitcoin = createIcon(TablerIcon)
