/**
 * Auto-generated icon: IconRotate2
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRotate2 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRotate2 = createIcon(TablerIcon)
