/**
 * Auto-generated icon: IconFaceMask
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFaceMask as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFaceMask = createIcon(TablerIcon)
