/**
 * Auto-generated icon: IconCrutches
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCrutches as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCrutches = createIcon(TablerIcon)
