/**
 * Auto-generated icon: IconTextDirectionRtl
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTextDirectionRtl as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTextDirectionRtl = createIcon(TablerIcon)
