/**
 * Auto-generated icon: IconBoxSeam
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBoxSeam as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBoxSeam = createIcon(TablerIcon)
