/**
 * Auto-generated icon: IconMoodTongueWink
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMoodTongueWink as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMoodTongueWink = createIcon(TablerIcon)
