/**
 * Auto-generated icon: IconBellPin
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBellPin as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBellPin = createIcon(TablerIcon)
