/**
 * Auto-generated icon: IconPointer
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPointer as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPointer = createIcon(TablerIcon)
