/**
 * Auto-generated icon: IconBackspaceFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBackspaceFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBackspaceFilled = createIcon(TablerIcon)
