/**
 * Auto-generated icon: IconBoldOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBoldOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBoldOff = createIcon(TablerIcon)
