/**
 * Auto-generated icon: IconMapOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMapOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMapOff = createIcon(TablerIcon)
