/**
 * Auto-generated icon: IconTimelineEventExclamation
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTimelineEventExclamation as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTimelineEventExclamation = createIcon(TablerIcon)
