/**
 * Auto-generated icon: IconPentagonNumber3
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPentagonNumber3 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPentagonNumber3 = createIcon(TablerIcon)
