/**
 * Auto-generated icon: IconEaseInControlPointFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconEaseInControlPointFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconEaseInControlPointFilled = createIcon(TablerIcon)
