/**
 * Auto-generated icon: IconShoppingCartExclamation
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconShoppingCartExclamation as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconShoppingCartExclamation = createIcon(TablerIcon)
