/**
 * Auto-generated icon: IconDoorExit
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDoorExit as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDoorExit = createIcon(TablerIcon)
