/**
 * Auto-generated icon: IconFocus2
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFocus2 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFocus2 = createIcon(TablerIcon)
