/**
 * Auto-generated icon: IconViewfinder
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconViewfinder as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconViewfinder = createIcon(TablerIcon)
