/**
 * Auto-generated icon: IconCopyCheckFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCopyCheckFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCopyCheckFilled = createIcon(TablerIcon)
