/**
 * Auto-generated icon: IconNumber11
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNumber11 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNumber11 = createIcon(TablerIcon)
