/**
 * Auto-generated icon: IconPyramidPlus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPyramidPlus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPyramidPlus = createIcon(TablerIcon)
