/**
 * Auto-generated icon: IconArrowBadgeRightFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowBadgeRightFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowBadgeRightFilled = createIcon(TablerIcon)
