/**
 * Auto-generated icon: IconCircleDashedLetterC
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleDashedLetterC as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleDashedLetterC = createIcon(TablerIcon)
