/**
 * Auto-generated icon: IconShoppingCartSearch
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconShoppingCartSearch as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconShoppingCartSearch = createIcon(TablerIcon)
