/**
 * Auto-generated icon: IconMailOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMailOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMailOff = createIcon(TablerIcon)
