/**
 * Auto-generated icon: IconFolderOpen
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFolderOpen as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFolderOpen = createIcon(TablerIcon)
