/**
 * Auto-generated icon: IconBuildingMosque
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBuildingMosque as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBuildingMosque = createIcon(TablerIcon)
