/**
 * Auto-generated icon: IconArrowAutofitUp
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowAutofitUp as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowAutofitUp = createIcon(TablerIcon)
