/**
 * Auto-generated icon: IconChartColumn
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconChartColumn as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconChartColumn = createIcon(TablerIcon)
