/**
 * Auto-generated icon: IconHierarchy
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHierarchy as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHierarchy = createIcon(TablerIcon)
