/**
 * Auto-generated icon: IconChevronCompactDown
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconChevronCompactDown as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconChevronCompactDown = createIcon(TablerIcon)
