/**
 * Auto-generated icon: IconHomeRibbon
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHomeRibbon as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHomeRibbon = createIcon(TablerIcon)
