/**
 * Auto-generated icon: IconWash
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconWash as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconWash = createIcon(TablerIcon)
