/**
 * Auto-generated icon: IconCurrencyLyd
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCurrencyLyd as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCurrencyLyd = createIcon(TablerIcon)
