/**
 * Auto-generated icon: IconVocabulary
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconVocabulary as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconVocabulary = createIcon(TablerIcon)
