/**
 * Auto-generated icon: IconBracketsOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBracketsOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBracketsOff = createIcon(TablerIcon)
