/**
 * Auto-generated icon: IconCircleLetterQ
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleLetterQ as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleLetterQ = createIcon(TablerIcon)
