/**
 * Auto-generated icon: IconSquareRoundedNumber8
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareRoundedNumber8 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareRoundedNumber8 = createIcon(TablerIcon)
