/**
 * Auto-generated icon: IconCloudLock
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCloudLock as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCloudLock = createIcon(TablerIcon)
