/**
 * Auto-generated icon: IconShieldCheckered
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconShieldCheckered as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconShieldCheckered = createIcon(TablerIcon)
