/**
 * Auto-generated icon: IconArrowsTransferDown
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowsTransferDown as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowsTransferDown = createIcon(TablerIcon)
