/**
 * Auto-generated icon: IconSql
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSql as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSql = createIcon(TablerIcon)
