/**
 * Auto-generated icon: IconCirclePercentage
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCirclePercentage as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCirclePercentage = createIcon(TablerIcon)
