/**
 * Auto-generated icon: IconFileZip
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileZip as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileZip = createIcon(TablerIcon)
