/**
 * Auto-generated icon: IconTrophy
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTrophy as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTrophy = createIcon(TablerIcon)
