/**
 * Auto-generated icon: IconBoxMultiple5
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBoxMultiple5 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBoxMultiple5 = createIcon(TablerIcon)
