/**
 * Auto-generated icon: IconStairsDown
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconStairsDown as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconStairsDown = createIcon(TablerIcon)
