/**
 * Auto-generated icon: IconBlob
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBlob as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBlob = createIcon(TablerIcon)
