/**
 * Auto-generated icon: IconMailboxOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMailboxOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMailboxOff = createIcon(TablerIcon)
