/**
 * Auto-generated icon: IconAuth2fa
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAuth2fa as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAuth2fa = createIcon(TablerIcon)
