/**
 * Auto-generated icon: IconMoodNeutral
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMoodNeutral as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMoodNeutral = createIcon(TablerIcon)
