/**
 * Auto-generated icon: IconLogout2
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLogout2 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLogout2 = createIcon(TablerIcon)
