/**
 * Auto-generated icon: IconSpadeFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSpadeFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSpadeFilled = createIcon(TablerIcon)
