/**
 * Auto-generated icon: IconBrandFlutter
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandFlutter as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandFlutter = createIcon(TablerIcon)
