/**
 * Auto-generated icon: IconBrandNytimes
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandNytimes as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandNytimes = createIcon(TablerIcon)
