/**
 * Auto-generated icon: IconUnderline
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconUnderline as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconUnderline = createIcon(TablerIcon)
