/**
 * Auto-generated icon: IconDeviceDesktopShare
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceDesktopShare as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceDesktopShare = createIcon(TablerIcon)
