/**
 * Auto-generated icon: IconFunctionFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFunctionFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFunctionFilled = createIcon(TablerIcon)
