/**
 * Auto-generated icon: IconBrandCake
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandCake as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandCake = createIcon(TablerIcon)
