/**
 * Auto-generated icon: IconLayersIntersect
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLayersIntersect as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLayersIntersect = createIcon(TablerIcon)
