/**
 * Auto-generated icon: IconBadgeHdFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBadgeHdFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBadgeHdFilled = createIcon(TablerIcon)
