/**
 * Auto-generated icon: IconClockHour4Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconClockHour4Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconClockHour4Filled = createIcon(TablerIcon)
