/**
 * Auto-generated icon: IconFileCodeFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileCodeFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileCodeFilled = createIcon(TablerIcon)
