/**
 * Auto-generated icon: IconAlbum
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAlbum as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAlbum = createIcon(TablerIcon)
