/**
 * Auto-generated icon: IconWindElectricity
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconWindElectricity as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconWindElectricity = createIcon(TablerIcon)
