/**
 * Auto-generated icon: IconMessageCircleCog
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMessageCircleCog as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMessageCircleCog = createIcon(TablerIcon)
