/**
 * Auto-generated icon: IconBuildingAirport
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBuildingAirport as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBuildingAirport = createIcon(TablerIcon)
