/**
 * Auto-generated icon: IconMapPinMinus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMapPinMinus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMapPinMinus = createIcon(TablerIcon)
