/**
 * Auto-generated icon: IconCircuitResistor
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircuitResistor as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircuitResistor = createIcon(TablerIcon)
