/**
 * Auto-generated icon: IconMessageCircleShare
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMessageCircleShare as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMessageCircleShare = createIcon(TablerIcon)
