/**
 * Auto-generated icon: IconFaceIdError
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFaceIdError as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFaceIdError = createIcon(TablerIcon)
