/**
 * Auto-generated icon: IconAlignRight2
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAlignRight2 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAlignRight2 = createIcon(TablerIcon)
