/**
 * Auto-generated icon: IconBrandBitbucket
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandBitbucket as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandBitbucket = createIcon(TablerIcon)
