/**
 * Auto-generated icon: IconCircleArrowUpLeftFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleArrowUpLeftFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleArrowUpLeftFilled = createIcon(TablerIcon)
