/**
 * Auto-generated icon: IconBrandAppleArcade
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandAppleArcade as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandAppleArcade = createIcon(TablerIcon)
