/**
 * Auto-generated icon: IconLogs
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLogs as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLogs = createIcon(TablerIcon)
