/**
 * Auto-generated icon: IconArrowsLeft
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowsLeft as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowsLeft = createIcon(TablerIcon)
