/**
 * Auto-generated icon: IconMathCtg
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMathCtg as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMathCtg = createIcon(TablerIcon)
