/**
 * Auto-generated icon: IconDatabasePlus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDatabasePlus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDatabasePlus = createIcon(TablerIcon)
