/**
 * Auto-generated icon: IconXboxY
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconXboxY as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconXboxY = createIcon(TablerIcon)
