/**
 * Auto-generated icon: IconSignal6g
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSignal6g as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSignal6g = createIcon(TablerIcon)
