/**
 * Auto-generated icon: IconArrowMergeBoth
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowMergeBoth as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowMergeBoth = createIcon(TablerIcon)
