/**
 * Auto-generated icon: IconNumber73Small
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNumber73Small as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNumber73Small = createIcon(TablerIcon)
