/**
 * Auto-generated icon: IconFileXFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileXFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileXFilled = createIcon(TablerIcon)
