/**
 * Auto-generated icon: IconMotorbikeFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMotorbikeFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMotorbikeFilled = createIcon(TablerIcon)
