/**
 * Auto-generated icon: IconArrowMoveLeft
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowMoveLeft as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowMoveLeft = createIcon(TablerIcon)
