/**
 * Auto-generated icon: IconCampfire
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCampfire as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCampfire = createIcon(TablerIcon)
