/**
 * Auto-generated icon: IconBrushOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrushOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrushOff = createIcon(TablerIcon)
