/**
 * Auto-generated icon: IconClearAll
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconClearAll as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconClearAll = createIcon(TablerIcon)
