/**
 * Auto-generated icon: IconArrowsDiagonalMinimize
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowsDiagonalMinimize as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowsDiagonalMinimize = createIcon(TablerIcon)
