/**
 * Auto-generated icon: IconAlignLeft
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAlignLeft as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAlignLeft = createIcon(TablerIcon)
