/**
 * Auto-generated icon: IconGenderNeutrois
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconGenderNeutrois as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconGenderNeutrois = createIcon(TablerIcon)
