/**
 * Auto-generated icon: IconShoppingCartCode
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconShoppingCartCode as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconShoppingCartCode = createIcon(TablerIcon)
