/**
 * Auto-generated icon: IconStarFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconStarFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconStarFilled = createIcon(TablerIcon)
