/**
 * Auto-generated icon: IconCircuitBattery
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircuitBattery as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircuitBattery = createIcon(TablerIcon)
