/**
 * Auto-generated icon: IconCashBanknoteFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCashBanknoteFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCashBanknoteFilled = createIcon(TablerIcon)
