/**
 * Auto-generated icon: IconBrowserX
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrowserX as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrowserX = createIcon(TablerIcon)
