/**
 * Auto-generated icon: IconCloudRain
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCloudRain as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCloudRain = createIcon(TablerIcon)
