/**
 * Auto-generated icon: IconFiles
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFiles as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFiles = createIcon(TablerIcon)
