/**
 * Auto-generated icon: IconSquareF7
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareF7 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareF7 = createIcon(TablerIcon)
