/**
 * Auto-generated icon: IconCircleDottedLetterL
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleDottedLetterL as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleDottedLetterL = createIcon(TablerIcon)
