/**
 * Auto-generated icon: IconColorFilter
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconColorFilter as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconColorFilter = createIcon(TablerIcon)
