/**
 * Auto-generated icon: IconIkosaedr
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconIkosaedr as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconIkosaedr = createIcon(TablerIcon)
