/**
 * Auto-generated icon: IconCalendarSmile
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCalendarSmile as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCalendarSmile = createIcon(TablerIcon)
