/**
 * Auto-generated icon: IconCircle5
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircle5 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircle5 = createIcon(TablerIcon)
