/**
 * Auto-generated icon: IconUserBitcoin
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconUserBitcoin as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconUserBitcoin = createIcon(TablerIcon)
