/**
 * Auto-generated icon: IconRuler
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRuler as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRuler = createIcon(TablerIcon)
