/**
 * Auto-generated icon: IconWashDry2
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconWashDry2 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconWashDry2 = createIcon(TablerIcon)
