/**
 * Auto-generated icon: IconShoppingCartFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconShoppingCartFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconShoppingCartFilled = createIcon(TablerIcon)
