/**
 * Auto-generated icon: IconClockQuestion
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconClockQuestion as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconClockQuestion = createIcon(TablerIcon)
