/**
 * Auto-generated icon: IconCircleDottedLetterB
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleDottedLetterB as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleDottedLetterB = createIcon(TablerIcon)
