/**
 * Auto-generated icon: IconTextPlus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTextPlus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTextPlus = createIcon(TablerIcon)
