/**
 * Auto-generated icon: IconFileEuroFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileEuroFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileEuroFilled = createIcon(TablerIcon)
