/**
 * Auto-generated icon: IconSquareLetterJFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareLetterJFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareLetterJFilled = createIcon(TablerIcon)
