/**
 * Auto-generated icon: IconFileSymlink
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileSymlink as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileSymlink = createIcon(TablerIcon)
