/**
 * Auto-generated icon: IconLockSquare
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLockSquare as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLockSquare = createIcon(TablerIcon)
