/**
 * Auto-generated icon: IconClick
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconClick as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconClick = createIcon(TablerIcon)
