/**
 * Auto-generated icon: IconDiaboloOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDiaboloOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDiaboloOff = createIcon(TablerIcon)
