/**
 * Auto-generated icon: IconReceiptBitcoin
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconReceiptBitcoin as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconReceiptBitcoin = createIcon(TablerIcon)
