/**
 * Auto-generated icon: IconTextWrap
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTextWrap as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTextWrap = createIcon(TablerIcon)
