/**
 * Auto-generated icon: IconFlagCancel
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFlagCancel as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFlagCancel = createIcon(TablerIcon)
