/**
 * Auto-generated icon: IconRecycle
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRecycle as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRecycle = createIcon(TablerIcon)
