/**
 * Auto-generated icon: IconTableImport
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTableImport as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTableImport = createIcon(TablerIcon)
