/**
 * Auto-generated icon: IconAddressBookOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAddressBookOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAddressBookOff = createIcon(TablerIcon)
