/**
 * Auto-generated icon: IconFileTypeJpg
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileTypeJpg as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileTypeJpg = createIcon(TablerIcon)
