/**
 * Auto-generated icon: IconMusicBolt
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMusicBolt as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMusicBolt = createIcon(TablerIcon)
