/**
 * Auto-generated icon: IconFlagBitcoin
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFlagBitcoin as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFlagBitcoin = createIcon(TablerIcon)
