/**
 * Auto-generated icon: IconMailDown
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMailDown as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMailDown = createIcon(TablerIcon)
