/**
 * Auto-generated icon: IconSquareRoundedLetterHFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareRoundedLetterHFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareRoundedLetterHFilled = createIcon(TablerIcon)
