/**
 * Auto-generated icon: IconRulerOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRulerOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRulerOff = createIcon(TablerIcon)
