/**
 * Auto-generated icon: IconUfoOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconUfoOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconUfoOff = createIcon(TablerIcon)
