/**
 * Auto-generated icon: IconTestPipe
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTestPipe as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTestPipe = createIcon(TablerIcon)
