/**
 * Auto-generated icon: IconCoinPoundFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCoinPoundFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCoinPoundFilled = createIcon(TablerIcon)
