/**
 * Auto-generated icon: IconDiscOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDiscOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDiscOff = createIcon(TablerIcon)
