/**
 * Auto-generated icon: IconMailOpenedFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMailOpenedFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMailOpenedFilled = createIcon(TablerIcon)
