/**
 * Auto-generated icon: IconCircleDashedLetterS
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleDashedLetterS as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleDashedLetterS = createIcon(TablerIcon)
