/**
 * Auto-generated icon: IconAccessibleFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAccessibleFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAccessibleFilled = createIcon(TablerIcon)
