/**
 * Auto-generated icon: IconTagPlus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTagPlus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTagPlus = createIcon(TablerIcon)
