/**
 * Auto-generated icon: IconSquareArrowDown
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareArrowDown as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareArrowDown = createIcon(TablerIcon)
