/**
 * Auto-generated icon: IconArrowBearLeft
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowBearLeft as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowBearLeft = createIcon(TablerIcon)
