/**
 * Auto-generated icon: IconPhotoPin
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPhotoPin as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPhotoPin = createIcon(TablerIcon)
