/**
 * Auto-generated icon: IconPhotoPause
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPhotoPause as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPhotoPause = createIcon(TablerIcon)
