/**
 * Auto-generated icon: IconUserPin
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconUserPin as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconUserPin = createIcon(TablerIcon)
