/**
 * Auto-generated icon: IconMeat
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMeat as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMeat = createIcon(TablerIcon)
