/**
 * Auto-generated icon: IconNumber39Small
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNumber39Small as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNumber39Small = createIcon(TablerIcon)
