/**
 * Auto-generated icon: IconMusicSearch
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMusicSearch as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMusicSearch = createIcon(TablerIcon)
