/**
 * Auto-generated icon: IconZoomExclamation
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconZoomExclamation as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconZoomExclamation = createIcon(TablerIcon)
