/**
 * Auto-generated icon: IconFreezeRow
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFreezeRow as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFreezeRow = createIcon(TablerIcon)
