/**
 * Auto-generated icon: IconConfetti
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconConfetti as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconConfetti = createIcon(TablerIcon)
