/**
 * Auto-generated icon: IconCurrencyDollarOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCurrencyDollarOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCurrencyDollarOff = createIcon(TablerIcon)
