/**
 * Auto-generated icon: IconBellPlus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBellPlus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBellPlus = createIcon(TablerIcon)
