/**
 * Auto-generated icon: IconMapPin2
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMapPin2 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMapPin2 = createIcon(TablerIcon)
