/**
 * Auto-generated icon: IconWashTemperature1
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconWashTemperature1 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconWashTemperature1 = createIcon(TablerIcon)
