/**
 * Auto-generated icon: IconBrandCtemplar
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandCtemplar as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandCtemplar = createIcon(TablerIcon)
