/**
 * Auto-generated icon: IconArrowBigLeftFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowBigLeftFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowBigLeftFilled = createIcon(TablerIcon)
