/**
 * Auto-generated icon: IconCashBanknote
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCashBanknote as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCashBanknote = createIcon(TablerIcon)
