/**
 * Auto-generated icon: IconWritingFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconWritingFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconWritingFilled = createIcon(TablerIcon)
