/**
 * Auto-generated icon: IconPhotoSearch
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPhotoSearch as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPhotoSearch = createIcon(TablerIcon)
