/**
 * Auto-generated icon: IconZoomInArea
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconZoomInArea as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconZoomInArea = createIcon(TablerIcon)
