/**
 * Auto-generated icon: IconBorderOuter
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBorderOuter as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBorderOuter = createIcon(TablerIcon)
