/**
 * Auto-generated icon: IconDeviceMobileUp
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceMobileUp as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceMobileUp = createIcon(TablerIcon)
