/**
 * Auto-generated icon: IconApiAppOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconApiAppOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconApiAppOff = createIcon(TablerIcon)
