/**
 * Auto-generated icon: IconArrowBigLeftLinesFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowBigLeftLinesFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowBigLeftLinesFilled = createIcon(TablerIcon)
