/**
 * Auto-generated icon: IconBrandMiniprogram
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandMiniprogram as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandMiniprogram = createIcon(TablerIcon)
