/**
 * Auto-generated icon: IconMoodNervous
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMoodNervous as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMoodNervous = createIcon(TablerIcon)
