/**
 * Auto-generated icon: IconTipJar
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTipJar as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTipJar = createIcon(TablerIcon)
