/**
 * Auto-generated icon: IconAlertSmall
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAlertSmall as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAlertSmall = createIcon(TablerIcon)
