/**
 * Auto-generated icon: IconShieldHalfFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconShieldHalfFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconShieldHalfFilled = createIcon(TablerIcon)
