/**
 * Auto-generated icon: IconBrandWalmart
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandWalmart as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandWalmart = createIcon(TablerIcon)
