/**
 * Auto-generated icon: IconBowlSpoon
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBowlSpoon as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBowlSpoon = createIcon(TablerIcon)
