/**
 * Auto-generated icon: IconPaw
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPaw as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPaw = createIcon(TablerIcon)
