/**
 * Auto-generated icon: IconArrowMoveDown
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowMoveDown as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowMoveDown = createIcon(TablerIcon)
