/**
 * Auto-generated icon: IconBrandWechat
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandWechat as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandWechat = createIcon(TablerIcon)
