/**
 * Auto-generated icon: IconExclamationMarkOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconExclamationMarkOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconExclamationMarkOff = createIcon(TablerIcon)
