/**
 * Auto-generated icon: IconApi
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconApi as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconApi = createIcon(TablerIcon)
