/**
 * Auto-generated icon: IconDropletCode
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDropletCode as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDropletCode = createIcon(TablerIcon)
