/**
 * Auto-generated icon: IconSquareRoundedLetterXFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareRoundedLetterXFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareRoundedLetterXFilled = createIcon(TablerIcon)
