/**
 * Auto-generated icon: IconCurrencySom
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCurrencySom as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCurrencySom = createIcon(TablerIcon)
