/**
 * Auto-generated icon: IconUserHeart
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconUserHeart as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconUserHeart = createIcon(TablerIcon)
