/**
 * Auto-generated icon: IconAlignBoxTopRight
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAlignBoxTopRight as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAlignBoxTopRight = createIcon(TablerIcon)
