/**
 * Auto-generated icon: IconGrid4x4
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconGrid4x4 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconGrid4x4 = createIcon(TablerIcon)
