/**
 * Auto-generated icon: IconPhotoScan
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPhotoScan as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPhotoScan = createIcon(TablerIcon)
