/**
 * Auto-generated icon: IconPlaylistOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPlaylistOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPlaylistOff = createIcon(TablerIcon)
