/**
 * Auto-generated icon: IconBrandEtsy
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandEtsy as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandEtsy = createIcon(TablerIcon)
