/**
 * Auto-generated icon: IconEyeTableFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconEyeTableFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconEyeTableFilled = createIcon(TablerIcon)
