/**
 * Auto-generated icon: IconGizmo
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconGizmo as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconGizmo = createIcon(TablerIcon)
