/**
 * Auto-generated icon: IconAppWindowFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAppWindowFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAppWindowFilled = createIcon(TablerIcon)
