/**
 * Auto-generated icon: IconDevicesPc
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDevicesPc as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDevicesPc = createIcon(TablerIcon)
