/**
 * Auto-generated icon: IconABOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconABOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconABOff = createIcon(TablerIcon)
