/**
 * Auto-generated icon: IconDeviceCameraPhone
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceCameraPhone as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceCameraPhone = createIcon(TablerIcon)
