/**
 * Auto-generated icon: IconBrandAmongUs
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandAmongUs as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandAmongUs = createIcon(TablerIcon)
