/**
 * Auto-generated icon: IconBrandDenodo
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandDenodo as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandDenodo = createIcon(TablerIcon)
