/**
 * Auto-generated icon: IconBrandPaypay
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandPaypay as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandPaypay = createIcon(TablerIcon)
