/**
 * Auto-generated icon: IconHttpGet
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHttpGet as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHttpGet = createIcon(TablerIcon)
