/**
 * Auto-generated icon: IconUsersMinus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconUsersMinus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconUsersMinus = createIcon(TablerIcon)
