/**
 * Auto-generated icon: IconColorPickerOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconColorPickerOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconColorPickerOff = createIcon(TablerIcon)
