/**
 * Auto-generated icon: IconRegisteredFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRegisteredFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRegisteredFilled = createIcon(TablerIcon)
