/**
 * Auto-generated icon: IconSquareLetterKFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareLetterKFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareLetterKFilled = createIcon(TablerIcon)
