/**
 * Auto-generated icon: IconScreenShare
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconScreenShare as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconScreenShare = createIcon(TablerIcon)
