/**
 * Auto-generated icon: IconTrademark
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTrademark as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTrademark = createIcon(TablerIcon)
