/**
 * Auto-generated icon: IconAntennaBarsOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAntennaBarsOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAntennaBarsOff = createIcon(TablerIcon)
