/**
 * Auto-generated icon: IconShieldFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconShieldFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconShieldFilled = createIcon(TablerIcon)
