/**
 * Auto-generated icon: IconEscalatorDownFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconEscalatorDownFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconEscalatorDownFilled = createIcon(TablerIcon)
