/**
 * Auto-generated icon: IconPennant2
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPennant2 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPennant2 = createIcon(TablerIcon)
