/**
 * Auto-generated icon: IconBasketHeart
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBasketHeart as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBasketHeart = createIcon(TablerIcon)
