/**
 * Auto-generated icon: IconTruckReturn
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTruckReturn as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTruckReturn = createIcon(TablerIcon)
