/**
 * Auto-generated icon: IconRadioactive
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRadioactive as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRadioactive = createIcon(TablerIcon)
