/**
 * Auto-generated icon: IconCornerDownLeft
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCornerDownLeft as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCornerDownLeft = createIcon(TablerIcon)
