/**
 * Auto-generated icon: IconFileScissorsFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileScissorsFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileScissorsFilled = createIcon(TablerIcon)
