/**
 * Auto-generated icon: IconCopyPlus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCopyPlus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCopyPlus = createIcon(TablerIcon)
