/**
 * Auto-generated icon: IconCodeVariable
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCodeVariable as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCodeVariable = createIcon(TablerIcon)
