/**
 * Auto-generated icon: IconArrowWaveLeftDown
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowWaveLeftDown as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowWaveLeftDown = createIcon(TablerIcon)
