/**
 * Auto-generated icon: IconPinned
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPinned as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPinned = createIcon(TablerIcon)
