/**
 * Auto-generated icon: IconArrowBigLeftLines
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowBigLeftLines as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowBigLeftLines = createIcon(TablerIcon)
