/**
 * Auto-generated icon: IconNumber68Small
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNumber68Small as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNumber68Small = createIcon(TablerIcon)
