/**
 * Auto-generated icon: IconNotes
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNotes as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNotes = createIcon(TablerIcon)
