/**
 * Auto-generated icon: IconWriting
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconWriting as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconWriting = createIcon(TablerIcon)
