/**
 * Auto-generated icon: IconSortAscending2Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSortAscending2Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSortAscending2Filled = createIcon(TablerIcon)
