/**
 * Auto-generated icon: IconCircleLetterT
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleLetterT as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleLetterT = createIcon(TablerIcon)
