/**
 * Auto-generated icon: IconCar4wdFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCar4wdFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCar4wdFilled = createIcon(TablerIcon)
