/**
 * Auto-generated icon: IconArrowBigRightLinesFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowBigRightLinesFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowBigRightLinesFilled = createIcon(TablerIcon)
