/**
 * Auto-generated icon: IconFilesOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFilesOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFilesOff = createIcon(TablerIcon)
