/**
 * Auto-generated icon: IconSTurnUp
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSTurnUp as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSTurnUp = createIcon(TablerIcon)
