/**
 * Auto-generated icon: IconExchangeFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconExchangeFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconExchangeFilled = createIcon(TablerIcon)
