/**
 * Auto-generated icon: IconClockHour12
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconClockHour12 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconClockHour12 = createIcon(TablerIcon)
