/**
 * Auto-generated icon: IconBurger
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBurger as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBurger = createIcon(TablerIcon)
