/**
 * Auto-generated icon: IconArrowRoundaboutRight
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowRoundaboutRight as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowRoundaboutRight = createIcon(TablerIcon)
