/**
 * Auto-generated icon: IconBrandFlickr
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandFlickr as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandFlickr = createIcon(TablerIcon)
