/**
 * Auto-generated icon: IconEggFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconEggFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconEggFilled = createIcon(TablerIcon)
