/**
 * Auto-generated icon: IconBrandLinktree
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandLinktree as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandLinktree = createIcon(TablerIcon)
