/**
 * Auto-generated icon: IconArrowLeftSquareFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowLeftSquareFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowLeftSquareFilled = createIcon(TablerIcon)
