/**
 * Auto-generated icon: IconArrowsUp
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowsUp as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowsUp = createIcon(TablerIcon)
