/**
 * Auto-generated icon: IconTimezone
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTimezone as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTimezone = createIcon(TablerIcon)
