/**
 * Auto-generated icon: IconSteam
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSteam as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSteam = createIcon(TablerIcon)
