/**
 * Auto-generated icon: IconDeviceIpadHorizontalSearch
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceIpadHorizontalSearch as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceIpadHorizontalSearch = createIcon(TablerIcon)
