/**
 * Auto-generated icon: IconShape
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconShape as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconShape = createIcon(TablerIcon)
