/**
 * Auto-generated icon: IconShoeOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconShoeOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconShoeOff = createIcon(TablerIcon)
