/**
 * Auto-generated icon: IconAppsFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAppsFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAppsFilled = createIcon(TablerIcon)
