/**
 * Auto-generated icon: IconFilePower
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFilePower as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFilePower = createIcon(TablerIcon)
