/**
 * Auto-generated icon: IconHexagonLetterU
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHexagonLetterU as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHexagonLetterU = createIcon(TablerIcon)
