/**
 * Auto-generated icon: IconOlympics
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconOlympics as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconOlympics = createIcon(TablerIcon)
