/**
 * Auto-generated icon: IconWashDry3
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconWashDry3 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconWashDry3 = createIcon(TablerIcon)
