/**
 * Auto-generated icon: IconTransitionRight
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTransitionRight as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTransitionRight = createIcon(TablerIcon)
