/**
 * Auto-generated icon: IconBarcodeOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBarcodeOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBarcodeOff = createIcon(TablerIcon)
