/**
 * Auto-generated icon: IconBuildingBroadcastTower
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBuildingBroadcastTower as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBuildingBroadcastTower = createIcon(TablerIcon)
