/**
 * Auto-generated icon: IconBattery1Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBattery1Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBattery1Filled = createIcon(TablerIcon)
