/**
 * Auto-generated icon: IconShieldShare
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconShieldShare as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconShieldShare = createIcon(TablerIcon)
