/**
 * Auto-generated icon: IconSeparator
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSeparator as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSeparator = createIcon(TablerIcon)
