/**
 * Auto-generated icon: IconBlenderFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBlenderFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBlenderFilled = createIcon(TablerIcon)
