/**
 * Auto-generated icon: IconLockOpen
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLockOpen as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLockOpen = createIcon(TablerIcon)
