/**
 * Auto-generated icon: IconHexagonMinus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHexagonMinus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHexagonMinus = createIcon(TablerIcon)
