/**
 * Auto-generated icon: IconCodeCircle
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCodeCircle as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCodeCircle = createIcon(TablerIcon)
