/**
 * Auto-generated icon: IconBrandStackoverflow
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandStackoverflow as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandStackoverflow = createIcon(TablerIcon)
