/**
 * Auto-generated icon: IconChartCovariate
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconChartCovariate as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconChartCovariate = createIcon(TablerIcon)
