/**
 * Auto-generated icon: IconGlassFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconGlassFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconGlassFilled = createIcon(TablerIcon)
