/**
 * Auto-generated icon: IconSquareLetterX
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareLetterX as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareLetterX = createIcon(TablerIcon)
