/**
 * Auto-generated icon: IconMistOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMistOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMistOff = createIcon(TablerIcon)
