/**
 * Auto-generated icon: IconPentagonNumber0
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPentagonNumber0 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPentagonNumber0 = createIcon(TablerIcon)
