/**
 * Auto-generated icon: IconFishBoneFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFishBoneFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFishBoneFilled = createIcon(TablerIcon)
