/**
 * Auto-generated icon: IconBrandTailwind
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandTailwind as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandTailwind = createIcon(TablerIcon)
