/**
 * Auto-generated icon: IconFenceOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFenceOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFenceOff = createIcon(TablerIcon)
