/**
 * Auto-generated icon: IconCast
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCast as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCast = createIcon(TablerIcon)
