/**
 * Auto-generated icon: IconHelpSquareRoundedFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHelpSquareRoundedFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHelpSquareRoundedFilled = createIcon(TablerIcon)
