/**
 * Auto-generated icon: IconDna2Off
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDna2Off as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDna2Off = createIcon(TablerIcon)
