/**
 * Auto-generated icon: IconAlertTriangleOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAlertTriangleOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAlertTriangleOff = createIcon(TablerIcon)
