/**
 * Auto-generated icon: IconDeviceCctvOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceCctvOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceCctvOff = createIcon(TablerIcon)
