/**
 * Auto-generated icon: IconAntennaBars2
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAntennaBars2 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAntennaBars2 = createIcon(TablerIcon)
