/**
 * Auto-generated icon: IconSquareNumber0
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareNumber0 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareNumber0 = createIcon(TablerIcon)
