/**
 * Auto-generated icon: IconPlaneDeparture
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPlaneDeparture as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPlaneDeparture = createIcon(TablerIcon)
