/**
 * Auto-generated icon: IconSandbox
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSandbox as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSandbox = createIcon(TablerIcon)
