/**
 * Auto-generated icon: IconClockDown
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconClockDown as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconClockDown = createIcon(TablerIcon)
