/**
 * Auto-generated icon: IconMoped
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMoped as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMoped = createIcon(TablerIcon)
