/**
 * Auto-generated icon: IconUniverse
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconUniverse as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconUniverse = createIcon(TablerIcon)
