/**
 * Auto-generated icon: IconNumber0
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNumber0 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNumber0 = createIcon(TablerIcon)
