/**
 * Auto-generated icon: IconRosetteNumber7
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRosetteNumber7 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRosetteNumber7 = createIcon(TablerIcon)
