/**
 * Auto-generated icon: IconEyePause
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconEyePause as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconEyePause = createIcon(TablerIcon)
