/**
 * Auto-generated icon: IconDirectionSignOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDirectionSignOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDirectionSignOff = createIcon(TablerIcon)
