/**
 * Auto-generated icon: IconDeviceProjector
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceProjector as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceProjector = createIcon(TablerIcon)
