/**
 * Auto-generated icon: IconSquareRoundedLetterF
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareRoundedLetterF as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareRoundedLetterF = createIcon(TablerIcon)
