/**
 * Auto-generated icon: IconBuildingSkyscraper
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBuildingSkyscraper as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBuildingSkyscraper = createIcon(TablerIcon)
