/**
 * Auto-generated icon: IconBrandBandlab
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandBandlab as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandBandlab = createIcon(TablerIcon)
