/**
 * Auto-generated icon: IconCircleChevronsUpFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleChevronsUpFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleChevronsUpFilled = createIcon(TablerIcon)
