/**
 * Auto-generated icon: IconEyeglass2Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconEyeglass2Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconEyeglass2Filled = createIcon(TablerIcon)
