/**
 * Auto-generated icon: IconFileChart
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileChart as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileChart = createIcon(TablerIcon)
