/**
 * Auto-generated icon: IconFolderCheck
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFolderCheck as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFolderCheck = createIcon(TablerIcon)
