/**
 * Auto-generated icon: IconNavigationDiscount
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNavigationDiscount as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNavigationDiscount = createIcon(TablerIcon)
