/**
 * Auto-generated icon: IconCalculatorFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCalculatorFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCalculatorFilled = createIcon(TablerIcon)
