/**
 * Auto-generated icon: IconHammer
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHammer as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHammer = createIcon(TablerIcon)
