/**
 * Auto-generated icon: IconSquareRoundedLetterW
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareRoundedLetterW as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareRoundedLetterW = createIcon(TablerIcon)
