/**
 * Auto-generated icon: IconCashMove
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCashMove as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCashMove = createIcon(TablerIcon)
