/**
 * Auto-generated icon: IconAlarmFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAlarmFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAlarmFilled = createIcon(TablerIcon)
