/**
 * Auto-generated icon: IconFilter2Question
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFilter2Question as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFilter2Question = createIcon(TablerIcon)
