/**
 * Auto-generated icon: IconAlignBoxTopLeft
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAlignBoxTopLeft as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAlignBoxTopLeft = createIcon(TablerIcon)
