/**
 * Auto-generated icon: IconMathXPlusX
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMathXPlusX as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMathXPlusX = createIcon(TablerIcon)
