/**
 * Auto-generated icon: IconExplicitFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconExplicitFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconExplicitFilled = createIcon(TablerIcon)
