/**
 * Auto-generated icon: IconKeyframeAlignVertical
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconKeyframeAlignVertical as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconKeyframeAlignVertical = createIcon(TablerIcon)
