/**
 * Auto-generated icon: IconCapsuleHorizontal
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCapsuleHorizontal as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCapsuleHorizontal = createIcon(TablerIcon)
