/**
 * Auto-generated icon: IconBasketDown
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBasketDown as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBasketDown = createIcon(TablerIcon)
