/**
 * Auto-generated icon: IconChevronsDown
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconChevronsDown as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconChevronsDown = createIcon(TablerIcon)
