/**
 * Auto-generated icon: IconRating16Plus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRating16Plus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRating16Plus = createIcon(TablerIcon)
