/**
 * Auto-generated icon: IconHexagon6
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHexagon6 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHexagon6 = createIcon(TablerIcon)
