/**
 * Auto-generated icon: IconEscalator
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconEscalator as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconEscalator = createIcon(TablerIcon)
