/**
 * Auto-generated icon: IconArrowRampLeft2
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowRampLeft2 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowRampLeft2 = createIcon(TablerIcon)
