/**
 * Auto-generated icon: IconTopologyComplex
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTopologyComplex as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTopologyComplex = createIcon(TablerIcon)
