/**
 * Auto-generated icon: IconNumber84Small
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNumber84Small as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNumber84Small = createIcon(TablerIcon)
