/**
 * Auto-generated icon: IconBrandSharik
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandSharik as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandSharik = createIcon(TablerIcon)
