/**
 * Auto-generated icon: IconWorldLongitude
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconWorldLongitude as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconWorldLongitude = createIcon(TablerIcon)
