/**
 * Auto-generated icon: IconHexagonLetterBFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHexagonLetterBFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHexagonLetterBFilled = createIcon(TablerIcon)
