/**
 * Auto-generated icon: IconRotateDot
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRotateDot as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRotateDot = createIcon(TablerIcon)
