/**
 * Auto-generated icon: IconChevronCompactLeft
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconChevronCompactLeft as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconChevronCompactLeft = createIcon(TablerIcon)
