/**
 * Auto-generated icon: IconSquareLetterLFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareLetterLFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareLetterLFilled = createIcon(TablerIcon)
