/**
 * Auto-generated icon: IconMathSymbols
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMathSymbols as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMathSymbols = createIcon(TablerIcon)
