/**
 * Auto-generated icon: IconSquareRoundedLetterTFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareRoundedLetterTFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareRoundedLetterTFilled = createIcon(TablerIcon)
