/**
 * Auto-generated icon: IconCashEdit
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCashEdit as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCashEdit = createIcon(TablerIcon)
