/**
 * Auto-generated icon: IconCircleDottedLetterX
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleDottedLetterX as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleDottedLetterX = createIcon(TablerIcon)
