/**
 * Auto-generated icon: IconDeviceMobileShare
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceMobileShare as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceMobileShare = createIcon(TablerIcon)
