/**
 * Auto-generated icon: IconCopyOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCopyOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCopyOff = createIcon(TablerIcon)
