/**
 * Auto-generated icon: IconShieldPause
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconShieldPause as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconShieldPause = createIcon(TablerIcon)
