/**
 * Auto-generated icon: IconHeartBrokenFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHeartBrokenFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHeartBrokenFilled = createIcon(TablerIcon)
