/**
 * Auto-generated icon: IconArrowsDownUp
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowsDownUp as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowsDownUp = createIcon(TablerIcon)
