/**
 * Auto-generated icon: IconLayersOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLayersOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLayersOff = createIcon(TablerIcon)
