/**
 * Auto-generated icon: IconLibraryPlusFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLibraryPlusFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLibraryPlusFilled = createIcon(TablerIcon)
