/**
 * Auto-generated icon: IconSquareLetterPFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareLetterPFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareLetterPFilled = createIcon(TablerIcon)
