/**
 * Auto-generated icon: IconBrandPaypalFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandPaypalFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandPaypalFilled = createIcon(TablerIcon)
