/**
 * Auto-generated icon: IconCashRegister
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCashRegister as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCashRegister = createIcon(TablerIcon)
