/**
 * Auto-generated icon: IconArrowIteration
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowIteration as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowIteration = createIcon(TablerIcon)
