/**
 * Auto-generated icon: IconCurrencyAfghani
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCurrencyAfghani as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCurrencyAfghani = createIcon(TablerIcon)
