/**
 * Auto-generated icon: IconBrandStorybook
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandStorybook as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandStorybook = createIcon(TablerIcon)
