/**
 * Auto-generated icon: IconLayoutAlignMiddleFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLayoutAlignMiddleFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLayoutAlignMiddleFilled = createIcon(TablerIcon)
