/**
 * Auto-generated icon: IconDice6Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDice6Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDice6Filled = createIcon(TablerIcon)
