/**
 * Auto-generated icon: IconFlagDollar
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFlagDollar as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFlagDollar = createIcon(TablerIcon)
