/**
 * Auto-generated icon: IconMathNot
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMathNot as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMathNot = createIcon(TablerIcon)
