/**
 * Auto-generated icon: IconBrandSnapchat
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandSnapchat as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandSnapchat = createIcon(TablerIcon)
