/**
 * Auto-generated icon: IconWashDryFlat
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconWashDryFlat as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconWashDryFlat = createIcon(TablerIcon)
