/**
 * Auto-generated icon: IconChessBishop
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconChessBishop as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconChessBishop = createIcon(TablerIcon)
