/**
 * Auto-generated icon: IconLetterKSmall
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLetterKSmall as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLetterKSmall = createIcon(TablerIcon)
