/**
 * Auto-generated icon: IconWashDryF
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconWashDryF as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconWashDryF = createIcon(TablerIcon)
