/**
 * Auto-generated icon: IconTrianglePlus2
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTrianglePlus2 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTrianglePlus2 = createIcon(TablerIcon)
