/**
 * Auto-generated icon: IconInputX
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconInputX as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconInputX = createIcon(TablerIcon)
