/**
 * Auto-generated icon: IconBrandKick
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandKick as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandKick = createIcon(TablerIcon)
