/**
 * Auto-generated icon: IconCornerUpRight
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCornerUpRight as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCornerUpRight = createIcon(TablerIcon)
