/**
 * Auto-generated icon: IconAlarmSnoozeFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAlarmSnoozeFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAlarmSnoozeFilled = createIcon(TablerIcon)
