/**
 * Auto-generated icon: IconTimelineEventFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTimelineEventFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTimelineEventFilled = createIcon(TablerIcon)
