/**
 * Auto-generated icon: IconMeteor
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMeteor as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMeteor = createIcon(TablerIcon)
