/**
 * Auto-generated icon: IconHexagonLetterY
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHexagonLetterY as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHexagonLetterY = createIcon(TablerIcon)
