/**
 * Auto-generated icon: IconBandageFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBandageFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBandageFilled = createIcon(TablerIcon)
