/**
 * Auto-generated icon: IconHelpCircleFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHelpCircleFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHelpCircleFilled = createIcon(TablerIcon)
