/**
 * Auto-generated icon: Icon12Hours
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { Icon12Hours as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const Icon12Hours = createIcon(TablerIcon)
