/**
 * Auto-generated icon: IconSquareNumber2
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareNumber2 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareNumber2 = createIcon(TablerIcon)
