/**
 * Auto-generated icon: IconFileTextShield
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileTextShield as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileTextShield = createIcon(TablerIcon)
