/**
 * Auto-generated icon: IconShredder
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconShredder as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconShredder = createIcon(TablerIcon)
