/**
 * Auto-generated icon: IconHandThreeFingers
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHandThreeFingers as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHandThreeFingers = createIcon(TablerIcon)
