/**
 * Auto-generated icon: IconFileWord
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileWord as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileWord = createIcon(TablerIcon)
