/**
 * Auto-generated icon: IconNumber11Small
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNumber11Small as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNumber11Small = createIcon(TablerIcon)
