/**
 * Auto-generated icon: IconAddressBook
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAddressBook as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAddressBook = createIcon(TablerIcon)
