/**
 * Auto-generated icon: IconBinaryTreeFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBinaryTreeFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBinaryTreeFilled = createIcon(TablerIcon)
