/**
 * Auto-generated icon: IconBrandBandcamp
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandBandcamp as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandBandcamp = createIcon(TablerIcon)
