/**
 * Auto-generated icon: IconSignature
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSignature as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSignature = createIcon(TablerIcon)
