/**
 * Auto-generated icon: IconBoxMultiple9
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBoxMultiple9 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBoxMultiple9 = createIcon(TablerIcon)
