/**
 * Auto-generated icon: IconRosetteDiscountCheckFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRosetteDiscountCheckFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRosetteDiscountCheckFilled = createIcon(TablerIcon)
