/**
 * Auto-generated icon: IconMoon
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMoon as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMoon = createIcon(TablerIcon)
