/**
 * Auto-generated icon: IconWaveSine
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconWaveSine as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconWaveSine = createIcon(TablerIcon)
