/**
 * Auto-generated icon: IconScubaDivingTankFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconScubaDivingTankFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconScubaDivingTankFilled = createIcon(TablerIcon)
