/**
 * Auto-generated icon: IconMilkFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMilkFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMilkFilled = createIcon(TablerIcon)
