/**
 * Auto-generated icon: IconBoxMultiple
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBoxMultiple as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBoxMultiple = createIcon(TablerIcon)
