/**
 * Auto-generated icon: IconCloudDownload
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCloudDownload as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCloudDownload = createIcon(TablerIcon)
