/**
 * Auto-generated icon: IconSortDescendingNumbers
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSortDescendingNumbers as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSortDescendingNumbers = createIcon(TablerIcon)
