/**
 * Auto-generated icon: IconBrandCupra
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandCupra as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandCupra = createIcon(TablerIcon)
