/**
 * Auto-generated icon: IconOctagonPlus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconOctagonPlus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconOctagonPlus = createIcon(TablerIcon)
