/**
 * Auto-generated icon: IconBuildingHospital
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBuildingHospital as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBuildingHospital = createIcon(TablerIcon)
