/**
 * Auto-generated icon: IconSquareLetterY
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareLetterY as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareLetterY = createIcon(TablerIcon)
