/**
 * Auto-generated icon: IconBrightnessFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrightnessFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrightnessFilled = createIcon(TablerIcon)
