/**
 * Auto-generated icon: IconBuildingBurjAlArab
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBuildingBurjAlArab as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBuildingBurjAlArab = createIcon(TablerIcon)
