/**
 * Auto-generated icon: IconBrandStorj
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandStorj as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandStorj = createIcon(TablerIcon)
