/**
 * Auto-generated icon: IconArrowsExchange
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowsExchange as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowsExchange = createIcon(TablerIcon)
