/**
 * Auto-generated icon: IconBowlFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBowlFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBowlFilled = createIcon(TablerIcon)
