/**
 * Auto-generated icon: IconDeviceTabletSearch
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceTabletSearch as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceTabletSearch = createIcon(TablerIcon)
