/**
 * Auto-generated icon: IconBrandSteam
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandSteam as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandSteam = createIcon(TablerIcon)
