/**
 * Auto-generated icon: IconSquareRoundedLetterE
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareRoundedLetterE as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareRoundedLetterE = createIcon(TablerIcon)
