/**
 * Auto-generated icon: IconBubble
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBubble as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBubble = createIcon(TablerIcon)
