/**
 * Auto-generated icon: IconGlassCocktail
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconGlassCocktail as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconGlassCocktail = createIcon(TablerIcon)
