/**
 * Auto-generated icon: IconRewindForward5
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRewindForward5 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRewindForward5 = createIcon(TablerIcon)
