/**
 * Auto-generated icon: IconBrandBaidu
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandBaidu as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandBaidu = createIcon(TablerIcon)
