/**
 * Auto-generated icon: IconArrowAutofitRight
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowAutofitRight as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowAutofitRight = createIcon(TablerIcon)
