/**
 * Auto-generated icon: IconSphere
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSphere as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSphere = createIcon(TablerIcon)
