/**
 * Auto-generated icon: IconTxt
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTxt as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTxt = createIcon(TablerIcon)
