/**
 * Auto-generated icon: IconMessage2Up
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMessage2Up as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMessage2Up = createIcon(TablerIcon)
