/**
 * Auto-generated icon: IconPointerStar
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPointerStar as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPointerStar = createIcon(TablerIcon)
