/**
 * Auto-generated icon: IconPaintFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPaintFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPaintFilled = createIcon(TablerIcon)
