/**
 * Auto-generated icon: IconTree
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTree as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTree = createIcon(TablerIcon)
