/**
 * Auto-generated icon: IconShoppingBagX
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconShoppingBagX as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconShoppingBagX = createIcon(TablerIcon)
