/**
 * Auto-generated icon: IconCircle8
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircle8 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircle8 = createIcon(TablerIcon)
