/**
 * Auto-generated icon: IconCurrencyRenminbi
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCurrencyRenminbi as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCurrencyRenminbi = createIcon(TablerIcon)
