/**
 * Auto-generated icon: IconTimeDuration0
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTimeDuration0 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTimeDuration0 = createIcon(TablerIcon)
