/**
 * Auto-generated icon: IconDevicesCog
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDevicesCog as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDevicesCog = createIcon(TablerIcon)
