/**
 * Auto-generated icon: IconBrandRadixUi
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandRadixUi as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandRadixUi = createIcon(TablerIcon)
