/**
 * Auto-generated icon: IconSquareRoundedLetterL
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareRoundedLetterL as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareRoundedLetterL = createIcon(TablerIcon)
