/**
 * Auto-generated icon: IconSquareRoundedChevronLeftFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareRoundedChevronLeftFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareRoundedChevronLeftFilled = createIcon(TablerIcon)
