/**
 * Auto-generated icon: IconEyeShare
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconEyeShare as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconEyeShare = createIcon(TablerIcon)
