/**
 * Auto-generated icon: IconDeviceMobileCancel
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceMobileCancel as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceMobileCancel = createIcon(TablerIcon)
