/**
 * Auto-generated icon: IconVectorTriangleOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconVectorTriangleOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconVectorTriangleOff = createIcon(TablerIcon)
