/**
 * Auto-generated icon: IconCircleDashedLetterH
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleDashedLetterH as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleDashedLetterH = createIcon(TablerIcon)
