/**
 * Auto-generated icon: IconFileTypePng
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileTypePng as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileTypePng = createIcon(TablerIcon)
