/**
 * Auto-generated icon: IconCameraDown
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCameraDown as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCameraDown = createIcon(TablerIcon)
