/**
 * Auto-generated icon: IconMessage2Pause
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMessage2Pause as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMessage2Pause = createIcon(TablerIcon)
