/**
 * Auto-generated icon: IconCell
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCell as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCell = createIcon(TablerIcon)
