/**
 * Auto-generated icon: IconFileHorizontal
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileHorizontal as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileHorizontal = createIcon(TablerIcon)
