/**
 * Auto-generated icon: IconLamp
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLamp as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLamp = createIcon(TablerIcon)
