/**
 * Auto-generated icon: IconChartDonut2
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconChartDonut2 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconChartDonut2 = createIcon(TablerIcon)
