/**
 * Auto-generated icon: IconBoxAlignBottomLeft
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBoxAlignBottomLeft as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBoxAlignBottomLeft = createIcon(TablerIcon)
