/**
 * Auto-generated icon: IconDeviceIpadOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceIpadOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceIpadOff = createIcon(TablerIcon)
