/**
 * Auto-generated icon: IconCarambola
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCarambola as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCarambola = createIcon(TablerIcon)
