/**
 * Auto-generated icon: IconInnerShadowTopFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconInnerShadowTopFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconInnerShadowTopFilled = createIcon(TablerIcon)
