/**
 * Auto-generated icon: IconFilterSpark
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFilterSpark as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFilterSpark = createIcon(TablerIcon)
