/**
 * Auto-generated icon: IconCircleDashedNumber6
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleDashedNumber6 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleDashedNumber6 = createIcon(TablerIcon)
