/**
 * Auto-generated icon: IconScoreboard
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconScoreboard as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconScoreboard = createIcon(TablerIcon)
