/**
 * Auto-generated icon: IconRewindForward60
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRewindForward60 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRewindForward60 = createIcon(TablerIcon)
