/**
 * Auto-generated icon: IconCrane
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCrane as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCrane = createIcon(TablerIcon)
