/**
 * Auto-generated icon: IconRelationManyToMany
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRelationManyToMany as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRelationManyToMany = createIcon(TablerIcon)
