/**
 * Auto-generated icon: IconTagsFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTagsFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTagsFilled = createIcon(TablerIcon)
