/**
 * Auto-generated icon: IconBadge3d
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBadge3d as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBadge3d = createIcon(TablerIcon)
