/**
 * Auto-generated icon: IconCircleCheckFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleCheckFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleCheckFilled = createIcon(TablerIcon)
