/**
 * Auto-generated icon: IconCarFan
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCarFan as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCarFan = createIcon(TablerIcon)
