/**
 * Auto-generated icon: IconPlayCard10Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPlayCard10Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPlayCard10Filled = createIcon(TablerIcon)
