/**
 * Auto-generated icon: IconHexagonLetterRFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHexagonLetterRFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHexagonLetterRFilled = createIcon(TablerIcon)
