/**
 * Auto-generated icon: IconAxisY
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAxisY as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAxisY = createIcon(TablerIcon)
