/**
 * Auto-generated icon: IconGaugeFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconGaugeFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconGaugeFilled = createIcon(TablerIcon)
