/**
 * Auto-generated icon: IconBrandPaypal
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandPaypal as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandPaypal = createIcon(TablerIcon)
