/**
 * Auto-generated icon: IconFileTypePdf
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileTypePdf as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileTypePdf = createIcon(TablerIcon)
