/**
 * Auto-generated icon: IconMenu2
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMenu2 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMenu2 = createIcon(TablerIcon)
