/**
 * Auto-generated icon: IconBrandZeit
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandZeit as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandZeit = createIcon(TablerIcon)
