/**
 * Auto-generated icon: IconAlignBoxLeftBottomFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAlignBoxLeftBottomFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAlignBoxLeftBottomFilled = createIcon(TablerIcon)
