/**
 * Auto-generated icon: IconCoinMoneroFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCoinMoneroFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCoinMoneroFilled = createIcon(TablerIcon)
