/**
 * Auto-generated icon: IconZoomOutFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconZoomOutFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconZoomOutFilled = createIcon(TablerIcon)
