/**
 * Auto-generated icon: IconHttpPatchOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHttpPatchOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHttpPatchOff = createIcon(TablerIcon)
