/**
 * Auto-generated icon: IconCandle
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCandle as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCandle = createIcon(TablerIcon)
