/**
 * Auto-generated icon: IconTriangles
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTriangles as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTriangles = createIcon(TablerIcon)
