/**
 * Auto-generated icon: IconHeartCode
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHeartCode as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHeartCode = createIcon(TablerIcon)
