/**
 * Auto-generated icon: IconLockOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLockOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLockOff = createIcon(TablerIcon)
