/**
 * Auto-generated icon: IconHttpConnectOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHttpConnectOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHttpConnectOff = createIcon(TablerIcon)
