/**
 * Auto-generated icon: IconWorldCog
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconWorldCog as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconWorldCog = createIcon(TablerIcon)
