/**
 * Auto-generated icon: IconDeviceTabletHeart
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceTabletHeart as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceTabletHeart = createIcon(TablerIcon)
