/**
 * Auto-generated icon: IconMapPinExclamation
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMapPinExclamation as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMapPinExclamation = createIcon(TablerIcon)
