/**
 * Auto-generated icon: IconNumber12Small
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNumber12Small as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNumber12Small = createIcon(TablerIcon)
