/**
 * Auto-generated icon: IconFileSearch
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileSearch as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileSearch = createIcon(TablerIcon)
