/**
 * Auto-generated icon: IconBadgeTm
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBadgeTm as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBadgeTm = createIcon(TablerIcon)
