/**
 * Auto-generated icon: IconBrandNationalGeographic
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandNationalGeographic as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandNationalGeographic = createIcon(TablerIcon)
