/**
 * Auto-generated icon: IconFile3d
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFile3d as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFile3d = createIcon(TablerIcon)
