/**
 * Auto-generated icon: IconRippleOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRippleOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRippleOff = createIcon(TablerIcon)
