/**
 * Auto-generated icon: IconSquareLetterC
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareLetterC as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareLetterC = createIcon(TablerIcon)
