/**
 * Auto-generated icon: IconRewindForward15
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRewindForward15 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRewindForward15 = createIcon(TablerIcon)
