/**
 * Auto-generated icon: IconCircleDashedLetterX
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleDashedLetterX as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleDashedLetterX = createIcon(TablerIcon)
