/**
 * Auto-generated icon: IconCircuitBulb
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircuitBulb as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircuitBulb = createIcon(TablerIcon)
