/**
 * Auto-generated icon: IconDeviceIpadHorizontalBolt
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceIpadHorizontalBolt as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceIpadHorizontalBolt = createIcon(TablerIcon)
