/**
 * Auto-generated icon: IconCannabisFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCannabisFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCannabisFilled = createIcon(TablerIcon)
