/**
 * Auto-generated icon: IconPlayerPlayFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPlayerPlayFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPlayerPlayFilled = createIcon(TablerIcon)
