/**
 * Auto-generated icon: IconBrandGolang
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandGolang as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandGolang = createIcon(TablerIcon)
