/**
 * Auto-generated icon: IconCameraBolt
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCameraBolt as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCameraBolt = createIcon(TablerIcon)
