/**
 * Auto-generated icon: IconBrandSnowflake
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandSnowflake as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandSnowflake = createIcon(TablerIcon)
