/**
 * Auto-generated icon: IconActivityHeartbeat
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconActivityHeartbeat as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconActivityHeartbeat = createIcon(TablerIcon)
