/**
 * Auto-generated icon: IconLockDown
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLockDown as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLockDown = createIcon(TablerIcon)
