/**
 * Auto-generated icon: IconBrandVimeo
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandVimeo as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandVimeo = createIcon(TablerIcon)
