/**
 * Auto-generated icon: IconFileFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFileFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFileFilled = createIcon(TablerIcon)
