/**
 * Auto-generated icon: IconDog
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDog as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDog = createIcon(TablerIcon)
