/**
 * Auto-generated icon: IconNavigationSouth
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconNavigationSouth as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconNavigationSouth = createIcon(TablerIcon)
