/**
 * Auto-generated icon: IconCircleDottedLetterI
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleDottedLetterI as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleDottedLetterI = createIcon(TablerIcon)
