/**
 * Auto-generated icon: IconSquareNumber7Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareNumber7Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareNumber7Filled = createIcon(TablerIcon)
