/**
 * Auto-generated icon: IconSquareArrowDownFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareArrowDownFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareArrowDownFilled = createIcon(TablerIcon)
