/**
 * Auto-generated icon: IconSkiJumping
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSkiJumping as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSkiJumping = createIcon(TablerIcon)
