/**
 * Auto-generated icon: IconLayoutList
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLayoutList as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLayoutList = createIcon(TablerIcon)
