/**
 * Auto-generated icon: IconZoomScanFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconZoomScanFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconZoomScanFilled = createIcon(TablerIcon)
