/**
 * Auto-generated icon: IconHourglassOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHourglassOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHourglassOff = createIcon(TablerIcon)
