/**
 * Auto-generated icon: IconBrandZoom
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandZoom as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandZoom = createIcon(TablerIcon)
