/**
 * Auto-generated icon: IconTrafficCone
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconTrafficCone as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconTrafficCone = createIcon(TablerIcon)
