/**
 * Auto-generated icon: IconSquareRoundedLetterKFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareRoundedLetterKFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareRoundedLetterKFilled = createIcon(TablerIcon)
