/**
 * Auto-generated icon: IconEyeSpark
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconEyeSpark as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconEyeSpark = createIcon(TablerIcon)
