/**
 * Auto-generated icon: IconBrandTypescript
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandTypescript as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandTypescript = createIcon(TablerIcon)
