/**
 * Auto-generated icon: IconHeartCheck
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHeartCheck as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHeartCheck = createIcon(TablerIcon)
