/**
 * Auto-generated icon: IconEngineFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconEngineFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconEngineFilled = createIcon(TablerIcon)
