/**
 * Auto-generated icon: IconMessageBolt
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMessageBolt as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMessageBolt = createIcon(TablerIcon)
