/**
 * Auto-generated icon: IconFlask2Off
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFlask2Off as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFlask2Off = createIcon(TablerIcon)
