/**
 * Auto-generated icon: IconDeviceComputerCameraOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceComputerCameraOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceComputerCameraOff = createIcon(TablerIcon)
