/**
 * Auto-generated icon: IconFolderDown
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFolderDown as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFolderDown = createIcon(TablerIcon)
