/**
 * Auto-generated icon: IconAdjustmentsDollar
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAdjustmentsDollar as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAdjustmentsDollar = createIcon(TablerIcon)
