/**
 * Auto-generated icon: IconSquareArrowRightFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareArrowRightFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareArrowRightFilled = createIcon(TablerIcon)
