/**
 * Auto-generated icon: IconSwipeDownFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSwipeDownFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSwipeDownFilled = createIcon(TablerIcon)
