/**
 * Auto-generated icon: IconDropletCog
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDropletCog as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDropletCog = createIcon(TablerIcon)
