/**
 * Auto-generated icon: IconRoadSign
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRoadSign as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRoadSign = createIcon(TablerIcon)
