/**
 * Auto-generated icon: IconDeviceIpadHorizontalExclamation
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDeviceIpadHorizontalExclamation as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDeviceIpadHorizontalExclamation = createIcon(TablerIcon)
