/**
 * Auto-generated icon: IconShapeOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconShapeOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconShapeOff = createIcon(TablerIcon)
