/**
 * Auto-generated icon: IconLamp2
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLamp2 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLamp2 = createIcon(TablerIcon)
