/**
 * Auto-generated icon: IconBasketStar
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBasketStar as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBasketStar = createIcon(TablerIcon)
