/**
 * Auto-generated icon: IconChalkboardTeacher
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconChalkboardTeacher as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconChalkboardTeacher = createIcon(TablerIcon)
