/**
 * Auto-generated icon: IconBlender
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBlender as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBlender = createIcon(TablerIcon)
