/**
 * Auto-generated icon: IconBrandPushbullet
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandPushbullet as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandPushbullet = createIcon(TablerIcon)
