/**
 * Auto-generated icon: IconCalendarBolt
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCalendarBolt as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCalendarBolt = createIcon(TablerIcon)
