/**
 * Auto-generated icon: IconMathXMinusY
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMathXMinusY as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMathXMinusY = createIcon(TablerIcon)
