/**
 * Auto-generated icon: IconFlaskOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFlaskOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFlaskOff = createIcon(TablerIcon)
