/**
 * Auto-generated icon: IconBrandBehance
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandBehance as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandBehance = createIcon(TablerIcon)
