/**
 * Auto-generated icon: IconBold
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBold as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBold = createIcon(TablerIcon)
