/**
 * Auto-generated icon: IconBrandCampaignmonitor
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandCampaignmonitor as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandCampaignmonitor = createIcon(TablerIcon)
