/**
 * Auto-generated icon: IconMeterCube
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMeterCube as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMeterCube = createIcon(TablerIcon)
