/**
 * Auto-generated icon: IconRosetteNumber8
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRosetteNumber8 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRosetteNumber8 = createIcon(TablerIcon)
