/**
 * Auto-generated icon: IconFrustumOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFrustumOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFrustumOff = createIcon(TablerIcon)
