/**
 * Auto-generated icon: IconContainerFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconContainerFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconContainerFilled = createIcon(TablerIcon)
