/**
 * Auto-generated icon: IconSquareRoundedLetterS
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareRoundedLetterS as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareRoundedLetterS = createIcon(TablerIcon)
