/**
 * Auto-generated icon: IconPinEnd
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPinEnd as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPinEnd = createIcon(TablerIcon)
