/**
 * Auto-generated icon: IconLayoutNavbarCollapse
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLayoutNavbarCollapse as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLayoutNavbarCollapse = createIcon(TablerIcon)
