/**
 * Auto-generated icon: IconBrandTiktokFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandTiktokFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandTiktokFilled = createIcon(TablerIcon)
