/**
 * Auto-generated icon: IconSquare5
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquare5 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquare5 = createIcon(TablerIcon)
