/**
 * Auto-generated icon: IconVersionsOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconVersionsOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconVersionsOff = createIcon(TablerIcon)
