/**
 * Auto-generated icon: IconBrandShopee
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandShopee as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandShopee = createIcon(TablerIcon)
