/**
 * Auto-generated icon: IconDropletSearch
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDropletSearch as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDropletSearch = createIcon(TablerIcon)
