/**
 * Auto-generated icon: IconOctahedronOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconOctahedronOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconOctahedronOff = createIcon(TablerIcon)
