/**
 * Auto-generated icon: IconFile
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconFile as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconFile = createIcon(TablerIcon)
