/**
 * Auto-generated icon: IconMessage2Down
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMessage2Down as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMessage2Down = createIcon(TablerIcon)
