/**
 * Auto-generated icon: IconMessageCheck
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMessageCheck as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMessageCheck = createIcon(TablerIcon)
