/**
 * Auto-generated icon: IconSquareNumber2Filled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareNumber2Filled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareNumber2Filled = createIcon(TablerIcon)
