/**
 * Auto-generated icon: IconHospital
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHospital as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHospital = createIcon(TablerIcon)
