/**
 * Auto-generated icon: IconCameraShare
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCameraShare as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCameraShare = createIcon(TablerIcon)
