/**
 * Auto-generated icon: IconCrop54
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCrop54 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCrop54 = createIcon(TablerIcon)
