/**
 * Auto-generated icon: IconDirectionSign
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDirectionSign as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDirectionSign = createIcon(TablerIcon)
