/**
 * Auto-generated icon: IconHttpPatch
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHttpPatch as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHttpPatch = createIcon(TablerIcon)
