/**
 * Auto-generated icon: IconHelmet
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHelmet as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHelmet = createIcon(TablerIcon)
