/**
 * Auto-generated icon: IconUserQuestion
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconUserQuestion as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconUserQuestion = createIcon(TablerIcon)
