/**
 * Auto-generated icon: IconLetterSpacing
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconLetterSpacing as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconLetterSpacing = createIcon(TablerIcon)
