/**
 * Auto-generated icon: IconUserCircle
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconUserCircle as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconUserCircle = createIcon(TablerIcon)
