/**
 * Auto-generated icon: IconRadioactiveOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconRadioactiveOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconRadioactiveOff = createIcon(TablerIcon)
