/**
 * Auto-generated icon: IconBroadcast
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBroadcast as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBroadcast = createIcon(TablerIcon)
