/**
 * Auto-generated icon: IconEggCrackedFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconEggCrackedFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconEggCrackedFilled = createIcon(TablerIcon)
