/**
 * Auto-generated icon: IconHexagonNumber9
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHexagonNumber9 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHexagonNumber9 = createIcon(TablerIcon)
