/**
 * Auto-generated icon: IconMessageCircleBolt
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMessageCircleBolt as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMessageCircleBolt = createIcon(TablerIcon)
