/**
 * Auto-generated icon: IconBadge8kFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBadge8kFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBadge8kFilled = createIcon(TablerIcon)
