/**
 * Auto-generated icon: IconMoodWrrr
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMoodWrrr as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMoodWrrr = createIcon(TablerIcon)
