/**
 * Auto-generated icon: IconGenderGenderqueer
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconGenderGenderqueer as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconGenderGenderqueer = createIcon(TablerIcon)
