/**
 * Auto-generated icon: IconGift
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconGift as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconGift = createIcon(TablerIcon)
