/**
 * Auto-generated icon: IconVectorBezier
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconVectorBezier as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconVectorBezier = createIcon(TablerIcon)
