/**
 * Auto-generated icon: IconMathGreater
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconMathGreater as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconMathGreater = createIcon(TablerIcon)
