/**
 * Auto-generated icon: IconBrandMyOppo
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandMyOppo as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandMyOppo = createIcon(TablerIcon)
