/**
 * Auto-generated icon: IconHeartFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHeartFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHeartFilled = createIcon(TablerIcon)
