/**
 * Auto-generated icon: IconBatteryVerticalOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBatteryVerticalOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBatteryVerticalOff = createIcon(TablerIcon)
