/**
 * Auto-generated icon: IconSettingsSpark
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSettingsSpark as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSettingsSpark = createIcon(TablerIcon)
