/**
 * Auto-generated icon: IconBrandDatabricks
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandDatabricks as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandDatabricks = createIcon(TablerIcon)
