/**
 * Auto-generated icon: IconBaseline
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBaseline as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBaseline = createIcon(TablerIcon)
