/**
 * Auto-generated icon: IconCreditCardOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCreditCardOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCreditCardOff = createIcon(TablerIcon)
