/**
 * Auto-generated icon: IconHomeSearch
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHomeSearch as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHomeSearch = createIcon(TablerIcon)
