/**
 * Auto-generated icon: IconArrowUpCircleFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowUpCircleFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowUpCircleFilled = createIcon(TablerIcon)
