/**
 * Auto-generated icon: IconCircleNumber9
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleNumber9 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleNumber9 = createIcon(TablerIcon)
