/**
 * Auto-generated icon: IconBrandFlipboard
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandFlipboard as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandFlipboard = createIcon(TablerIcon)
