/**
 * Auto-generated icon: IconSpherePlus
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSpherePlus as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSpherePlus = createIcon(TablerIcon)
