/**
 * Auto-generated icon: IconBrandOnlyfans
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandOnlyfans as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandOnlyfans = createIcon(TablerIcon)
