/**
 * Auto-generated icon: IconSos
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSos as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSos = createIcon(TablerIcon)
