/**
 * Auto-generated icon: IconBatteryVertical4
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBatteryVertical4 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBatteryVertical4 = createIcon(TablerIcon)
