/**
 * Auto-generated icon: IconBadgeVo
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBadgeVo as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBadgeVo = createIcon(TablerIcon)
