/**
 * Auto-generated icon: IconCircuitSwitchClosed
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircuitSwitchClosed as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircuitSwitchClosed = createIcon(TablerIcon)
