/**
 * Auto-generated icon: IconAdjustmentsStar
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconAdjustmentsStar as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconAdjustmentsStar = createIcon(TablerIcon)
