/**
 * Auto-generated icon: IconCalendarDot
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCalendarDot as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCalendarDot = createIcon(TablerIcon)
