/**
 * Auto-generated icon: IconArrowLeft
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowLeft as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowLeft = createIcon(TablerIcon)
