/**
 * Auto-generated icon: IconBadgesOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBadgesOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBadgesOff = createIcon(TablerIcon)
