/**
 * Auto-generated icon: IconCreativeCommonsOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCreativeCommonsOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCreativeCommonsOff = createIcon(TablerIcon)
