/**
 * Auto-generated icon: IconPhotoSquareRounded
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconPhotoSquareRounded as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconPhotoSquareRounded = createIcon(TablerIcon)
