/**
 * Auto-generated icon: IconStackForward
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconStackForward as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconStackForward = createIcon(TablerIcon)
