/**
 * Auto-generated icon: IconDiamonds
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDiamonds as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDiamonds = createIcon(TablerIcon)
