/**
 * Auto-generated icon: IconScribble
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconScribble as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconScribble = createIcon(TablerIcon)
