/**
 * Auto-generated icon: IconArrowDownTail
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconArrowDownTail as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconArrowDownTail = createIcon(TablerIcon)
