/**
 * Auto-generated icon: IconBookmarksOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBookmarksOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBookmarksOff = createIcon(TablerIcon)
