/**
 * Auto-generated icon: IconBrandEmber
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandEmber as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandEmber = createIcon(TablerIcon)
