/**
 * Auto-generated icon: IconCircleNumber0
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCircleNumber0 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCircleNumber0 = createIcon(TablerIcon)
