/**
 * Auto-generated icon: IconCarFan1
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCarFan1 as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCarFan1 = createIcon(TablerIcon)
