/**
 * Auto-generated icon: IconSquareLetterL
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconSquareLetterL as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconSquareLetterL = createIcon(TablerIcon)
