/**
 * Auto-generated icon: IconScreenshot
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconScreenshot as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconScreenshot = createIcon(TablerIcon)
