/**
 * Auto-generated icon: IconHemisphereOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHemisphereOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHemisphereOff = createIcon(TablerIcon)
