/**
 * Auto-generated icon: IconBugOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBugOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBugOff = createIcon(TablerIcon)
