/**
 * Auto-generated icon: IconBadgeSd
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBadgeSd as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBadgeSd = createIcon(TablerIcon)
