/**
 * Auto-generated icon: IconDropletShare
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconDropletShare as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconDropletShare = createIcon(TablerIcon)
