/**
 * Auto-generated icon: IconBrandLastfm
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBrandLastfm as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBrandLastfm = createIcon(TablerIcon)
