/**
 * Auto-generated icon: IconHexagonLetterWFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconHexagonLetterWFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconHexagonLetterWFilled = createIcon(TablerIcon)
