/**
 * Auto-generated icon: IconCalendarWeekFilled
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconCalendarWeekFilled as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconCalendarWeekFilled = createIcon(TablerIcon)
