/**
 * Auto-generated icon: IconBiohazardOff
 * DO NOT EDIT - Generated by: pnpm generate-icons
 */
import { IconBiohazardOff as TablerIcon } from '@tabler/icons-vue'
import { createIcon } from '../wrapper'

export const IconBiohazardOff = createIcon(TablerIcon)
