import { defineComponent, h, type Component, type PropType } from 'vue'
import { IconApi } from '@a2ui/web_core/v0_9/basic_catalog'
import {
  IconAlertCircle,
  IconAlertTriangle,
  IconArrowLeft,
  IconArrowRight,
  IconBell,
  IconBellOff,
  IconCalendar,
  IconCalendarEvent,
  IconCamera,
  IconCheck,
  IconCreditCard,
  IconDots,
  IconDotsVertical,
  IconDownload,
  IconEdit,
  IconEye,
  IconEyeOff,
  IconFolder,
  IconHeart,
  IconHeartOff,
  IconHelp,
  IconHome,
  IconInfoCircle,
  IconLock,
  IconLockOpen,
  IconMail,
  IconMapPin,
  IconMenu2,
  IconPaperclip,
  IconPhone,
  IconPhoto,
  IconPlayerPause,
  IconPlayerPlay,
  IconPlayerSkipBack,
  IconPlayerSkipForward,
  IconPlayerStop,
  IconPlayerTrackNext,
  IconPlayerTrackPrev,
  IconPlus,
  IconPoint,
  IconPrinter,
  IconRefresh,
  IconSearch,
  IconSend,
  IconSettings,
  IconShare,
  IconShoppingCart,
  IconStar,
  IconStarHalf,
  IconStarOff,
  IconTrash,
  IconUpload,
  IconUser,
  IconUserCircle,
  IconVolume,
  IconVolume2,
  IconVolume3,
  IconVolumeOff,
  IconX,
} from '@meldui/tabler-vue'
import { defineVueComponent } from '../../define'
import type { A2uiRenderProps } from '../../types'

// A2UI material-style icon names → Tabler icon components.
const ICONS: Record<string, Component> = {
  accountCircle: IconUserCircle,
  add: IconPlus,
  arrowBack: IconArrowLeft,
  arrowForward: IconArrowRight,
  attachFile: IconPaperclip,
  calendarToday: IconCalendar,
  call: IconPhone,
  camera: IconCamera,
  check: IconCheck,
  close: IconX,
  delete: IconTrash,
  download: IconDownload,
  edit: IconEdit,
  event: IconCalendarEvent,
  error: IconAlertCircle,
  fastForward: IconPlayerTrackNext,
  favorite: IconHeart,
  favoriteOff: IconHeartOff,
  folder: IconFolder,
  help: IconHelp,
  home: IconHome,
  info: IconInfoCircle,
  locationOn: IconMapPin,
  lock: IconLock,
  lockOpen: IconLockOpen,
  mail: IconMail,
  menu: IconMenu2,
  moreVert: IconDotsVertical,
  moreHoriz: IconDots,
  notificationsOff: IconBellOff,
  notifications: IconBell,
  pause: IconPlayerPause,
  payment: IconCreditCard,
  person: IconUser,
  phone: IconPhone,
  photo: IconPhoto,
  play: IconPlayerPlay,
  print: IconPrinter,
  refresh: IconRefresh,
  rewind: IconPlayerTrackPrev,
  search: IconSearch,
  send: IconSend,
  settings: IconSettings,
  share: IconShare,
  shoppingCart: IconShoppingCart,
  skipNext: IconPlayerSkipForward,
  skipPrevious: IconPlayerSkipBack,
  star: IconStar,
  starHalf: IconStarHalf,
  starOff: IconStarOff,
  stop: IconPlayerStop,
  upload: IconUpload,
  visibility: IconEye,
  visibilityOff: IconEyeOff,
  volumeDown: IconVolume2,
  volumeMute: IconVolume3,
  volumeOff: IconVolumeOff,
  volumeUp: IconVolume,
  warning: IconAlertTriangle,
}

const MeldIcon = defineComponent({
  name: 'MeldIcon',
  props: { p: { type: Object as PropType<A2uiRenderProps['p']>, required: true } },
  setup(props) {
    return () => {
      const name = props.p.name
      // Custom inline SVG path.
      if (name && typeof name === 'object' && 'svgPath' in (name as object)) {
        return h(
          'svg',
          {
            width: 20,
            height: 20,
            viewBox: '0 0 24 24',
            fill: 'currentColor',
            'data-a2ui': 'Icon',
          },
          [h('path', { d: (name as { svgPath: string }).svgPath })],
        )
      }
      const Comp = (typeof name === 'string' ? ICONS[name] : undefined) ?? IconPoint
      return h(Comp, { size: 20, 'data-a2ui': 'Icon' })
    }
  },
})

export const iconEntry = defineVueComponent(IconApi, MeldIcon)
