import { copyFileSync, existsSync, mkdirSync } from 'node:fs'
import { resolve } from 'node:path'
import { defineConfig, type Plugin } from 'vite'
import dts from 'vite-plugin-dts'

/**
 * Copies the generated catalog artifact into dist so it can be published and
 * served via the `@meldui/a2ui/catalog` package export. The catalog itself is
 * generated by `scripts/generate-catalog.ts` (run via the `build` script
 * before vite) and committed under `src/schema/`.
 */
function copyCatalog(): Plugin {
  return {
    name: 'meldui-a2ui-copy-catalog',
    closeBundle() {
      const src = resolve(__dirname, 'src/schema/meldui-v1.catalog.json')
      const outDir = resolve(__dirname, 'dist/schema')
      if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true })
      copyFileSync(src, resolve(outDir, 'meldui-v1.catalog.json'))
    },
  }
}

export default defineConfig({
  plugins: [
    dts({
      tsconfigPath: './tsconfig.json',
      rollupTypes: true,
      include: ['src/**/*'],
    }),
    copyCatalog(),
  ],
  build: {
    lib: {
      entry: {
        index: resolve(__dirname, 'src/index.ts'),
        'vue/index': resolve(__dirname, 'src/vue/index.ts'),
      },
      formats: ['es', 'cjs'],
      fileName: (format, entryName) => `${entryName}.${format === 'es' ? 'mjs' : 'cjs'}`,
    },
    rollupOptions: {
      // Keep the framework-agnostic contract free of these; the Vue renderer
      // entry treats them all as externals (peers / protocol core).
      external: ['vue', /^@meldui\//, /^@a2ui\//, /^@incremark\//, 'zod', '@preact/signals-core'],
    },
    sourcemap: true,
    emptyOutDir: true,
  },
})
